ChainSafe/forest

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/general_report.md
- .github/ISSUE_TEMPLATE/task_req.md
- README.md
- Updated markdown for readme and templates
> Updated markdown for readme and templates

- ipld/cid/src/error.rs
- ipld/cid/src/to_cid.rs
- ipld/cid/tests/serde_tests.rs
- node/db/src/errors.rs
- node/utils/src/lib.rs
- vm/address/src/lib.rs
- Just updating to clear warnings on nightly to be proactive
Closes 
> Clear warnings for new nightly toolchain rule

- vm/actor/src/builtin/account.rs
- vm/actor/src/builtin/cron.rs
- vm/actor/src/builtin/init.rs
- vm/actor/src/builtin/reward.rs
- vm/actor/src/builtin/storage_power.rs
- vm/src/exit_code.rs
- Update exit codes to specs-actor latest version
Closes 
#257 
> Update exit codes

- blockchain/chain_sync/Cargo.toml
- blockchain/chain_sync/src/sync.rs
- node/clock/src/lib.rs
- vm/actor/Cargo.toml
- vm/actor/src/builtin/cron/mod.rs
- vm/actor/src/builtin/mod.rs
- vm/actor/src/builtin/multisig/mod.rs
- vm/actor/src/builtin/paych/mod.rs
- vm/actor/src/builtin/paych/state.rs
- vm/actor/src/builtin/paych/types.rs
- vm/message/src/lib.rs
- vm/message/src/signed_message.rs
- vm/message/src/unsigned_message.rs
- vm/message/tests/builder_test.rs
- vm/runtime/src/lib.rs
- vm/src/actor_state.rs
- vm/src/method.rs
- vm/src/token.rs
- vm/state_tree/tests/state_tree_tests.rs
- Implement payment channel actor #267 
- Update message types (was using BigUint for gas price but that really should have been a TokenAmount value (doesn't change much)
- Updates related types as well
Closes #267
> Payment channel actor

- vm/runtime/src/lib.rs
Whew that was hard!
Closes 
#302 
> Blake2b syscall

- .github/workflows/ci-rust.yml
- Cargo.toml
- Makefile
- ipld/cid/src/lib.rs
- utils/commcid/Cargo.toml
- utils/commcid/src/lib.rs
- utils/commcid/tests/commcid_tests.rs
- vm/actor/src/builtin/codes.rs
- #355 https://github.com/filecoin-project/go-fil-commcid
- Pretty strightforward, pretty close to a 1:1 port
- Needed for proofs
Closes 
#355 
> Commitment to cid conversions

- blockchain/blocks/Cargo.toml
- blockchain/chain_sync/Cargo.toml
- forest/Cargo.toml
- node/db/Cargo.toml
- node/db/src/rocks.rs
- node/forest_libp2p/Cargo.toml
- tests/serialization_tests/Cargo.toml
- utils/test_utils/Cargo.toml
- bump async-std from 1.4 to 1.5
- bump base64 from 1.12.0 to 1.12.1
- bump rocksdb from 1.13.0 to 1.14.0
Closes 
> Bump Dependencies

- forest/Cargo.toml
- forest/src/cli/genesis.rs
- forest/src/cli/mod.rs
- forest/src/main.rs
- Refactors CLI to use structops rather than Clap cuts off a lot of code
-A few syntax changes
https://crates.io/crates/structopt
> refactor with structops macro

- blockchain/blocks/src/header.rs
- blockchain/chain_sync/src/bucket.rs
- node/forest_libp2p/tests/decode_test.rs
- vm/actor/src/builtin/paych/state.rs
- vm/actor/src/builtin/paych/types.rs
- vm/actor/tests/common/mod.rs
- vm/address/src/lib.rs
- vm/address/src/payload.rs
- vm/address/src/protocol.rs
- vm/interpreter/src/gas_syscalls.rs
- Just for safety so it can't be misused this way
- Could technically also be done for Cid, but the ergonomics of that is a way higher cost than this
Closes 
> Remove Address default implementation

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- forest/Cargo.toml
- ipld/blockstore/Cargo.toml
- ipld/blockstore/src/lib.rs
- node/db/Cargo.toml
- node/db/src/errors.rs
- node/db/src/lib.rs
- node/db/src/rocks.rs
- node/db/tests/db_utils/mod.rs
- node/db/tests/rocks_test.rs
- Separate rocksdb usage into feature
- No need to have to compile all of that when it's just used inside the `forest` crate, it was starting to get annoying
- Update docs to indicate for #420 
- If anyone has something useful to link for this please comment, it is an OS specific installation and no good central resource that's useful that I could find
- Update PR template
- Has been slightly bugging me for awhile but way it is people always put the issue on the next line and it doesn't connect to auto close issue
Closes #420
> Update docs and use rocksdb as feature

- crypto/Cargo.toml
- crypto/src/signature.rs
- utils/test_utils/src/chain_structures.rs
- vm/Cargo.toml
- vm/actor/tests/account_actor_test.rs
- vm/address/Cargo.toml
- vm/address/src/errors.rs
- vm/address/src/lib.rs
- vm/address/tests/address_test.rs
- vm/message/Cargo.toml
- vm/state_tree/tests/state_tree_tests.rs
https://github.com/filecoin-project/specs/pull/872/files
Was recently merged into spec and was suggestion from @jleni to add the sanity check validation for safer usage
Unfortunately the minor version has to be bumped because it's API breaking change
Closes 
> Add Secp address sanity check

- crypto/Cargo.toml
- encoding/Cargo.toml
- Missed the breaking change in crypto which uses the tuple serialize library added in the crypto package, so bumped version and published them, but just to be safe going to pull this in
Closes 
> Update encoding package version

- blockchain/beacon/Cargo.toml
- blockchain/chain_sync/Cargo.toml
- forest/Cargo.toml
- ipld/Cargo.toml
- ipld/graphsync/Cargo.toml
- node/forest_libp2p/Cargo.toml
- utils/test_utils/Cargo.toml
- async-std 1.6 introduces a the new smol runtime. Want to upgrade now to make sure there are no surprises in the future with compatibility
Closes 
> Bump to async-std 1.6

- blockchain/chain_sync/src/sync.rs
- blockchain/state_manager/src/lib.rs
- crypto/src/signature.rs
- vm/address/src/lib.rs
- Just handles better after the Address refactor
Closes 
> Switch bls pub key from using vec

- .github/workflows/ci-rust.yml
- oops, change must have been lost on an branch pull
Closes 
> Fix docs publish rule

- Cargo.lock
- blockchain/chain_sync/Cargo.toml
- blockchain/state_manager/Cargo.toml
- crypto/Cargo.toml
- crypto/src/signature.rs
- types/Cargo.toml
- utils/commcid/Cargo.toml
- vm/runtime/Cargo.toml
- Updates proofs-api to 4.0.1
- Pointing to master branch caused issues and also noticed they are pushing releases to crates.io now so this is better
Closes 
> Update proofs-api to 4.0.1

- .github/workflows/ci-rust.yml
- It broke yesterday using latest. Can't test to verify since Github is down, but I will open this PR when it does (but I'm sure it will because the same command works on other workflows with that ubuntu version)
link to CI run on fork: https://github.com/austinabell/forest/runs/874169881?check_suite_focus=true
Closes 
> Update docs publish ubuntu version

- blockchain/chain_sync/src/network_handler.rs
- Sends event from the network handler to the chain syncer
Closes 
> Fix Regression in Syncing

- vm/actor/src/builtin/init/mod.rs
- vm/actor/src/builtin/init/state.rs
- vm/actor/src/builtin/init/types.rs
- vm/actor/src/lib.rs
- vm/src/error.rs
- Small tweaks for this one
Closes #557 
> Update init actor

- vm/address/Cargo.toml
- vm/address/src/lib.rs
- vm/address/tests/address_test.rs
- Network string decoding wasn't being handled correctly for ID addresses
oops, missed that conditional adding network to address a while back
Closes #610 
> Fix string decode handling network

- Cargo.lock
- utils/bigint/src/bigint_ser.rs
- vm/actor/src/builtin/verifreg/mod.rs
- vm/actor/src/builtin/verifreg/state.rs
- vm/actor/src/builtin/verifreg/types.rs
- Picked the commit that seems to be what will be used for next devnet reset
Closes #565 
> Update verified registry actor

- Cargo.lock
- vm/actor/src/builtin/power/mod.rs
- vm/actor/tests/common/mod.rs
- vm/interpreter/Cargo.toml
- vm/interpreter/src/default_runtime.rs
- vm/interpreter/src/gas_block_store.rs
- vm/interpreter/src/gas_syscalls.rs
- vm/interpreter/src/gas_tracker/gas_charge.rs
- vm/interpreter/src/gas_tracker/mod.rs
- vm/interpreter/src/gas_tracker/price_list.rs
- vm/interpreter/src/lib.rs
- vm/interpreter/src/vm.rs
- vm/interpreter/tests/transfer_test.rs
- vm/runtime/src/lib.rs
- When I had made a pass through the VM before the gas charges were not finalized. Now they are and with the test vector runner I compared almost everything is matching except for some code path differences (and common things like puppet and chaos actor not being registered yet)
Closes 
> Update gas charges in VM

- Cargo.lock
- blockchain/message_pool/Cargo.toml
- crypto/Cargo.toml
- encoding/Cargo.toml
- ipld/cid/Cargo.toml
- utils/bigint/Cargo.toml
- utils/json_utils/Cargo.toml
- vm/Cargo.toml
- vm/address/Cargo.toml
- vm/message/Cargo.toml
- Centered around updating message crate with new protocol changes (mainly around dyn gas) cc: @jleni
Closes 
> Released updated protocol crates

- tests/conformance_tests/tests/conformance_runner.rs
- vm/interpreter/src/vm.rs
- 33/66 tests passing now
Closes 
> Fix bugs in vm and update runner

- vm/state_tree/src/lib.rs
- we never return None and convert it to Err. 
I hear this is relevant to you @dutterbutter 
Closes 
> Fix Get Actor

- vm/actor/src/util/chaos/mod.rs
> add validation in chaos actor

- vm/interpreter/src/default_runtime.rs
- tied for worlds smallest PR
Closes 
> check value correctly before transfer

- vm/interpreter/src/default_runtime.rs
- vm/interpreter/src/vm.rs
- We need to return an error in ApplyRet, not on the Result
Closes 
> Handle failed retrieve of actor state

- vm/actor/src/builtin/multisig/types.rs
> fix serialization of TxnIdParams

- Cargo.lock
- crypto/src/vrf.rs
- forest/src/daemon.rs
- ipld/car/src/util.rs
- ipld/cid/src/lib.rs
- node/forest_libp2p/src/behaviour.rs
- types/src/sector/post.rs
- vm/actor/Cargo.toml
- vm/actor/src/builtin/market/deal.rs
- vm/actor/src/builtin/reward/mod.rs
- vm/actor/src/util/balance_table.rs
- vm/address/src/lib.rs
- vm/interpreter/src/default_runtime.rs
- vm/interpreter/src/gas_syscalls.rs
- Didn't go in depth or try to solve all, just fixed while scoping
Closes 
> Remove TODOs from scoping

- node/forest_libp2p/src/behaviour.rs
- node/forest_libp2p/src/service.rs
- Blocksync and hello messages seem to timeout for unknown reasons, but probably due to the format changes. Will look into that in another PR
Closes #684 
> Swap secio authentication for noise

- .github/workflows/ci-rust.yml
- Github actions is so finnicky, I had to remove this before when it broke, but now our docs publish is borked
Closes 
> Fix docs publish workflow

- Makefile
- tests/conformance_tests/tests/conformance_runner.rs
- There was a request for this to show in CI logs so it's easily viewable. I also think this could be useful for tracking
Closes 
> Print out conformance results and add log for skips

- ipld/amt/src/amt.rs
- ipld/amt/src/error.rs
- ipld/amt/src/lib.rs
- ipld/amt/src/node.rs
- ipld/amt/src/root.rs
- ipld/amt/tests/amt_tests.rs
- Change on go-amt: https://github.com/filecoin-project/go-amt-ipld/commit/618e9ea047aefa9f6a4c3904453068ac4fd4a233#diff-28bf0c74b1a5062f61e609b225ee52fe
I didn't notice this came in until now.
Closes 
> Update AMT max index bound

- Cargo.lock
- forest/Cargo.toml
- forest/src/daemon.rs
- forest/src/paramfetch/mod.rs
- forest/src/paramfetch/parameters.json
- update params version (oops was still v27, needed to be v28)
- Avoids bug with `HEAD` requests in surf
- I've indicated to maintainers and they are looking into, can link to issue when available
- Fetches verification keys on daemon start
Closes #717 
> Update params and fetch on daemon start

- vm/actor/src/builtin/power/policy.rs
> MAX_MINER_PROVE_COMMITS_PER_EPOCH 3 to 200

- vm/interpreter/src/vm.rs
- 496/592 tests passed ez money
Closes 
> Skip send in transfer_to_actor if value is 0

- tests/conformance_tests/tests/conformance_runner.rs
- vm/actor/src/builtin/miner/mod.rs
- vm/actor/src/builtin/miner/state.rs
- Gas diff because of the extra blockstore read
558/592
Closes 
> Remove extra state load from withdraw balance

- node/rpc/src/lib.rs
- node/rpc/src/state_api.rs
- vm/address/src/lib.rs
> Minor fixes found during devnet testing

- tests/conformance_tests/tests/conformance_runner.rs
- vm/actor/src/builtin/power/policy.rs
> Minimum Power Fix

- tests/conformance_tests/tests/conformance_runner.rs
- vm/actor/src/util/chaos/mod.rs
> Fix chaos actor send

- vm/interpreter/src/vm.rs
- Changed when debugging a diff: https://github.com/filecoin-project/lotus/pull/4350 it's optional but since it removes extra reads I figured I'd PR in
This shouldn't change anything related to consensus, just may make debugging easier later
Closes 
> Update sequence based on epoch for internal messages

- Cargo.lock
- Cargo.toml
- blockchain/chain_sync/src/sync_worker.rs
- tests/conformance_tests/Cargo.toml
- tests/conformance_tests/tests/conformance_runner.rs
- utils/statediff/Cargo.toml
- utils/statediff/src/lib.rs
- I needed it outside to test state diff of running chain, will be useful in future for this to be available to pull in from anywhere
Closes 
> Refactor statediff to own crate

- blockchain/blocks/src/block.rs
- node/forest_libp2p/src/blocksync/provider.rs
- Provider was using wrong vector for indexing
- Block message limit has changed
Syncing to block 51 now
Closes 
> Fix provider and block message limit

- Cargo.lock
- vm/actor/src/builtin/miner/bitfield_queue.rs
- vm/actor/src/builtin/miner/monies.rs
- vm/actor/src/builtin/miner/state.rs
- Honestly this was just a mistype during the network version update, my bad
With other PRs, up to 260
Closes 
> Fix projection period for faults

- blockchain/state_manager/src/lib.rs
- forest/src/logger/mod.rs
- vm/interpreter/src/vm.rs
- I was using their previous value they had and didn't think that more gas would be used because I didn't realize the amount of gas used during cron
sync to: 971
Closes 
> Increase cron gas limit

- vm/actor/src/builtin/miner/state.rs
- Fixes state diff at epoch 1441
Closes 
> Fix reschedule sector expirations

- vm/message/src/message_receipt.rs
- vm/message/src/unsigned_message.rs
- Noticed when working on unrelated things, this currently will serialize the bytes as an array of integers
Closes 
> Fix message receipt json

- .circleci/config.yml
- Coverage wasn't run on main, my linter pointed out some other issues with the config so I fixed those as well
cc @dutterbutter 
Closes 
> Fix circleCI coverage

- ipld/cid/src/json.rs
- vm/address/src/lib.rs
- vm/message/Cargo.toml
- vm/message/src/signed_message.rs
- vm/message/src/unsigned_message.rs
- vm/message/tests/message_json_test.rs
- Ours was missing the `CID` field
Closes 
> Update message json format to match Lotus

- ipld/hamt/fuzz/.gitignore
- ipld/hamt/fuzz/Cargo.toml
- ipld/hamt/fuzz/fuzz_targets/hamt_fuzz.rs
- Equivalent of #871 but for Hamt
Closes 
> Implement hamt fuzzer

- Cargo.lock
- vm/message/Cargo.toml
- Json feature wasn't enabled on our bigint crate when message json feature enabled
Closes 
> Fix message crate compilation with json feature

- vm/actor/src/builtin/account/mod.rs
- vm/actor/src/builtin/cron/mod.rs
- vm/actor/src/builtin/init/mod.rs
- vm/actor/src/builtin/multisig/mod.rs
- vm/actor/src/builtin/multisig/state.rs
- vm/actor/src/builtin/multisig/types.rs
- vm/actor/src/builtin/system/mod.rs
- multisig v2 (self-explanatory)
Closes #820 
> Update multisig to v2

- vm/actor/src/builtin/market/mod.rs
- vm/actor/src/builtin/market/policy.rs
- vm/actor/src/builtin/market/types.rs
> Update market actor to v2

- vm/actor/src/builtin/miner/mod.rs
- vm/actor/src/builtin/miner/policy.rs
- vm/actor/src/builtin/mod.rs
- vm/actor/src/builtin/power/mod.rs
- vm/actor/src/builtin/power/policy.rs
- vm/actor/src/builtin/power/state.rs
- vm/actor/src/builtin/power/types.rs
- vm/actor/src/builtin/sector.rs
> power actor v2 upgrade

- vm/actor/src/builtin/paych/mod.rs
- vm/actor/src/builtin/paych/types.rs
- vm/actor/tests/paych_actor_test.rs
- Paych actor update
Closes #821 
> paych v2 actor update

- vm/actor/src/builtin/market/mod.rs
- vm/actor/src/builtin/verifreg/mod.rs
- Basically all changes was just resolving addresses to ID
Closes #825 
> Update verifreg actor to v2

- blockchain/state_manager/src/lib.rs
* Added method `get_market_state` to State Manager
Closes #828 
> Add GetMarketState to State Manager

- vm/actor/src/builtin/miner/mod.rs
- vm/actor/src/builtin/miner/types.rs
- vm/actor/src/builtin/reward/logic.rs
- vm/actor/src/builtin/reward/mod.rs
- vm/actor/src/builtin/reward/state.rs
- vm/actor/src/builtin/reward/types.rs
- vm/actor/tests/reward_actor_test.rs
- Updates reward actor 
Closes #823 
> Update reward actor to v2

- Cargo.lock
- tests/conformance_tests/tests/conformance_runner.rs
- types/Cargo.toml
- types/src/version.rs
- vm/actor/src/builtin/market/mod.rs
- vm/actor/src/builtin/market/types.rs
- vm/actor/src/builtin/miner/deadline_assignment.rs
- vm/actor/src/builtin/miner/deadline_state.rs
- vm/actor/src/builtin/miner/deadlines.rs
- vm/actor/src/builtin/miner/expiration_queue.rs
- vm/actor/src/builtin/miner/mod.rs
- vm/actor/src/builtin/miner/monies.rs
- vm/actor/src/builtin/miner/partition_state.rs
- vm/actor/src/builtin/miner/policy.rs
- vm/actor/src/builtin/miner/sectors.rs
- vm/actor/src/builtin/miner/state.rs
- vm/actor/src/builtin/miner/types.rs
- vm/actor/src/builtin/miner/vesting_state.rs
- vm/actor/src/builtin/reward/mod.rs
- vm/actor/src/lib.rs
- vm/actor/tests/reward_actor_test.rs
- vm/actor_interface/src/builtin/miner/mod.rs
- vm/actor_interface/src/lib.rs
> Update miner actor to v2

- blockchain/chain/src/store/base_fee.rs
- Finishes last part of #908, all other parts of this was done previously
Closes #908
> Update smoke base fee calculation

- crypto/src/signature.rs
- ipld/amt/src/bitmap.rs
- utils/bigint/src/bigint_ser.rs
- utils/bigint/src/biguint_ser.rs
- utils/bitfield/src/rleplus/mod.rs
- vm/address/src/lib.rs
- In cases where the reader cannot reference bytes and needs to clone, this will support that.
@ec2
Closes 
> Switch temp bytes deserialize to Cow

- vm/interpreter/src/gas_tracker/gas_charge.rs
- vm/interpreter/src/gas_tracker/price_list.rs
- Updates storage gas multiplier. I didn't notice this changed when updating the price list.
- Balances are all correct for the tipset I'm checking against for the most recent network version
Closes 
> Update calico storage gas multiplier

- blockchain/state_manager/src/vm_circ_supply.rs
- Fix calico vesting (didn't update the fil vested function after the refactor was done, oops)
Closes 
> Fix calico vesting

- node/rpc/src/chain_api.rs
- node/rpc/src/gas_api.rs
- node/rpc/src/wallet_api.rs
- Title is pretty self explanatory. 
Closes 
> Nullable Entropy in Randomness RPC and Fix Gas Base Fee Estimation

- vm/actor/src/builtin/multisig/mod.rs
- Proposal hash in params should be considered optional
- Yes this is a bit of a weird flow, but this needs to be exactly this (because of the hashing gas cost, I might open an issue for this)
Closes 
> Handle null multisig proposal hashes

- Cargo.lock
- blockchain/beacon/Cargo.toml
- blockchain/beacon/src/drand.rs
- blockchain/state_manager/Cargo.toml
- crypto/Cargo.toml
- crypto/src/signature.rs
- key_management/Cargo.toml
- node/rpc/Cargo.toml
- tests/serialization_tests/Cargo.toml
- types/Cargo.toml
- vm/runtime/Cargo.toml
- something something 35x faster
- Downgrades certain versions to compatible (newer disallows zero key/addr)
In draft until it gets released (don't want two versions of blst)
Closes 
> Update bls backend to blst

- Cargo.lock
- blockchain/state_manager/Cargo.toml
- blockchain/state_manager/src/lib.rs
- utils/statediff/Cargo.toml
- utils/statediff/src/lib.rs
- vm/state_tree/src/lib.rs
- needs to handle new state tree versions
- Puts logic under feature so can be easily re-enabled when needed to test
Closes 
> Update statediff for v2 and keep under feature

- blockchain/blocks/src/header/mod.rs
- blockchain/chain_sync/src/sync_worker.rs
- This function was only called within `verify_consensus_fault` so was not caught before, but definitely something I should have noticed when I fixed the other interactions
- Switched other references to use this helper function to make cleaner and have more consistency
Closes 
> Fix block header signature verification helper function

- Cargo.lock
- ipld/hamt/CHANGELOG.md
- ipld/hamt/Cargo.toml
- ipld/hamt/src/node.rs
- ipld/hamt/src/pointer.rs
- ipld/hamt/tests/hamt_tests.rs
- utils/statediff/Cargo.toml
- vm/actor/Cargo.toml
- vm/interpreter/Cargo.toml
- vm/state_tree/Cargo.toml
- Adds changelog
- removes v2 feature, no need for it
- point current references to released version to allow for v3 amt to come in
Closes 
> Prep hamt v2 release

- Cargo.lock
- We really should try to purge this dependency out at some point, but because it's included in `rust-fil-proofs` it's a bit unavoidable right now.
Closes 
> fix hyper vulnerability

- ipld/car/src/util.rs
- Noticed when looking around, there is no need to convert the cid to bytes just to get the amount of bytes read.
Closes 
> Improve Car file read node

- types/networks/Cargo.toml
- types/networks/src/interopnet/mod.rs
- types/networks/src/lib.rs
- types/networks/src/mainnet/mod.rs
- types/src/version.rs
- vm/interpreter/src/vm.rs
- Getting ready to do state migrations.
- Function signatures are not stable yet, and are subject to change.
Closes 
> Framework for State Migrations

- .circleci/config.yml
- README.md
> Add 1.46.0 msrv check to CI

- blockchain/state_manager/src/vm_circ_supply.rs
- vm/interpreter/src/vm.rs
- New version of clippy triggered this, ironically was added a few days ago. Also fixed the logic, didn't notice it was flipped in review (oops)
Closes 
> Fix new clippy warnings and fix logic

- vm/actor/src/builtin/verifreg/mod.rs
- vm/actor/src/builtin/verifreg/state.rs
- vm/actor/src/lib.rs
- Its in the title :D 
- Not much has changed except for one exitcode case and enforcing hamt bitwidth. 
Closes 
> Verifreg Actor v3

- .github/CODEOWNERS
> Remove old codeowners

- Cargo.lock
- Update to patched versions of generic-array and rand-core
Closes 
> Cargo Audit Patch

- vm/interpreter/src/default_runtime.rs
- Fixes fork at epoch 577415
Closes 
> Fix Parent Grinding Fault Detection

- forest/src/logger/mod.rs
- node/forest_libp2p/src/behaviour.rs
- Sets Gossipsub Logs to error
- Updates some log levels from the Behaviour
Closes 
> Update Networking Log Levels

- .github/CODEOWNERS
> Add @olibero to Code Owners

- vm/actor/src/builtin/miner/mod.rs
- Receipt mismatch in this transaction https://filfox.info/en/message/bafy2bzacecuex6dir7enoa3cdlbltdankadtzqtmzwfm7dqm44so6iz2oe3io
Closes 
> Fix ExitCode handling when calling repay_partial_debt_in_priority_order

- vm/actor/src/builtin/miner/deadline_state.rs
> Fix Error Handling in Deadline Construction

- ipld/blockstore/src/buffered.rs
Were just changes I noticed when scanning code for what I was working on, figured I'd PR
What changed:
- Switched trait to `Read` since there was no need for the `AsyncRead` specific functions
- Removed `BufferedReader` wrapper for the bytes
- There is no need to have the overhead of the buffered reader when the bytes are already in memory, it should be redundant, unless I'm missing something here?
- Switched the scanning for links to attach a callback instead of allocating a vector of Cids, just to iterate and copy them
- There are iterator based alternatives to this with the same function, but this was the least invasive change
Closes 
> Tweaks to buffered blockstore

- Cargo.lock
- vm/actor/src/builtin/miner/state.rs
- Fixes error caused by this message https://filfox.info/en/message/bafy2bzaceclpal4jjrehsaiwotfpeu5c63yc6lkhterg742qcboptcclbuy3m
Closes 
> Fix Error Handling in Load Deadlines

- blockchain/message_pool/src/msgpool/test_provider.rs
- ipld/graphsync/src/libp2p/codec.rs
By folding them in the Error case of their encompassing Result
Tool-aided by [comby-rust](https://github.com/huitseeker/compby-rust)
> Remove a couple unnecessary panics

- .github/CODEOWNERS
> Add @connormullett to Code Owners

- .circleci/config.yml
Disable MacOS CI for now. Looked into it a bit, not sure what other better solutions we have. I'm open to better solutions.
- 
Closes 
> Disable MacOS CI

- key_management/src/keystore.rs
- node/rpc/src/enc_api.rs
- node/rpc/src/lib.rs
> Encrypted Key Store (RPC API & CLI)

- Cargo.lock
- types/Cargo.toml
- vm/actor/Cargo.toml
- vm/actor_interface/Cargo.toml
- release fil_types 0.2.1 crate
- release actors crate 3.0.0 (v4 actors) 
- bump local version of actors to 4.0.0 (v5 actors)
Closes 
> v5 Actors Prep

- vm/actor/src/builtin/market/mod.rs
- vm/actor/src/builtin/miner/expiration_queue.rs
- vm/actor/src/builtin/miner/mod.rs
- vm/interpreter/src/vm.rs
- No logical changes just some minor typos in comments and error messages
n/a 
> Spelling and typos

- Cargo.lock
- node/forest_libp2p/Cargo.toml
- node/forest_libp2p/src/rpc/mod.rs
- This fixed our nightly builds breaking
Closes 
> Swap to asyncronous_codec and bump futures_cbor_codec

- vm/actor/src/builtin/power/policy.rs
> [Audit fixes] FOR-10: Inconsistent CONSENSUS_MINER_MIN_MINERS Constant Value to Lotus

- forest/src/daemon.rs
Signed-off-by: detailyang <detailyang@gmail.com>
Fix the problem of inconsistent passwords when confirm the password:)
Closes 
> hotfix:fix passphrase fake confirm

- vm/interpreter/src/vm.rs
- Related issues #1176 
- Fixes the VM apply_blocks when contains null rounds
Closes 
> bugfix:vm:run cron for null rounds

- forest/src/cli/mod.rs
- improves UX by adding the check for config file via Env Var
Closes #1191 
> added the check for config file via Env Var

- vm/actor/src/builtin/market/mod.rs
- vm/actor/src/builtin/market/state.rs
- Adds missing docs to market actor and market state from https://github.com/filecoin-project/specs-actors/pull/1417
- Swapped order of proposal and state deletion to maintain consistency (probably doesn't matter, but it makes it easier to follow)
Closes N/A
> Add some missing docs to the rest of v5 updates

- vm/actor/src/builtin/market/mod.rs
- vm/actor/tests/common/mod.rs
- vm/interpreter/src/default_runtime.rs
- vm/runtime/src/lib.rs
- unit tests fixed
- update conformance-tests/test-vectors to v6
n/a
> actors v6: fix unit tests, integrate test vectors

- .github/workflows/msrv.yml
> ci: attempt to improve gh actions time

- vm/actor/src/builtin/market/mod.rs
- Remove redundant code
Could cause a chain split.
Closes 
#1268
> Elmattic/actors review F4

- vm/actor/src/builtin/market/mod.rs
- Fix error code
`SysXXX` error codes can't be directly returned by a spec actor. See [here](https://github.com/filecoin-project/go-state-types/blob/master/exitcode/reserved.go#L4).
Closes #1270
> Elmattic/actors review F6

- vm/actor/src/builtin/power/mod.rs
- Add missing decrement
Closes #1272
Note we don't expose [this method](https://github.com/filecoin-project/lotus/blob/1d2f84322d4fc1c0d5357476aa693c309097a8c8/chain/actors/builtin/power/v6.go#L92-L94) in our power actor, so miner count was never used.
> Elmattic/actors review F8

- vm/actor/src/builtin/market/state.rs
- Fix incorrect error codes
Closes #1271 
> Elmattic/actors review F7

- vm/actor/src/builtin/market/mod.rs
- fixes market actor bug
- see https://github.com/filecoin-project/specs-actors/pull/1487/files#diff-f2f7ea54737b6cc23d8ca128a88ea69344f4cbf8ea522b5843602d8e7297df48R307
Closes n/a
> v6: fix market actor bug

- vm/actor/src/builtin/market/mod.rs
- fix market logic to match go code https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/market/market_actor.go#L279
n/a
> fix market logic

- blockchain/chain_sync/src/network_context.rs
- blockchain/chain_sync/src/tipset_syncer.rs
- forest/src/cli/auth_cmd.rs
- forest/src/cli/genesis_cmd.rs
- forest/src/cli/net_cmd.rs
- forest/src/cli/state_cmd.rs
- forest/src/cli/sync_cmd.rs
- key_management/src/wallet.rs
- node/rpc/src/wallet_api.rs
- vm/address/src/lib.rs
- vm/state_migration/src/lib.rs
- vm/state_tree/src/lib.rs
- Apply clippy lints from rust-1.58
Closes #1377 
> Apply clippy lints from rust-1.58

- .github/workflows/docs.yml
- Generate documentation in dry-run mode to verify that the CI steps work.
> ci: documentation dry-run for PRs.

- Makefile
- Conformance tests were disabled by mistake. This PR re-enables them.
> Fix command line for running conformance tests.

- Cargo.lock
- forest/Cargo.toml
- ipld/blockstore/Cargo.toml
- node/db/Cargo.toml
> chore: bump rocksdb to 0.17

- .github/CODEOWNERS
- Added myself to the codeowners
> add LesnyRumcajs to CODEOWNERS

- .github/workflows/release.yml
> ci: fix documentation in release workflow

- CHANGELOG.md
- Cargo.lock
- forest/Cargo.toml
> forest: bump version to 0.2.2

- crypto/src/signature.rs
- Fixed clippy warnings introduced in #1437 (additional test lints were merged to `main` in the meantime).
> fix clippy fiascoes introduced in #1437

- blockchain/chain_sync/src/network_context.rs
- crypto/src/signature.rs
> blockchain/sync: demote chain exchange warning to debug message

- blockchain/chain/src/store/chain_store.rs
- forest/src/cli/wallet_cmd.rs
- ipld/amt/src/node.rs
- key_management/src/wallet.rs
- node/rpc-api/build.rs
- node/rpc/src/wallet_api.rs
- fixed new clippy warnings that were failing the `main` branch. Thanks to @q9f for spotting this.
> fixed new clippy warnings

- .maintain/monitoring/README.md
- .maintain/monitoring/docker-compose.yml
- remove needless volume mount and steps,
- cleanup compose-file,
- update readme to reflect simplified set-up steps
> improve docker-compose for monitoring stack

- codecov.yml
- PRs aren't blocked anymore if they contain code not covered by tests.
> CI: Allow codecov policies to fail.

- .github/workflows/rust.yml
- .tarpaulin.toml
- tests/conformance_tests/Cargo.toml
- Conformance tests weren't being included in the code coverage because the submodule containing all the test-vectors was not checked out. This PR pulls in the submodule before doing code coverage.
> CI: Include conformance tests in code coverage results

- blockchain/chain_sync/src/chain_muxer.rs
- blockchain/chain_sync/src/metrics.rs
- blockchain/chain_sync/src/tipset_syncer.rs
- added more metrics to assert health of the running node
> add more metrics of syncing

- scripts/nightly_check/README.md
- scripts/nightly_check/download_latest_snapshot.sh
- scripts/nightly_check/health_check.sh
- scripts/nightly_check/nightly_check.sh
- scripts/nightly_check/nightly_check_prepare.sh
- nightly checks scripts to be installed on a nightly runner with instructions
Closes #1455
For the moment latest snapshots are not downloaded nor used as Forest won't work with v15. I put a snapshot from February on the server. After we introduce support for v15 we can re-iterate on that. https://github.com/ChainSafe/forest/issues/1476
> Night job scripts

- .github/CODEOWNERS
```diff
-*       @ec2 @noot @connormullett @elmattic @Lemmih @LesnyRumcajs
+*       @connormullett @elmattic @lemmih @LesnyRumcajs @jdjaustin
```
> github: update code owners

- .github/ISSUE_TEMPLATE/bug_report.md
- Fixed the label for bug templates (the former doesn't exist so it was not applied)
> fixed bug label for bug template

- .github/workflows/release.yml
> ci: add wasm target to release script

- Cargo.lock
fix https://rustsec.org/advisories/RUSTSEC-2022-0016
> crates: bump wasmtime

- .github/workflows/rust.yml
- .tarpaulin.toml
> PR 1534 LLVM code coverage

- blockchain/state_manager/src/lib.rs
- node/rpc/src/state_api.rs
- vm/interpreter/src/vm.rs
- Remove ApplyRet from forest in favor of the FVM's implementation
Closes 
#1551 
> use FVM ApplyRet and remove Forest's

- .github/workflows/release.yml
- switch on nightly on release workflow
> switch to nightly on release workflow

- ipld/blockstore/src/resolve.rs
- Fix missing recursive call
The algorithm was only replacing the first level of hash links, but not the more deeply nested ones.
> Fix the resolve_ipld algorithm

- forest/src/daemon.rs
- vm/address/src/lib.rs
> Delete the unused NETWORK_DEFAULT 

- .github/workflows/docs.yml
- blockchain/beacon/src/drand.rs
- blockchain/message_pool/src/msgpool/selection.rs
- encoding/src/lib.rs
- ipld/legacy_amt/src/lib.rs
- node/forest_libp2p/src/hello/message.rs
- utils/hash_utils/src/lib.rs
- utils/paramfetch/src/lib.rs
- Fail if there are any warnings during `cargo doc`
- Update URLs to be hyperlinks in the API documentation
Closes 
> Check API documentation in CI

- blockchain/blocks/src/tipset.rs
> Ensure blocks are created by a distinct set of miners. 

- .config/forest.dic
- encoding/src/checked_serde_bytes.rs
- encoding/src/hash.rs
> Enable cargo-spellcheck for encoding

- .config/forest.dic
- .config/spellcheck.toml
- blockchain/chain/src/store/chain_store.rs
- blockchain/state_manager/src/chain_rand.rs
- blockchain/state_manager/src/errors.rs
- blockchain/state_manager/src/lib.rs
- blockchain/state_manager/src/utils.rs
> Enable cargo-spellcheck for blockchain/state_manager 

- blockchain/chain_sync/src/chain_muxer.rs
- Restore previously-broken test.
Closes #1477 
> ChainMuxer test is no longer broken

- forest/Cargo.toml
- forest/src/daemon.rs
- ipld/blockstore/Cargo.toml
- node/db/Cargo.toml
- node/db/src/errors.rs
- node/db/src/lib.rs
- node/db/tests/db_utils/mod.rs
- node/db/tests/rocks_test.rs
- utils/statediff/Cargo.toml
- removed rocksdb feature flag as it's not optional anymore since we removed `sled` db support
> remove rocksdb feature (not optional anymore)

- .github/workflows/docs.yml
- Enable caching when verifying docs.
Closes 
> Enable caching when building docs during ci

- .config/forest.dic
- blockchain/message_pool/src/block_prob.rs
- blockchain/message_pool/src/config.rs
- blockchain/message_pool/src/errors.rs
- blockchain/message_pool/src/msg_chain.rs
- blockchain/message_pool/src/msgpool/mod.rs
- blockchain/message_pool/src/msgpool/msg_pool.rs
- blockchain/message_pool/src/msgpool/provider.rs
- blockchain/message_pool/src/msgpool/selection.rs
- blockchain/message_pool/src/msgpool/test_provider.rs
- blockchain/message_pool/src/msgpool/utils.rs
> Enable cargo-spellcheck for blockchain/message_pool 

- .config/forest.dic
- blockchain/beacon/src/beacon_entries.rs
- blockchain/beacon/src/drand.rs
> Enable cargo-spellcheck for blockchain/beacon 

- ipld/SERIALIZER.md
- ipld/src/json.rs
- 
Documentation explaining the differences of serializers added.
Closes #1700
> Serializer differences doc

- blockchain/blocks/src/lib.rs
- blockchain/chain_sync/src/lib.rs
- vm/message/src/lib.rs
- vm/src/lib.rs
> Untangle workaround for old compiler bug

- .github/workflows/rust.yml
- need to temporarily ignore RUSTSEC-2022-0040 until https://github.com/libp2p/rust-libp2p/issues/2794 is resolved to unblock the CI.
- same audit error occurs in `libp2p 0.46.1` so https://github.com/ChainSafe/forest/pull/1717 won't help.
```
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 430 security advisories (from /home/rumcajs-work/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (752 crate dependencies)
Crate:     owning_ref
Version:   0.4.1
Title:     Multiple soundness issues in `owning_ref`
Date:      2022-01-26
ID:        RUSTSEC-2022-0040
URL: …
```
> temporarily ignore RUSTSEC-2022-0040

- blockchain/message_pool/src/msgpool/msg_pool.rs
- Move duration to be seconds
Most of the time if not all in filecoin, durations are expressed in seconds. I'm not sure there is a need for moving to `Duration` everywhere.
Closes #1499
> Fix republish message interval

- scripts/sync_check/sync_check.toml
- Fix config regression introduced in https://github.com/ChainSafe/forest/pull/1743
> fix sync check config regression

- Cargo.lock
- lockfile wants to be updated, lets update it and not bloat other PRs with it
> bump lockfile

- forest/src/daemon.rs
- vm/actor_interface/Cargo.toml
- found some stray features during reviews, as far as I remember we functionally deleted those
> remove stray features

- vm/interpreter/src/fvm/kernel.rs
- vm/interpreter/src/gas_block_store.rs
- vm/interpreter/src/vm.rs
- Enable cargo-spellcheck for vm/interpreter/
Closes issue #1749 
> Implement spellcheck for vm/interpreter

- .config/forest.dic
- Cargo.lock
- forest/src/cli/chain_cmd.rs
- forest/src/cli/client.rs
- forest/src/cli/config.rs
- forest/src/cli/fetch_params_cmd.rs
- forest/src/cli/mod.rs
- forest/src/cli/net_cmd.rs
- forest/src/subcommand.rs
- Clear spellcheck errors in `forest/`
Closes #1745 
> Enable spellcheck in `forest/`

- blockchain/chain_sync/src/peer_manager.rs
- blockchain/message_pool/src/block_prob.rs
- forest/src/cli/sync_cmd.rs
- ipld/src/selector/walk.rs
- node/forest_libp2p/src/gossip_params.rs
- node/forest_libp2p/src/rpc/cbor_codec.rs
- node/rpc/src/common_api.rs
- utils/json/src/address.rs
> Review allow attributes.

- node/db/Cargo.toml
- Bump rocksdb version to 0.19
Closes #1814
> Bump rocksdb version to 0.19

- .github/workflows/rust.yml
- encoding/src/lib.rs
- Only a few folders are checked at the moment. Eventually we'll just run `cargo-spellcheck` at the root level.
Closes #1803
> Run `cargo-spellcheck` during CI

- node/rpc/src/beacon_api.rs
- node/rpc/src/gas_api.rs
- node/rpc/src/mpool_api.rs
- node/rpc/src/state_api.rs
- node/rpc/src/sync_api.rs
- node/rpc/src/wallet_api.rs
> Enable cargo-spellcheck for node/rpc 

- forest/src/cli/fetch_params_cmd.rs
- forest/src/cli/mod.rs
- forest/src/cli/state_cmd.rs
> Avoid using panic for user-facing errors. 

- .config/forest.dic
- node/rpc-api/src/lib.rs
> Enable cargo-spellcheck for node/rpc-api 

- documentation/developer_documentation/mainnet_compatibility.md
- Provide developer documentation on how to determine if forest is on mainnet
- Provide developer documentation on how to perform some complicated debugging steps like state mismatches and diffs
Closes #1262
> Document mainnet compatibility and workflows

- blockchain/beacon/tests/drand.rs
> Investigate why drand tests are ignored

- .config/forest.dic
- .github/workflows/rust.yml
- types/src/deadlines/mod.rs
- types/src/genesis/mod.rs
- types/src/sector/post.rs
- types/src/verifier/mock.rs
- Spellcheck `types/`
Closes #1747 
> Implement cargo spellcheck for types

- .github/workflows/rust.yml
- vm/interpreter/src/gas_block_store.rs
- Regression occurred that required these spellcheck changes to be re-implemented.
Closes #1749 
> Implement spellcheck for vm/interpreter v2

- forest/src/daemon.rs
- Change the ordering of tasks in daemon.rs to start the RPC server prior to loading the snapshot
Closes #1800 
> Start RPC server before loading snapshot

- documentation/developer_documentation/state_migration.md
- Add a new document in the developer documentation
Closes #1754
> Add a migration markdown document

- vm/actor_interface/src/lib.rs
- vm/actor_interface/src/policy.rs
- removed an empty policy file I randomly found
> remove empty policy file

- Cargo.lock
- utils/auth/Cargo.toml
- utils/auth/src/lib.rs
- Bump jsonwebtoken from version 7 to version 8.
Closes #1923 
> Bump version of jsonwebtoken to 8.1

- Cargo.lock
- blockchain/chain/Cargo.toml
- blockchain/chain/src/lib.rs
- blockchain/chain/src/store/chain_store.rs
- blockchain/chain/src/store/index.rs
- blockchain/chain_sync/Cargo.toml
- blockchain/chain_sync/src/bad_block_cache.rs
- blockchain/message_pool/Cargo.toml
- blockchain/message_pool/src/lib.rs
- blockchain/message_pool/src/msgpool/msg_pool.rs
> Update lru dependency 

- .github/workflows/rust.yml
- Makefile
- README.md
- Improved docs and ergonomics of linters for Rust (didn't touch scripts linters as we will be moving them into a different repo).
> Linters better doc

- scripts/daily_snapshot/daily_snapshot.rb
- I previously removed the top-level logger from the daily_snapshot.rb script but forgot to remove everything.
Closes 
> Remove invaild logging attempt.

- blockchain/blocks/src/header/mod.rs
- blockchain/chain/src/store/chain_store.rs
- blockchain/chain_sync/src/tipset_syncer.rs
- blockchain/message_pool/src/msgpool/mod.rs
- blockchain/message_pool/src/msgpool/selection.rs
- blockchain/state_manager/src/chain_rand.rs
- blockchain/state_manager/src/lib.rs
- forest/src/daemon.rs
- node/forest_libp2p/src/behaviour.rs
- node/forest_libp2p/src/chain_exchange/provider.rs
- node/forest_libp2p/src/discovery.rs
- node/forest_libp2p/src/service.rs
- node/rpc/src/sync_api.rs
- utils/genesis/src/lib.rs
- utils/net_utils/src/download.rs
- Calling async code from a sync context is a bad practice and can cause a variety of issues.
- Most cases were easy to fix but some can't be updated before we switch entirely to tokio.
Closes #1910 
> Remove nearly all instances of `block_on`

- blockchain/chain_sync/src/chain_muxer.rs
- blockchain/chain_sync/src/validation.rs
- blockchain/consensus/deleg_cns/src/consensus.rs
- blockchain/consensus/deleg_cns/src/validation.rs
> Remove the clippy::result_large_err clippy exceptions 

- .github/workflows/pr_stats.yml
- Add Slack notification with code review stats. It will run every hour just to check if it is OK for us. Afterwards, a quick PR will change it to 9 AM UTC Monday only.
> slack review stats

- forest/src/daemon.rs
- let's tell our users we are aware of our flaws. 
> add tracking issue to dangling ref fiasco

- forest/src/cli/config.rs
- forest/src/logger/mod.rs
> Hubert's fix

- forest/src/cli/config.rs
- forest/src/logger/mod.rs
> Improve configuration formation for logging options 

- .gitmodules
- Fix typo in .gitmodules. This kept the 'Update Branch' button from working on github.
Closes 
> Fix typo in .gitmodules

- scripts/Dockerfile-snapshot
- scripts/daily_snapshot/daily_snapshot.rb
- scripts/daily_snapshot/run_service.sh
- scripts/daily_snapshot/snapshots_prune.rb
- scripts/ruby_common/slack_client.rb
- Added periodical snapshots prune to snapshot exporter,
- cleaned up the exporter structure a bit.
Closes https://github.com/ChainSafe/forest/issues/1949
> Periodical snapshots prune

- scripts/daily_snapshot/daily_snapshot.rb
- always attach logs after the snapshot upload. This should be useful if there is no apparent error during export, but the exported data is somehow invalid.
> Always include logs for snapshot export

- forest/src/cli/snapshot_fetch.rs
- fix snapshot download issue encountered by @lemmih  when not the entire buffer was flushed to the file. Added a size check at the end of the snapshot download.
> fix snapshot fetch file download

- .github/CODEOWNERS
- add @hanabi1224 to CODEOWNERS
Closes 
> add hanabi1224 to CODEOWNERS

- .github/workflows/scripts-lint.yml
- scripts/daily_snapshot/boot_service.sh
- Fix scripts lint regression introduced [here](https://github.com/ChainSafe/forest/commit/20d58d5010b7c59165d47bf20260070a7ce66119#diff-cf5c63ae353529df317c65753a10cdf18b4781efe58a65c1ffa5ccfd98e23c59R19) which resulted in a silent-ish [error](https://github.com/ChainSafe/forest/actions/runs/3141993168)
```
[Invalid workflow file: .github/workflows/scripts-lint.yml#L19](https://github.com/ChainSafe/forest/actions/runs/3141993168/workflow)
The workflow is not valid. .github/workflows/scripts-lint.yml (Line: 19, Col: 7): Unexpected value 'args'
```
Closes 
> fix shellcheck action

- vm/message/src/message_receipt.rs
- Use quickcheck to test our custom implementations of `MessageReceipt`
Closes associated task in #1881 
N/A
> Property Test for MessageReceipt

- .github/CODEOWNERS
- Add @creativcoder to CODEOWNERS
Closes 
> Add creativcoder to CODEOWNERS

- utils/paramfetch/src/lib.rs
- improve error handling logic in `paramfetch` to pass better error message to upstream caller(s)
Closes https://github.com/ChainSafe/forest/issues/1975
> fix: improve error handling logic in paramfetch

- .github/workflows/autoupdate.yml
- Workflows required were not triggered because of https://github.com/chinthakagodawita/autoupdate#limitations. This will hopefully fix it.
> use ACTIONS_PAT for auto-updater

- blockchain/chain_sync/src/tipset_syncer.rs
Co-authored-by: Eric Tu <tu.eric@hotmail.com>
- @ec2 fix seems to be working well. No thresholds were exceeded for over four days. The only issue is that we still detect lots of forks, but let's make this part of another investigation.
Closes https://github.com/ChainSafe/forest/issues/1873
> fix fork threshold issue

- .github/workflows/docs.yml
- Adding a linkchecker to mdbook caused the output directory to change. This PR uploads the correct folder.
Closes 
> Upload the correct folder for the user's guide

- .github/workflows/docs.yml
> feat: run the link checker over the README file

- .github/workflows/docs.yml
- .github/workflows/rust.yml
- Cargo.lock
- Makefile
- README.md
- update CI setup to publish rustdoc of the `main` branch to github pages
- update `readme.md` accordingly
Closes https://github.com/ChainSafe/forest/issues/1996
> feat: publish rustdoc of main branch

- Cargo.lock
- utils/json/src/actor_state.rs
- Use quickcheck to test our custom implementations of `ActorState`
Closes associated task in #1881
N/A
> Property Test for ActorState

- .github/dependabot.yml
- `ignore` needs to be an array and cannot be left empty, remove it for now
Closes 
> fix: bad dependabot.yml format

- blockchain/state_manager/src/lib.rs
- vm/interpreter/src/vm.rs
> Remove the LookbackStateGetter trait 

- forest/cli/src/cli/mod.rs
- added a fail-safe for RPC error handling for when `JsonRpcError` has code zero, the process would exit with code zero, indicating a success (even though there was an error).
Closes 
> fix rpc error handling

- .github/workflows/rust.yml
- Makefile
- README.md
- Changes to Makefile to use cargo nextest as test runner
Closes #2040 
> Switch to cargo nextest as test runner

- Cargo.lock
- forest/cli/Cargo.toml
- forest/cli/src/cli/mod.rs
- When applicable (the error code exists as an HTTP status code), give the reason for the http error code for clarity
Closes #1159 
> Http Status codes with reasons when logging errors

- .github/CODEOWNERS
- added @sudo-shashank to CODEOWNERS
Closes 
> add @sudo-shashank to CODEOWNERS

- Cargo.lock
- blockchain/chain/Cargo.toml
- blockchain/chain/src/store/base_fee.rs
- blockchain/message_pool/src/msgpool/msg_pool.rs
- blockchain/message_pool/src/msgpool/utils.rs
- node/rpc/src/gas_api.rs
- remove lazy_static dep from chain crate
Closes https://github.com/ChainSafe/forest/issues/2114
> chore: remove lazy_static dep from chain crate

- Cargo.lock
- Cargo.toml
- remove unused libp2p features
Closes part of https://github.com/ChainSafe/forest/issues/2088
> chore: remove unused libp2p features

- forest/daemon/src/daemon.rs
- Don't ask to download a snapshot if we're already trying to import one.
Closes 
> fix: don't ask to download a snapshot if one is already given

- forest/daemon/src/daemon.rs
- Fix chain validation function
When we changed `FIL_PROOFS_PARAMETER_CACHE` from its default value (`/var/tmp/filecoin-proof-parameters`) to a configuration driven one, we have created a functional regression that stayed unnoticed for a while.
The regression shows up in [validate_chain](https://github.com/ChainSafe/forest/blob/main/blockchain/state_manager/src/lib.rs) function, resulting in an always broken state.
This PR fixes this issue by moving the init of proof parameters *before* `sync_from_snapshot` (that can call `validate_chain` internally), ensuring a proper init.
Closes n/a
> Fix chain validation

- .cargo/config.toml
- Dockerfile
- Makefile
- remove lld from system package deps
Closes https://github.com/ChainSafe/forest/issues/2199
> chore: remove lld from system package deps

- documentation/developer_documentation/TEST_PLAN.md
- Add a bit more detail about long running tests and checks.
Closes 
> chore: describe the long-running tests in more detail

- forest/cli/src/cli/chain_cmd.rs
- forest/cli/src/cli/mod.rs
> Remove deprecated chain fetch and chain export from CLI 

- README.md
> Improve Ubuntu build instructions 

- Cargo.lock
- Cargo.toml
- actors/cron_v8/Cargo.toml
- actors/cron_v8/src/lib.rs
- actors/cron_v8/src/state.rs
- actors/cron_v8/src/testing.rs
- actors/cron_v9/Cargo.toml
- actors/cron_v9/src/lib.rs
- actors/cron_v9/src/state.rs
- actors/cron_v9/src/testing.rs
- Added `cron` v8
- Added `cron` v9
Closes 
> Cron versioned actors

- Cargo.lock
- Cargo.toml
- actors/system_v8/Cargo.toml
- actors/system_v8/src/lib.rs
- actors/system_v8/src/state.rs
- actors/system_v9/Cargo.toml
- actors/system_v9/src/lib.rs
- actors/system_v9/src/state.rs
- Added system v8 actor 
- Added system v9 actor 
Closes 
> System versioned actors

- Cargo.lock
- Cargo.toml
- actors/multisig_v8/Cargo.toml
- actors/multisig_v8/src/lib.rs
- actors/multisig_v8/src/state.rs
- actors/multisig_v8/src/testing.rs
- actors/multisig_v8/src/types.rs
- actors/multisig_v9/Cargo.toml
- actors/multisig_v9/src/lib.rs
- actors/multisig_v9/src/state.rs
- actors/multisig_v9/src/testing.rs
- actors/multisig_v9/src/types.rs
- Added multisig v8 actor
- Added multisig v9 actor
Closes 
> Multisig versioned actors

- networks/src/mainnet/mod.rs
- vm/actor_interface/src/builtin/account/mod.rs
- vm/actor_interface/src/builtin/init/mod.rs
- vm/actor_interface/src/builtin/market/mod.rs
- vm/actor_interface/src/builtin/miner/mod.rs
- vm/actor_interface/src/builtin/power/mod.rs
- vm/actor_interface/src/builtin/reward/mod.rs
- Set parameters for the NV17 upgrade.
Tracking issue: #1892
> chore: set epoch and actor cids for nv17 (shark).

- .cargo/config.toml
- Cargo.lock
- forest/daemon/Cargo.toml
- forest/daemon/src/main.rs
> Add support for tokio-console

- forest/daemon/Cargo.toml
- This feature should automagically handle SIGTERM and SIGHUP, see https://github.com/Detegr/rust-ctrlc#handling-sigterm-and-sighup
Closes https://github.com/ChainSafe/forest/issues/2261 (we can handle SIGQUIT in another issue)
> handle sigterm and sighup

- .github/workflows/rust.yml
- blockchain/chain/src/store/chain_store.rs
- blockchain/chain/src/store/errors.rs
- blockchain/state_manager/src/chain_rand.rs
- forest/cli/src/cli/snapshot_cmd.rs
- ipld/src/util.rs
- node/rpc/src/chain_api.rs
- utils/genesis/src/lib.rs
> Integrate snapshot export step in CI

- .github/workflows/rust.yml
- API_IMPLEMENTATION.md
- blockchain/chain/src/store/chain_store.rs
- blockchain/chain/src/store/index.rs
- forest/cli/src/cli/chain_cmd.rs
- networks/src/lib.rs
- node/rpc-api/src/lib.rs
- node/rpc-client/src/chain_ops.rs
- node/rpc/src/chain_api.rs
- node/rpc/src/lib.rs
- Adds an RPC command ValidateTipsetCheckpoints
- Invokes validate-tipset-checkpoints in CI
~~Open questions: Do we remove checkpoints that are out of range of the current snapshot file?~~
NOTE: To be merged after #2155 
Part of #2155 
> Validate tipset hashes via RPC command and add it as a CI step 

- Makefile
- fix dep installation fiasco introduced in https://github.com/ChainSafe/forest/pull/2280
Closes 
> fix mdbook-linkcheck fiasco

- .github/workflows/docs.yml
- .github/workflows/rust.yml
- Makefile
- allow using caching/existing `quickinstall` (plus make it a bit cleaner)
Closes 
> allow cached quickinstall

- forest/cli/src/cli/mod.rs
- clamped the JSON RPC code error. Without it, some commands failed miserably with a panic
```
❯ target/release/forest-cli --token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXSwiZXhwIjoxNjc0OTgyODUzfQ.I2CPKzz_WAYL3c-ep52j5u1iLF8Z6BMzhzhstXdAovw auth create-token --perm wallet
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', forest/cli/src/cli/mod.rs:118:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
now it still fails but in a more civilised way
```
❯ target/release/forest-cli --token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXSwiZXhwIjoxNjc0OTgyODUzfQ.I …
```
> fix JSON RPC code error

- Cargo.lock
- Cargo.toml
- blockchain/chain/src/store/index.rs
- blockchain/chain_sync/src/tipset_syncer.rs
- forest/shared/src/cli/snapshot_fetch.rs
- utils/forest_utils/Cargo.toml
- utils/forest_utils/src/io/progress_bar.rs
- utils/forest_utils/src/net/download.rs
> Replacement of `pbr` crate with `indicatif`

- CHANGELOG.md
- Cargo.lock
- forest/cli/Cargo.toml
- forest/daemon/Cargo.toml
- Patch release for progress bar fix.
Closes 
> chore: release forest v0.5.1

- blockchain/chain/src/store/index.rs
- Move checkpoint closer to current snapshot head.
Closes 
> chore: update calibnet tipset checkpoint

- Cargo.lock
- forest/cli/src/cli/snapshot_cmd.rs
- forest/daemon/src/daemon.rs
- forest/shared/src/cli/snapshot_fetch.rs
- Fix snapshot fetch default server selection
- Optimise snapshot new pattern matching
Closes #2163 
[Support the new protocol labs snapshot service](https://github.com/ChainSafe/forest/pull/2194#top)
#2194
> Snapshot fetch fixes

- .github/workflows/rust.yml
- CI sync check fails from time to time with forest snapshot, switch to `filecoin` provider until snapshot validation is in place.
Closes 
> fix: CI sync check temporary fix

- blockchain/chain/src/store/chain_store.rs
- Messages were accidentally removed from snapshots, making the snapshots invalid.
Closes #2334 
> fix: include messages in snapshots

- Cargo.lock
- documentation/src/trouble_shooting.md
- forest/daemon/Cargo.toml
- forest/daemon/src/main.rs
> Remove `check_for_low_fd`

- CHANGELOG.md
- Cargo.lock
- blockchain/chain_sync/src/chain_muxer.rs
- forest/daemon/src/daemon.rs
- node/forest_libp2p/src/peer_manager.rs
- node/forest_libp2p/src/service.rs
Closes https://github.com/ChainSafe/forest/issues/2391
> feat: ban peer with duration

- documentation/developer_documentation/RELEASE_CHECKLIST.md
- Add extra detail about release assets.
- Add step describing how to update the Forest Progress wiki.
Closes
> chore: include updating the forest wiki in the release checklist

- README.md
Before: [![GitHub Workflow Status](https://img.shields.io/github/workflow/status/ChainSafe/forest/Rust?style=for-the-badge)](https://github.com/ChainSafe/forest/actions)
After: [![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/ChainSafe/forest/rust.yml?style=for-the-badge)](https://github.com/ChainSafe/forest/actions)
Closes
> fix: ci badge in readme.md

- Makefile
- blockchain/message_pool/src/msgpool/msg_pool.rs
- blockchain/state_manager/src/lib.rs
- forest/shared/src/cli/mod.rs
- node/forest_libp2p/src/behaviour.rs
The else block adds unnecessary indentation and verbosity especially in our cases when else block happens in the end of the function.
Closes
> redundant_else pedantic check

- CHANGELOG.md
- Cargo.lock
- forest/shared/src/cli/config.rs
- node/db/Cargo.toml
- node/db/src/parity_db.rs
- node/db/src/parity_db_config.rs
- utils/metrics/src/lib.rs
- added working ParityDb statistics endpoint,
- unified `enable_statistics` and `compression_type` params for databases,
- fixed stats endpoint header to accommodate current and all future db backends :brain: 
Closes https://github.com/ChainSafe/forest/issues/2433
Sample `ParityDb` stats output
<details>
<summary>Log Output</summary>
```Paste log output here
❯ curl localhost:6116/stats/db
Column 0
Total values: 1373
Total bytes: 1551798
Total oversized values: 0
Total oversized bytes: 0
Total commits: 2303
New value insertions: 1373
Existing value insertions: 10048
Reference increases: 0
Missed reference increases: 0
Removals: 0
Missed removals: 0
Uncompressed bytes: 2896138
Compression deltas:
2080-2111: 3432
2112-2143: 2400
2304-2335: 4986 …
```
> fix db stats endpoint

- Cargo.toml
- scripts/find_unused_deps.rb
- also check workspace dependencies
- cleanup findings
Closes
> fix: improve find_unused_deps.rb

- Cargo.lock
- Cargo.toml
- blockchain/blocks/Cargo.toml
- blockchain/blocks/src/header/mod.rs
- blockchain/chain/Cargo.toml
- blockchain/chain/src/store/base_fee.rs
- blockchain/chain_sync/src/tipset_syncer.rs
- blockchain/consensus/deleg_cns/src/proposer.rs
- blockchain/message_pool/src/msgpool/msg_pool.rs
- blockchain/message_pool/src/msgpool/provider.rs
- blockchain/state_manager/src/lib.rs
- node/rpc/Cargo.toml
- node/rpc/src/gas_api.rs
- utils/forest_shim/Cargo.toml
- utils/forest_shim/src/econ.rs
- utils/forest_shim/src/lib.rs
> chore: shim `TokenAmount`

- CHANGELOG.md
- README.md
- forest/daemon/src/daemon.rs
- forest/shared/src/cli/client.rs
- forest/shared/src/cli/config.rs
- forest/shared/src/cli/mod.rs
- renamed `download_snapshot` to `auto-download-snapshot` and improved the docs around it a bit. The previous one turned out to be a bit ambiguous. 
Closes
> improve download snapshot documentation

- Cargo.lock
- Cargo.toml
- blockchain/chain/Cargo.toml
- blockchain/chain/src/store/chain_store.rs
- forest/cli/Cargo.toml
- forest/cli/src/cli/snapshot_cmd.rs
- ipld/Cargo.toml
- ipld/src/util.rs
- use `blake3` for having the seen entries while traversing the ipld
Closes https://github.com/ChainSafe/forest/issues/2490
> Hash entries walk snapshot

- .dockerignore
- Dockerfile
- add caching to the compilation layer - this allows seamlessly building the image and re-use the artefacts from the previous build. It is a significant improvement for folks building the image regularly on the local machine; previously, it would build everything from scratch (5 minutes for every minor change on my machine). This will reduce the CI time if on the same runner.
- minor, random tweaks to make the Dockerfile more ready for production environments
Closes https://github.com/ChainSafe/forest/issues/2513
> dockerfile caching + tweaks

- Cargo.lock
- node/db/Cargo.toml
Full changelog: https://github.com/rust-rocksdb/rust-rocksdb/releases
Closes
> chore: upgrade rocksdb

- README.md
> fix: bad license link in readme

- Cargo.lock
- forest/shared/src/cli/config.rs
- 
Closes https://github.com/ChainSafe/forest/issues/2541
> chore: upgrade toml-edit from v0.19.2 to v0.19.3 and fix tests

- blockchain/chain/src/store/chain_store.rs
- To make it easier to trouble shoot paritydb issue on https://github.com/ChainSafe/forest/pull/2524
Closes
> fix: print block cid on not found during walk_snapshot

- Cargo.lock
- Cargo.toml
- utils/forest_utils/Cargo.toml
Closes https://github.com/ChainSafe/forest/issues/2251
> chore: upgrade `pbr` and remove crate patch

- forest/daemon/src/daemon.rs
- forest/shared/src/cli/snapshot_fetch.rs
* show human-readable snapshot size when user is prompted to download the snapshot.
- Added `num-bigint` to `daemon`'s dependencies so that I can reuse the `to_size_string` util.
- Added `snapshot_fetch_size`, which just copies over the logic from the other parts of the file, have not DRYed this yet, need to check with @LesnyRumcajs.
Closes #2501
> feat: show snapshot size in prompt

- Cargo.lock
- blockchain/blocks/src/header/json.rs
- blockchain/blocks/src/header/mod.rs
- blockchain/consensus/fil_cns/src/validation.rs
- blockchain/state_manager/src/utils.rs
- forest/cli/Cargo.toml
- forest/cli/src/cli/fetch_params_cmd.rs
- types/src/verifier/mod.rs
- utils/forest_shim/Cargo.toml
- utils/forest_shim/src/lib.rs
- utils/forest_shim/src/sector.rs
- utils/json/src/sector.rs
- utils/paramfetch/Cargo.toml
- utils/paramfetch/src/lib.rs
- vm/actor_interface/src/builtin/miner/mod.rs
> SectorInfo fvm_shared v2->v3

- Cargo.lock
- blockchain/chain/src/store/chain_store.rs
- blockchain/chain_sync/src/tipset_syncer.rs
- blockchain/consensus/fil_cns/src/weight.rs
- blockchain/message_pool/src/msgpool/provider.rs
- blockchain/state_manager/src/lib.rs
- blockchain/state_manager/src/vm_circ_supply.rs
- node/rpc/src/wallet_api.rs
- utils/forest_shim/Cargo.toml
- utils/forest_shim/src/address.rs
- utils/forest_shim/src/state_tree.rs
- utils/statediff/Cargo.toml
- utils/statediff/src/lib.rs
- vm/interpreter/src/fvm.rs
- vm/interpreter/src/lib.rs
- vm/state_migration/src/lib.rs
- Implemented the `StateTree` variant to handle multiple state tree versions in a single place. It should make transitions smoother.
Part of https://github.com/ChainSafe/forest/issues/2438
> Seamless StateTree

- .github/workflows/docker.yml
- CHANGELOG.md
- Dockerfile
- Makefile
- Added multiplatform support for Docker images. It will work on amd64 and arm64 (e.g., M1, M2) architectures. We can add some more exotic ones in the future if there is a need for that.
Closes https://github.com/ChainSafe/forest/issues/2476
> Docker multiplatform image

- utils/paramfetch/src/lib.rs
- 
Closes https://github.com/ChainSafe/forest/issues/2555
> chore: improve param fetch console output

- CHANGELOG.md
- Cargo.lock
- forest/shared/src/cli/config.rs
- node/forest_libp2p/Cargo.toml
- node/forest_libp2p/src/config.rs
- node/forest_libp2p/src/service.rs
- node/rpc-client/Cargo.toml
- node/rpc-client/src/lib.rs
- 
Closes https://github.com/ChainSafe/forest/issues/2551
> feat(libp2p): support multiple listen addr

- documentation/src/SUMMARY.md
- update documentation index with docker page
Closes
> update documentation index with docker page

- README.md
deps.rs is down again. Maybe we should consider disabling it for good as it does not yet support workspace dependencies anyway
Closes
> fix(CI): bad deps.rs links in readme.md

- utils/forest_shim/src/gas.rs
- Fix typo in the GasCharge shim.
Closes
> fix: typo when converting gas charges

- Cargo.lock
- Cargo.toml
- Fixes https://github.com/ChainSafe/forest/security/dependabot/22
Closes
> fix: dependabot alert #22

- blockchain/chain_sync/src/tipset_syncer.rs
- utils/forest_shim/src/address.rs
- utils/forest_shim/src/state_tree.rs
- vm/actor_interface/src/builtin/ethaccount/mod.rs
- vm/actor_interface/src/builtin/mod.rs
- vm/actor_interface/src/builtin/placeholder/mod.rs
- vm/interpreter/src/lib.rs
- porting https://github.com/filecoin-project/lotus/blob/6c0a2feade9ac2c5d9d35a31839a606ff94c0179/chain/consensus/common.go#L134 so that we don't skip delegated messages.
Closes https://github.com/ChainSafe/forest/issues/2601
> validate delegated messages

- .github/workflows/docker.yml
- .github/workflows/rust.yml
> fix(ci): try ubuntu:focal on buildject

- Cargo.lock
- utils/paramfetch/Cargo.toml
- utils/paramfetch/src/lib.rs
This reverts commit 2b5515d29834be56816fb5447d7a57abb977da90.
- fixes hashes mismatches for proof params
- adds more strict verification (previously the errors were being ignored)
Re-opens https://github.com/ChainSafe/forest/issues/2458
> Revert "feat: read data as trustless gateway with car stream (#2604)"

- API_IMPLEMENTATION.md
- forest/cli/src/cli/send_cmd.rs
- forest/cli/src/cli/wallet_cmd.rs
- key_management/src/wallet.rs
- node/rpc-api/src/lib.rs
- node/rpc/src/wallet_api.rs
- Returns Option<String> for wallet_default_address RPC fn.
Closes #2663 
(if possible),
> Return optional string in default_wallet_address

- utils/forest_shim/src/address.rs
- utils/forest_shim/src/econ.rs
- Added new `From` impl for Address and TokenAmount shim.
Closes
(if possible),
> Added new `From` impl for Address and TokenAmount Shim

- Cargo.lock
- Cargo.toml
- blockchain/blocks/src/header/mod.rs
- utils/statediff/Cargo.toml
- utils/statediff/src/lib.rs
- update the lockfile
Closes
(if possible),
> update fil actor states

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Summarise the changes for release v0.7.0
(if possible),
> Prepare for release v0.7.0

- .github/workflows/docker.yml
- This should increase our pull rate limits from 100 to 200 (per 6 hours); hopefully, it will resolve most `too many requests` issues for now.
Closes
(if possible),
> login to dockerhub

- .github/CODEOWNERS
- tyshko5 is no longer on the team, remove him from the code-owners list.
Closes
(if possible),
> chore: remove tyshko5 from the code-owners list

- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/rust.yml
Metrics:
|job|branch|cache status|time
|--|--|--|--|
|test|pr|no cache|[16min](https://github.com/ChainSafe/forest/actions/runs/4677532706/jobs/8285153392?pr=2758)|
|test|pr|cache hit|[13min17s](https://github.com/ChainSafe/forest/actions/runs/4677532706/jobs/8285593800)|
|test|main|cache hit|[11m59s](https://github.com/ChainSafe/forest/actions/runs/4673112264/jobs/8275980128)|
Closes https://github.com/ChainSafe/forest/issues/2757
> feat(ci): try mozilla-actions/sccache-action

- .github/workflows/docker.yml
- CHANGELOG.md
- README.md
- documentation/src/docker.md
- `latest` tag shall denote the latest stable release
- `edge` tag shall denote the latest development build (latest main build)
`forest-iac` PR: https://github.com/ChainSafe/forest-iac/pull/72
Closes https://github.com/ChainSafe/forest/issues/2767
⚠️ after merging, the sync check on DO should be updated to use the `edge` tag, don't merge if you don't intend to change it! 
> Stable tag

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepare release `v0.7.2` codename _Roberto_, the main motivation being having the `latest` tag pointing to the latest stable release.
Closes
> prepare release v0.7.2

- node/forest_libp2p/bitswap/tests/go_compat.rs
- improve bitswap test err msg when `go-bitswap` code does not compile
Closes
> fix(test): improve bitswap test err msg

- CHANGELOG.md
- Cargo.toml
> prepare release v0.8.0

- documentation/src/developer_documentation/release_checklist.md
> doc: Update release checklist on including `Cargo.lock`

- .github/workflows/rust.yml
- scripts/calibnet_health_check.sh
- re-enable calibnet check job
Closes
> re-enable calibnet checks

- scripts/calibnet_health_check.sh
- Double the number of tries when checking send of FIL token
Closes
> Try waiting for more blocks

- node/forest_libp2p/src/behaviour.rs
- utils/forest_utils/src/version/mod.rs
- fixes agent name
before using the crawler:
```
time="2023-04-27T14:23:01+02:00" level=info msg="Upsert agent version" agentVersion=0.8.1+git.6af7a8e29
```
after
```
time="2023-04-27T14:33:05+02:00" level=info msg="Upsert agent version" agentVersion=forest-0.8.1+git.de581140d
```
Closes
> fix agent name

- networks/src/mainnet/mod.rs
- Use the correct bundle for NV19,
Closes
https://github.com/filecoin-project/builtin-actors/releases/tag/v11.0.0
https://github.com/filecoin-project/lotus/blob/master/build/builtin_actors_gen.go#L439-L461
> use correct bundle for actors v11

- node/rpc/src/chain_api.rs
-
Closes  https://github.com/ChainSafe/forest/issues/2810
> fix: create tmp file at the same mount point during snapshot export

- blockchain/chain/src/store/chain_store.rs
- blockchain/chain_sync/src/tipset_syncer.rs
- blockchain/state_manager/src/lib.rs
- Remove unused `Result` type
- Remove unnecessary clone
Closes
> chore: minor code clean-up

- .github/CODEOWNERS
- Add @aatifsyed to the list of code-owners
Closes
> chore: add Aatif as a codeowner

- forest/cli/src/subcommand.rs
- forest/daemon/src/daemon.rs
- forest/shared/src/cli/config.rs
- forest/shared/src/cli/mod.rs
- networks/src/lib.rs
- Remove `NetworkChain::from_str` constructor
- Remove testing of combination of `--chain` and `--config`
- Add `ChainConfig::from_chain` constructor
Closes
> Code clean-up

- Cargo.lock
- blockchain/chain/src/store/chain_store.rs
- forest/cli/src/cli/snapshot_cmd.rs
- forest/daemon/src/bundle/mod.rs
- forest/daemon/src/daemon.rs
- ipld/src/cid_hashset.rs
- ipld/src/util.rs
- node/db/src/rolling/gc.rs
- utils/forest_utils/Cargo.toml
- utils/forest_utils/src/db/file_backed_obj.rs
- utils/genesis/src/lib.rs
As part of https://github.com/ChainSafe/forest/issues/2688
- track estimated db records in meta.yaml after snapshot import and `walk_snapshot`
Closes
> feat: track estimated db records in meta.yaml

- Cargo.lock
- build/bootstrap/calibnet
- build/bootstrap/mainnet
- networks/Cargo.toml
- networks/src/calibnet/mod.rs
- networks/src/mainnet/mod.rs
- moved bootstrap peers into separate files to re-use them across the project.
Part of https://github.com/ChainSafe/forest/issues/2789
> move bootstrap peers to seperate files

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepare release 0.8.2
Closes
> prepare release v0.8.2

- CHANGELOG.md
- Fixed bad CHANGELOG formatting
Closes
> fixed CHANGELOG formatting

- Makefile
- blockchain/blocks/Cargo.toml
- blockchain/chain/Cargo.toml
- blockchain/chain_sync/Cargo.toml
- blockchain/message_pool/Cargo.toml
- blockchain/state_manager/Cargo.toml
- node/rpc-api/Cargo.toml
- node/rpc/Cargo.toml
- utils/test_utils/Cargo.toml
- vm/interpreter/Cargo.toml
- vm/message/Cargo.toml
- Remove the `blst` feature flag since it is non-optional. The flag is required by the FVM.
Closes
> chore: remove unnecessary `blst` feature

- .github/workflows/forest.yml
- We have some transient CI test failures that forest crashes with `bad instruction` error. We could log info for further investigation
Closes
> feat(ci): lscpu to help investigate transient test failures

- Cargo.lock
- Cargo.toml
- Use latest version 2.0.0 of fil actor states
Closes
> Use version num for fil actor state crates

- documentation/src/SUMMARY.md
- documentation/src/developer_documentation/state_migration_guide.md
- added State Migration guide to the developer documentation
Closes
> state migration guide

- .github/workflows/unit-tests.yml
- addresses @hanabi1224 comment https://github.com/ChainSafe/forest/pull/2863#pullrequestreview-1424194245 regarding possible issues with doc tests and including markdown files in Rust source code.
Closes
> don't ignore markdown in crates

- Cargo.lock
- Cargo.toml
- upgrade zstd and async-compression
Closes
zstd v1.5.4 changelog: https://github.com/facebook/zstd/blob/dev/CHANGELOG#L20
> chore: upgrade zstd and async-compression

- .github/workflows/docker.yml
- .github/workflows/forest.yml
- .github/workflows/rust-lint.yml
- .github/workflows/unit-tests.yml
- disabled path ignores. While the workflows are skipped successfully, the mandatory checks still want them to pass. There's a solution but it requires some tinkering and we need to unblock the CI for now.
Closes
> disable path ignores

- Cargo.toml
> Remove blst in the feature list

- forest/cli/src/main.rs
- forest/daemon/src/main.rs
- forest/shared/src/cli/mod.rs
- Add a `--dry-run` flag
This should help us validate some of our Ruby scripts in the CI.
Closes
> Add dry run flag to forest and forest-cli

- documentation/src/docker.md
- The `Address` should now be correctly handled and so we need to update the wallet in Docker documentation.
Closes
> fix Docker docs

- blockchain/chain/src/store/chain_store.rs
- blockchain/chain/src/store/index.rs
- blockchain/consensus/deleg_cns/configs/delegator-config.toml
- blockchain/consensus/deleg_cns/configs/proposer-config.toml
- blockchain/state_manager/src/lib.rs
- forest/cli/src/cli/chain_cmd.rs
- forest/cli/src/cli/snapshot_cmd.rs
- forest/daemon/src/bundle/mod.rs
- forest/daemon/src/daemon.rs
- forest/daemon/src/main.rs
- forest/daemon/tests/common/mod.rs
- forest/shared/src/cli/mod.rs
- forest/shared/src/cli/snapshot_fetch.rs
- forest/shared/src/lib.rs
- networks/src/lib.rs
- node/rpc/src/chain_api.rs
- utils/genesis/src/lib.rs
- move to a more strict type for the network
Closes
> network as enum

- Cargo.toml
- ~~I keep having to remove it "temporarily" in order to do some debugging. No more!~~
- I still have to do it but documented why it shouldn't be the default.
Closes
> Add comment for debug builds

- blockchain/state_manager/src/lib.rs
- utils/forest_shim/src/machine/mod.rs
- vm/interpreter/src/vm.rs
- Breaking up PR #2880 into multiple, smaller PRs. This PR replaces direct FVM usages of `MultiEngine` with a `forest_shim` implementation.
Closes associated tasks in #2713.
> Prune direct FVM usage of `MultiEngine`

- README.md
- additional instructions to run the forest-cli in a terminal window
- adding a user-friendly docker command
> adding startup instructions

- .github/CODEOWNERS
> Add @ruseinov to the list of code-owners

- .github/CHECKPOINT_ISSUE_TEMPLATE.md
- Fix yaml list in `CHECKPOINT_ISSUE_TEMPLATE.md`.
Closes
> fix: use valid yaml list in template for recurrent checkpoint task

- .github/CHECKPOINT_ISSUE_TEMPLATE.md
- Fix the github markdown syntax to render the checkboxes correctly.
Closes
> chore: fix checkbox syntax in issue template

- src/state_migration/common/macros/system.rs
- src/state_migration/common/migration_job.rs
- src/state_migration/common/migrators.rs
- src/state_migration/common/mod.rs
- src/state_migration/common/state_migration.rs
- src/state_migration/nv18/init.rs
- src/state_migration/nv19/miner.rs
- src/state_migration/nv19/power.rs
As part of https://github.com/ChainSafe/forest/issues/2801
- Adds a `DeferredMigrator` type that delegates the explicit migration logic to post migrator(s)
Go code: https://github.com/filecoin-project/go-state-types/blob/master/builtin/v9/migration/top.go
```go
// Set of prior version code CIDs for actors to defer during iteration, for explicit migration afterwards.
deferredCodeIDs := make(map[cid.Cid]struct{})
...
for name, oldCodeCID := range oldCodeIDMap { //nolint:nomaprange
if name == manifest.MarketKey || name == manifest.VerifregKey {
deferredCodeIDs[oldCodeCID] = struct{}{}
} else {
...
}
}
...
if err = actorsIn.ForEachV4(func(addr address.Address, actorIn *builtin.ActorV4) error {
if _, ok := deferredCodeIDs[actorIn.Code]; ok {
return nil …
```
> feat: add deferred migrator for nv17 state migration

- CHANGELOG.md
- I didn't think to update the changelog in the previous PR. It should be listed as a breaking change.
Closes
> chore: update changelog for the `preimage` changes

- Cargo.lock
- documentation/src/developer_documentation/release_checklist.md
Fixes the `release_checklist.md` and includes `Cargo.lock` package version update.
> [Fix] Cargo.lock package version

- .github/workflows/unit-tests.yml
- since recently, we started hitting timeouts on the unit test workflow. This should make the CI greener (the cost of buildjet would not increase, given we'd have to manually re-run everything anyway, it could even decrease)
Closes
> parallelize debug/release unit tests

- documentation/src/SUMMARY.md
- documentation/src/basic_usage.md
- documentation/src/snapshot_export.md
- added snapshot export documentation as per @jennijuju suggestion,
- rewritten basic usage page to reflect the current state-of-the-art
Closes
> add snapshot export documentation, rewrite basic usage

- src/state_manager/mod.rs
- This should match the Go code https://github.com/filecoin-project/lotus/blob/30a9f631653fed86072322b4dfccb31219ecb1f5/chain/stmgr/utils.go#L154-L163
- we eventually push this method to the FVM externs which caused state mismatch at epoch 2997616
Closes
> match tipset getter code with Lotus

- .github/workflows/forest.yml
- the devnet job turned out to be flaky, therefore let's disable it until it is fixed.
Closes
> disable devnet in the CI

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: update CHANGELOG and bump version to 0.11

- Cargo.lock
- Cargo.toml
- src/ipld_amt/amt.rs
- src/ipld_amt/diff.rs
- src/ipld_amt/error.rs
- src/ipld_amt/mod.rs
- src/ipld_amt/node.rs
- src/ipld_amt/root.rs
- src/ipld_amt/tests/amt_tests.rs
- src/ipld_amt/tests/diff_tests.rs
- src/ipld_amt/value_mut.rs
- src/lib.rs
- src/state_migration/nv17/miner.rs
- Temporarily embed fvm_ipld_amt to unblock the release. 
Closes
https://github.com/filecoin-project/ref-fvm/pull/1788
https://github.com/ChainSafe/forest/issues/3099
https://github.com/ChainSafe/fil-actor-states/issues/143
> fix: temporarily embed fvm_ipld_amt to unblock release

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Dagny Taggert because I messed up the tags of the last release. No user-visible changes at all.
Closes
> release: v0.11.1

- src/libp2p/rpc/decoder.rs
- src/utils/io/writer_checksum.rs
> Remove Unpin constraints

- src/blocks/errors.rs
> chore: remove unnecessary block time errors

- Cargo.lock
- Cargo.toml
- src/cli/subcommands/fetch_params_cmd.rs
- src/interpreter/vm.rs
- src/lib.rs
- src/message_pool/msgpool/test_provider.rs
- src/networks/mod.rs
- src/shim/crypto.rs
- src/shim/error.rs
- src/shim/mod.rs
- src/shim/sector.rs
- src/shim/state_tree.rs
- src/shim/version.rs
- src/state_migration/common/migration_job.rs
- src/utils/proofs_api/paramfetch.rs
- `frc46_token` is unused, remove it.
- Re-exported signatures are unused, remove them.
- Remove `Inner` trait.
Closes
> chore: remove vestigial code

- CHANGELOG.md
- src/blocks/tipset.rs
- src/chain/mod.rs
- src/chain/store/chain_store.rs
- src/chain/store/index.rs
- src/chain/store/mod.rs
- src/cli/main.rs
- src/cli/subcommands/archive_cmd.rs
- src/cli/subcommands/mod.rs
- Implement `forest-cli archive info` which displays basic information about an archive file.
Closes #3166 
> feat: `forest-cli archive info`

- src/blocks/tipset.rs
- src/chain_sync/chain_muxer.rs
- src/chain_sync/network_context.rs
- src/fil_cns/mod.rs
- src/libp2p/service.rs
- src/rpc/state_api.rs
- there's no need for bitswap to know anything about epochs
Closes
> chore: bitswap doesn't care about epochs

- src/beacon/drand.rs
- src/beacon/tests/drand.rs
- src/blocks/header/mod.rs
- src/daemon/mod.rs
- src/networks/mod.rs
- src/rpc/auth_api.rs
- src/rpc/beacon_api.rs
- src/rpc/chain_api.rs
- src/rpc/common_api.rs
- src/rpc/db_api.rs
- src/rpc/gas_api.rs
- src/rpc/mod.rs
- src/rpc/mpool_api.rs
- src/rpc/net_api.rs
- src/rpc/node_api.rs
- src/rpc/state_api.rs
- src/rpc/sync_api.rs
- src/rpc/wallet_api.rs
- src/rpc_api/data_types.rs
- src/state_manager/mod.rs
- The `Beacon` is a source of randomness. Hide the implementation rather than pass around its type everywhere.
Closes
> chore: hide beacon implementation

- rust-toolchain.toml
- src/key_management/wallet_helpers.rs
- src/libp2p/behaviour.rs
- src/libp2p/rpc/mod.rs
- src/message_pool/msgpool/selection.rs
- src/rpc/chain_api.rs
- src/shim/executor.rs
- [Rust 1.71](https://blog.rust-lang.org/2023/07/13/Rust-1.71.0.html) got new, shiny clippy lints.
Closes
> bump rust toolchain to 1.71

- src/cli/subcommands/snapshot_cmd.rs
- src/daemon/mod.rs
- src/fil_cns/composition.rs
- src/interpreter/vm.rs
- src/rpc/sync_api.rs
- src/state_manager/mod.rs
- Removes the `RewardCalc` trait and its implementations.
Closes #3075 
> chore: remove RewardCalc trait

- .github/workflows/forest.yml
- scripts/tests/calibnet_other_check.sh
- the test turned out to be flaky, see more https://github.com/ChainSafe/forest/issues/3209
Closes
> fix: temp disable state fetch tests

- .github/workflows/docs.yml
- the link checker is failing too often; let's relax the retries policy a bit (the default is three retries with 1s sleep in-between).
Closes
> retry link checker

- src/cli/subcommands/snapshot_cmd.rs
- actor bundles may be necessary when validating a snapshot.
- tests will be added as a follow-up PR.
Closes
> fix: download bundles in `forest-cli snapshot validate`

- scripts/gen_coverage_report.sh
- Add `send` command to Forest code coverage report
Closes #2669 
> Add `send` command to code coverage report

- src/cli_shared/cli/config.rs
- src/daemon/main.rs
> refactor: unconfigure tokio

- Cargo.lock
- Cargo.toml
- src/daemon/mod.rs
- src/networks/calibnet/mod.rs
- src/networks/mainnet/mod.rs
- src/networks/mod.rs
- we always had an error about unparsable Multiaddrss. This was because the included file always contained a newline which spawned an empty entry. This resolves this warning and makes sure we don't have them in the future.
Closes
> prune bootstrap peers

- src/ipld/util.rs
- Depth-first iteration should be separate from the chain stream.
Closes
> refactor: separate ipld iterator from chain stream

- src/ipld/cid_hashmap.rs
- src/ipld/cid_hashset.rs
- src/ipld/mod.rs
- src/libp2p_bitswap/request_manager.rs
- src/message_pool/msgpool/test_provider.rs
- src/state_migration/common/macros/verifier.rs
- src/state_migration/common/state_migration.rs
- src/state_migration/common/verifier.rs
Closes associated task in #3202 
> `CidHashMap` implementation

- src/cli/subcommands/snapshot_cmd.rs
- set default output destination to the current directory,
- prompt if we're about to overwrite the destination file (inhibit with `--force`),
- show a progress bar.
Closes
> feat: snapshot compress: default output, progress bar, overwrite prompt

- build/known_blocks.yaml
- update list with two new entries
Closes
> chore: update the list of known block headers

- src/db/car/many.rs
- parallelize `get` in `ManyCar`
Closes
> parallel manycar get

- src/chain_sync/chain_muxer.rs
- src/chain_sync/consensus.rs
- src/chain_sync/network_context.rs
- src/chain_sync/tipset_syncer.rs
- src/cli/subcommands/snapshot_cmd.rs
- src/fil_cns/composition.rs
- src/fil_cns/mod.rs
- src/fil_cns/validation.rs
- src/genesis/mod.rs
- src/interpreter/mod.rs
- src/libp2p/chain_exchange/provider.rs
- src/libp2p/service.rs
- src/message_pool/msgpool/msg_pool.rs
- src/metrics/mod.rs
- src/rpc/mod.rs
- src/rpc/mpool_api.rs
- src/shim/state_tree.rs
- src/state_manager/utils.rs
- src/state_manager/vm_circ_supply.rs
- src/state_migration/common/macros/system.rs
- src/state_migration/common/macros/verifier.rs
- src/state_migration/common/migration_job.rs
- src/state_migration/common/migrators.rs
- src/state_migration/common/mod.rs
- src/state_migration/nv18/init.rs
- src/state_migration/nv19/miner.rs
- src/state_migration/nv19/power.rs
Continue the work in https://github.com/ChainSafe/forest/pull/3294 as part of https://github.com/ChainSafe/forest/issues/2676
- Remove Clone from most of Blockstore type constraints
Closes
> fix: remove Clone from most of Blockstore type constraints

- documentation/src/SUMMARY.md
- documentation/src/developer_documentation/database_migrations.md
- added a proposed database migration plan. I'm open to discussing it.
Closes
> database migration plan

- Cargo.lock
- Cargo.toml
- src/daemon/mod.rs
- this automatic soft FD limit increase should prevent issues like here [forest-mainnet_2023-08-09T19_50_17_forest.txt](https://github.com/ChainSafe/forest/files/12310960/forest-mainnet_2023-08-09T19_50_17_forest.txt)
```
2023-08-09T19:50:39.596081Z ERROR forest_filecoin::metrics::db: Calculating DB size for metrics failed: Error { kind: Io(Os { code: 24, kind: Uncategorized, message: "Too many open files" }), message: "Io error. Look inside err_kind for more details." }
2023-08-09T19:50:40.620353Z ERROR hyper::server::tcp: accept error: Too many open files (os error 24)
2023-08-09T19:50:41.621565Z ERROR hyper::server::tcp: accept error: Too many open files (os error 24)
2023-08-09T19:50:42.622454Z ERROR hyper::server::tcp: accept error: Too many …
```
> auto increase FD limit

- .cargo/audit.toml
- Cargo.lock
- Cargo.toml
- src/key_management/keystore.rs
> fix(security): use renamed crypto_secretbox instead of xsalsa20poly1305

- src/state_migration/tests/mod.rs
- Use non CDN link
- Add 5s http timeout
- Add retry
Closes
> fix(test): make state migration tests more robust

- src/ipld/json.rs
> test: add ignored repro for #3383

- src/ipld/util.rs
- src/utils/encoding/cid_de_cbor.rs
- Adopt the new Cid parser in DFS.
work on #3314 
Needs to be merged after #3379 . After switching the base branch.
> [Enhancement] DFS is using a faster parser now.

- CHANGELOG.md
- src/utils/io/progress_log.rs
- Completely removed inaccurate progress log ETA (instead of attempting to correct it, based on the discussions in #3178).
Closes #3178 
> Remove progress log ETA

- src/ipld/cid_hashset.rs
- Introduces `contains` method to `CidHashSet`.
Closes
> [Chore] CidHashSet::contains

- Cargo.lock
- Cargo.toml
- documentation/src/SUMMARY.md
- documentation/src/environment_variables.md
- src/db/car/many.rs
- src/utils/io/mmap.rs
- src/utils/io/mod.rs
Related to https://github.com/ChainSafe/forest/issues/3361
- use Mmap in `ManyCar::read_only_files` for better performance.
P.S. benchmark shows the performance of using vanilla Mmap API is 2-5x better than using a Mmap wrapper that implements `positioned-io` traits, we could benchmark and discuss about it later
calibnet snapshot(local laptop):
```console
main branch:
traversed 2.84 GiB at 104.91 MiB/s in 00:00:27
traversed 2.84 GiB at 104.65 MiB/s in 00:00:27
traversed 2.84 GiB at 103.04 MiB/s in 00:00:28
feature branch:
traversed 2.84 GiB at 139.04 MiB/s in 00:00:20
traversed 2.84 GiB at 157.26 MiB/s in 00:00:18
traversed 2.84 GiB at 161.50 MiB/s in 00:00:17
```
mainnet snapshot(DO droplet):
```console
➜  car_db /root/forest-tool-main benchmark …
```
> feat(perf): use Mmap in `ManyCar::read_only_files`

- Makefile
- rust-toolchain.toml
- src/chain/store/chain_store.rs
- src/cli/subcommands/info_cmd.rs
- src/cli/subcommands/mpool_cmd.rs
- src/ipld/frozen_cids.rs
- src/shim/machine/manifest.rs
- upgrade rust toolchain
- upgrade VENDORED_DOCS_TOOLCHAIN
Closes
> chore: upgrade rust toolchain to 1.72

- Makefile
- benches/car-index.rs
- src/utils/db/car_index/car_index_builder.rs
Came across the issue when benchmarking https://github.com/ChainSafe/forest/pull/3414
- Fix build errors and clippy warnings in benchmarks
- Update `make lint-clippy` to cover benches
Closes
> fix(benches): Make sure benches compile

- assets/actor_bundles.car.zst
- assets/ci_download.sh
- build.rs
- src/networks/mod.rs
- replaced the bundle on git lfs,
- updated sizes,
- added bundle to the downloaded ones for the `forest-tool state-migration actor-bundle`,
Closes https://github.com/ChainSafe/forest/issues/3421
> Add Shark actors for devnet actor bundle

- src/chain_sync/chain_muxer.rs
- src/chain_sync/tipset_syncer.rs
- src/cli_shared/cli/config.rs
- src/fil_cns/validation.rs
- src/interpreter/vm.rs
- src/message_pool/msgpool/msg_pool.rs
- src/networks/mod.rs
- src/rpc/mod.rs
- lower `u64` and `usize` to `u32` such that they can be encoded as TOML.
- implement `Arbitrary` for `Config`.
- remove `ConfigPartial`.
Closes #2965
> chore: implement arbitrary for `Config`

- .github/CHECKPOINT_ISSUE_TEMPLATE.md
- build/known_blocks.yaml
- Update snapshot checkpoint for:
mainnet at epoch `3110400`
calibnet at epoch `864000`
Also update the code comment and checkpoints issue template to reflect the migration of the `archive` command from `forest-cli` to `forest-tool`.
Closes #3438 
> Monthly update of snapshot checkpoints

- CHANGELOG.md
> release: v0.13.0 "Holocron"

- .github/workflows/docker.yml
- .github/workflows/unit-tests.yml
- documentation/src/SUMMARY.md
- documentation/src/developer_documentation/archie_and_fuzzy.md
- `fuzzy` is faster and cheaper than `buildjet`.
Closes
> ci: use `fuzzy` as an action runner

- src/db/migration/migration_map.rs
- use a macro to have the migration declaration more readable
Closes
> migration declaration as macro

- src/tool/subcommands/state_migration_cmd.rs
- print the path to the saved bundle,
Closes
> write bundle path to stdout

- src/state_migration/nv21/miner.rs
To address https://chainsafeio.slack.com/archives/C0144LHN732/p1696942089024669?thread_ts=1696931765.174969&cid=C0144LHN732
- verify SectorOnChainInfoV12::flags is properly migrated
Closes
> test: verify SectorOnChainInfoV12::flags is properly migrated

- .github/workflows/lotus-devnet-publish.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- assets/actor_bundles.car.zst
- assets/ci_download.sh
- scripts/devnet/.env
- scripts/devnet/ci_check.sh
- scripts/devnet/docker-compose.yml
- scripts/devnet/lotus.dockerfile
- scripts/devnet/run_it.sh
- scripts/devnet/update-schedules.diff
- src/daemon/mod.rs
- src/networks/calibnet/mod.rs
- src/networks/devnet/mod.rs
- src/networks/mod.rs
- src/shim/sector.rs
- src/state_manager/utils.rs
- src/state_migration/common/migration_job.rs
- src/state_migration/common/mod.rs
- src/state_migration/common/state_migration.rs
- src/state_migration/mod.rs
- src/state_migration/nv21/migration.rs
- src/state_migration/nv21/miner.rs
- src/state_migration/nv21/mod.rs
- src/state_migration/type_migrations/miner/mod.rs
- src/state_migration/type_migrations/miner/power_pair_v11_to_v12.rs
- src/state_migration/type_migrations/miner/sector_onchain_info_v11_to_v12.rs
- support NV21 watermelon upgrade for devnet & caliubnet
- support state migration
Closes https://github.com/ChainSafe/forest/issues/3422
Closes https://github.com/ChainSafe/forest/issues/3573
> NV21 Watermelon 🍉 support

- src/state_migration/nv17/util.rs
-[ this PR ](https://github.com/ChainSafe/fil-actor-states/pull/122)won't be merged and so the TODO is now WON'T DO.
Closes https://github.com/ChainSafe/forest/issues/3576
> Remove obsolete TODO

- scripts/devnet/.env
- scripts/devnet/lotus.dockerfile
- use Lotus release tag instead of a wild commit from even a wilder branch for devnet testing.
Closes
> use Lotus release in devnet

- build/bootstrap/mainnet
- synced to https://github.com/filecoin-project/lotus/blob/master/build/bootstrap/mainnet.pi
Closes
> update mainnet boostrap nodes

- .github/workflows/coverage.yml
- scripts/gen_coverage_report.sh
- Fix errors in code coverage script.
- Run a small version of the code coverage script in PRs when they're out of draft.
Closes
> fix: update code coverage script and prevent similar problems in the future

- CHANGELOG.md
- scripts/devnet/docker-compose.yml
- scripts/devnet/forest_config.toml.tpl
- src/cli_shared/cli/config.rs
- tests/common/mod.rs
- tests/db_migration_tests.rs
- tests/db_mode_tests.rs
- tests/import_snapshot_tests.rs
- tests/keystore_tests.rs
- remove chain section from forest config by adding `serde(ignore)` to the field, as suggested [here](https://github.com/ChainSafe/forest/pull/3608#discussion_r1365485628). The follow-up cleanup will be in https://github.com/ChainSafe/forest/pull/3608
Closes
> fix: remove chain section from forest config

- .github/workflows/coverage.yml
- Code coverage is broken. Disable it until it can be fixed.
Closes
> ci: don't generate the code coverage report

- Cargo.lock
- Cargo.toml
- bump versions of `fvm@4` and `fvm_shared@4`
Closes
> chore(deps): bump fvm@4 version

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db/migration/migration_map.rs
- update changelog.
- increment Forest crate version.
- add void migration for `v0.14.0` to `v0.15.0`
Closes
> release: v0.15.0 "Buttress"

- src/lotus_json/mod.rs
- src/rpc_api/data_types.rs
- src/rpc_api/mod.rs
- src/rpc_client/chain_ops.rs
- src/rpc_client/state_ops.rs
- src/shim/sector.rs
- src/tool/subcommands/api_cmd.rs
- Client-side tests for the following methods:
- `ChainGetParentMessages`
- `StateGetRandomnessFromBeacon`
- `StateReadState`
- `StateMinerActiveSectors`
Closes
> chore: test high-priority RPC methods

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db/migration/migration_map.rs
Target branch is `stable-0.14` which is based on `v0.14.0` plus cherry-picked #3622.
- Update changeling
- Update crate version
- Update migration map
Crate file size is now around 4.9M.
Closes #3656
> release: v0.14.1

- tests/lint.rs
https://github.com/ChainSafe/forest/issues/3665
> chore: disable flaky lint

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db/migration/migration_map.rs
- prepare release v0.15.2
- ~~migrate both from v0.15.0 and v0.15.1 because why not~~
Closes
> prepare release v0.15.2 "Defenestration"

- src/rpc_client/chain_ops.rs
- src/tool/subcommands/api_cmd.rs
- Test the `ChainGetTipSet` rpc method.
Part of #3639
> test: lotus compatibilty test for `ChainGetTipSet` rpc method

- .github/workflows/docker-latest-tag.yml
- .github/workflows/docker.yml
- documentation/src/developer_documentation/release_checklist.md
- don't push `latest` tag automatically. This prevents the backport releases from overriding the `latest` tag.
- workflow dispatch to semi-manually tag given release with `latest`
- added step in the release checklist
Closes
> Docker image: retag workflow

- src/libp2p/behaviour.rs
- I see no reason why this message would be a warning. Downgraded to `info`.
Closes
> fix wrong log level

- .github/workflows/docker-latest-tag.yml
- https://github.com/actions/runner/issues/1483
Closes
> booleans are not booleans in GH inputs

- CHANGELOG.md
- release `v0.16.0` "Rottenmelon"
Closes
> prepare release v0.16.0

- src/cli/subcommands/mod.rs
- align `forest-cli chain head` output format with `lotus chain head`
[Lotus code](https://github.com/filecoin-project/lotus/blob/fbafe1c507f362c82d2cd5540b6c5d580dae8e74/cli/chain.go#L89)
```go
var ChainHeadCmd = &cli.Command{
Name:  "head",
Usage: "Print chain head",
Action: func(cctx *cli.Context) error {
afmt := NewAppFmt(cctx.App)
api, closer, err := GetFullNodeAPI(cctx)
return err
}
defer closer()
ctx := ReqContext(cctx)
head, err := api.ChainHead(ctx)
return err
}
for _, c := range head.Cids() {
afmt.Println(c)
}
return nil
},
}
```
Closes
> fix: align `forest-cli chain head` output format with `lotus chain head`

- src/cli/subcommands/chain_cmd.rs
- src/rpc/chain_api.rs
- src/rpc_client/chain_ops.rs
- Update `Filecoin.ChainReadObj` RPC API to make it compatible with `lotus`
- Update `forest-cli` accordingly
`forest-tool API compare [snapshot]` output:
```
➜  lotus git:(master) forest-tool api compare ~/fr/snapshots/calibnet/1072560_2023_11_09T04_13_00Z.car.zst
| RPC Method                            | Forest              | Lotus         |
|---------------------------------------|---------------------|---------------|
| Filecoin.ChainGetBlock                | Valid               | Valid         |
| Filecoin.ChainGetBlockMessages        | Valid               | Valid         |
| Filecoin.ChainGetGenesis              | Valid               | Valid         |
| Filecoin.ChainGetMessage (160) …
```
> fix: Make `Filecoin.ChainReadObj` RPC API compatible with lotus

- src/cli/subcommands/chain_cmd.rs
- align `forest-cli chain message` output format with `lotus chain getmessage`
`forest-cli chain message -c bafy2bzacea6lxnnmrzzo7ofmsk6orukxgr7i6mzkxlk546feozpg6aufq2pqy` output:
```json
{
"Version": 0,
"To": "t410fzkuntk5rh5bqqou6ocrrfdb6rqj6flezkpwsq5q",
"From": "t410faw2tt3p5yabrh7ooaou6zlu4xhp2qw4qotd6cya",
"Nonce": 83,
"Value": "0",
"GasLimit": 22817538,
"GasFeeCap": "100150",
"GasPremium": "99950",
"Method": 3844450837,
"Params": "WQKEanYSAgAAAAAAAAAAAAAAAOMMAbcnkOkES23vYcWOKTpZ8HhUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA …
```
> fix: align `forest-cli chain message` output format with `lotus chain getmessage`

- src/tool/subcommands/archive_cmd.rs
It's useful to use the root CIDs of a snapshot to manually construct JSON payload for testing RPC endpoints with tools like [Fiddler](https://www.telerik.com/download/fiddler) or [Insomnia](https://insomnia.rest/)
- print root CIDs in `forest-tool archive info` output
Sample output:
```console
➜  calibnet forest-tool archive info forest_snapshot_calibnet_2023-11-09_height_1073049.forest.car.zst
CAR format:    ForestCARv1.zst
Network:       calibnet
Epoch:         1073049
State-roots:   2000
Messages sets: 2557
Root CIDs:     bafy2bzacebux6f2ghxfq4tu4qpzdviv5vdzechb375psacohtlxnjenf2fdqa
bafy2bzacebhgg75eqyc36eri5l3clms7u6fhokzg55uceo3qwbclaz5ftqq36
bafy2bzaceb5nml3ofry3h7xfhx2522exymgkqg75xw5gbi5lj3j6ykfat64su …
```
> feat: print root CIDs in `forest-tool archive info` output

- src/tool/subcommands/api_cmd.rs
When `forest-tool api compare` uses a shared tipset that contains no messages, it's insufficient to test API like `ChainGetMessagesInTipset`, this PR tries to use the latest tipset that contains messages instead.
e.g. in `forest_snapshot_calibnet_2023-11-09_height_1073049.forest.car.zst`, the heaviest tipset contains no messages.
(See https://calibration.filfox.info/en/tipset/1073049)
- ~~ensure shared tipset has messages~~ Use the last 20 tipsets instead for `chain_get_block_messages_req`, `chain_get_messages_in_tipset_req` and `chain_get_parent_messages_req`
```console
Running `target/debug/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2023-11-09_height_10 …
```
> fix(api compare): test get_xx_messages API with the last 20 tipsets

- src/rpc/chain_api.rs
- fix `Filecoin.ChainGetMessage` server error when requesting a signed message
Payload:
```json
{
"jsonrpc": "2.0",
"id": 2,
"method": "Filecoin.ChainGetMessage",
"params": [
{
"/": "bafy2bzacedpkf2v5kgm4mvvljer6q3s45yfcdzaiyl3xdoivt5m53iv77v76w"
}
]
}
```
Before:
```json
{
"jsonrpc": "2.0",
"error": {
"code": 0,
"message": "Serialization error for Cbor protocol: RequireLength { name: \"tuple\", expect: 10, value: 2 }"
},
"id": 2
}
```
After:
```json
{
"jsonrpc": "2.0",
"result": {
"Version": 0,
"To": "t410famf46pkqzlieylsxhenre5ajqkutbbrb652rziy",
"From": "t410fot3vkzzorqg4alowvghvxx4mhofhtazixbm6z2i",
"Nonce": 26944,
"Value": "0",
"GasLimit": 33780427,
"GasFeeCap": "201100",
"GasPremium": …
```
> fix: `Filecoin.ChainGetMessage` server error when requesting a signed message

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db/migration/migration_map.rs
- release v0.16.1 "(Re)Fresh(ed)Melon"
Closes
> chore: prepare release v0.16.1

- CHANGELOG.md
- build/bootstrap/calibnet
- added a new bootstrap peer for calibnet ran by glif node team
- originally introduced in https://github.com/filecoin-project/lotus/pull/11175
Closes
> add calib bootstrap node peer run by glif node team

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db/migration/migration_map.rs
> prepare release v0.16.2

- .github/workflows/coverage.yml
- .github/workflows/docker.yml
- .github/workflows/docs.yml
- .github/workflows/forest.yml
- .github/workflows/rust-lint.yml
- .github/workflows/scripts-lint.yml
- .github/workflows/unit-tests.yml
- This should help fork PRs like https://github.com/ChainSafe/forest/pull/3727 to run workflows. The issue is that the fork doesn't have access to, e.g., SCCACHE variables. While it introduces [security implications](https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests), it should be okay, given we explicitly approve every workflow to run.
Closes
> fix workflows for fork PRs

- src/networks/actors_bundle.rs
- just a cosmetic change, given RC3 is now final. The CIDs remain the same.
Closes
> use official release for actor bundle v12.0.0

- .github/workflows/coverage.yml
- .github/workflows/docker.yml
- .github/workflows/docs.yml
- .github/workflows/forest.yml
- .github/workflows/rust-lint.yml
- .github/workflows/scripts-lint.yml
- .github/workflows/unit-tests.yml
This reverts commit b7ac40354c713ef2e087a6e4c1f0c59c61a28bef.
- the https://github.com/ChainSafe/forest/pull/3728 didn't work, see https://github.com/ChainSafe/forest/pull/3730, the culprit being https://github.com/orgs/community/discussions/44322.
Closes
> Revert "fix workflows for fork PRs (#3728)"

- src/rpc_client/beacon_ops.rs
- src/rpc_client/mod.rs
- src/tool/subcommands/api_cmd.rs
- Added support for `Filecoin.BeaconGetEntryj` API
> Implemented Filecoin.BeaconGetEntry API 

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db/migration/migration_map.rs
- Release version 0.16.3, code name "Tempura".
Closes
> release: Forest 0.16.3 "Tempura" 🍤

- documentation/src/developer_documentation/release_checklist.md
- make the retag more visible by making it a separate step (and adding a mildly related emoji)
Closes
> retag as separate step in the checklist

- src/ipld/json.rs
- src/rpc/state_api.rs
- src/rpc_api/data_types.rs
- src/rpc_api/mod.rs
- src/rpc_client/state_ops.rs
- src/tool/subcommands/api_cmd.rs
- add tests for StateSearchMsg* RPC APIs
| RPC Method                          | Forest        | Lotus |
|-------------------------------------|---------------|-------|
| Filecoin.StateSearchMsg (13)        | MissingMethod | Valid |
| Filecoin.StateSearchMsgLimited (13) | MissingMethod | Valid |
Closes
> test: add tests for StateSearchMsg* RPC APIs

- src/rpc/mod.rs
- src/rpc/state_api.rs
- src/rpc_api/mod.rs
- src/rpc_client/state_ops.rs
- src/tool/subcommands/api_cmd.rs
- Implement the `GetRandomnessFromTickets` RPC method.
```
| RPC Method                             | Forest | Lotus |
|----------------------------------------|--------|-------|
| Filecoin.StateGetRandomnessFromTickets | Valid  | Valid |
```
Part of #3639
> feat: implement GetRandomnessFromTickets and validate against Lotus

- README.md
> docs: fix logo dimensions

- documentation/src/developer_documentation/rpc_api_compatibility.md
- src/rpc/eth_api.rs
- src/rpc/mod.rs
- src/rpc/rpc_http_handler.rs
- src/rpc/rpc_util.rs
- src/rpc_api/mod.rs
- src/rpc_client/eth_ops.rs
- src/rpc_client/mod.rs
- src/tool/subcommands/api_cmd.rs
- Add support for v1 RPC methods.
- Implement `EthChainId`.
- Test against Lotus.
| RPC Method          | Forest | Lotus |
|---------------------|--------|-------|
| Filecoin.EthChainId | Valid  | Valid |
Part of #3640
> feat: implement `EthChainId` and validate against Lotus

- src/lotus_json/mod.rs
- src/rpc/mod.rs
- src/rpc/state_api.rs
- src/rpc_api/mod.rs
- src/rpc_client/state_ops.rs
- src/tool/subcommands/api_cmd.rs
- Implement the `StateMinerProvingDeadline`
- Test implementation against Lotus
Part of #3639
> feat: implement `StateMinerProvingDeadline` and verify against Lotus

- src/state_migration/common/migration_job.rs
- src/state_migration/common/mod.rs
- src/state_migration/common/state_migration.rs
- src/state_migration/nv21/miner.rs
- src/state_migration/type_migrations/miner/sector_onchain_info_v11_to_v12.rs
- few optimizations which allow running Forest NV21 state migration for mainnet on commodity hardware. Previously, it was running out of memory on a VPS (due to the unbounded cache), and on my machine, it was 4x slower (20 minutes on my machine vs 5 now).
On a DO VPS with specs
```
CPU: DO-Premium-AMD (8) @ 2.300GHz        
Memory: 15978MiB                  
```
It takes 1556s to run an NV21 state migration.
On the **Beast**
```
CPU: 13th Gen Intel i9-13900KF (32) @ 5.500GHz
Memory: 64119MiB
```
It takes 349s.
Note that the performance degrades significantly after a single migration, due to the number of entries in the database.
Closes
> optimize state migrations

- documentation/src/developer_documentation/state_migration_guide.md
- added a short perf guide for state migrations to the developer documentation.
Closes
> docs: add state migrations perf guide

- .config/forest.dic
- Cargo.lock
- Cargo.toml
- src/rpc/common_api.rs
- src/rpc/mod.rs
- src/rpc_api/mod.rs
- Implement the `Filecoin.Session` RPC method.
Part of #3639
> feat: implement the `Session` RPC method and validate against Lotus

- build/bootstrap/mainnet
- https://github.com/filecoin-project/lotus/blob/master/build/bootstrap/mainnet.pi (https://github.com/filecoin-project/lotus/commit/92c3b0a42d36528a6f2297df6001bec97ece5692)
Closes
> update mainnet bootstrap peers

- Cargo.lock
- src/rpc/mod.rs
- src/rpc/state_api.rs
- src/rpc_api/data_types.rs
- src/rpc_api/mod.rs
- src/rpc_client/state_ops.rs
- src/tool/subcommands/api_cmd.rs
- Added support for Filecoin.StateMinerSectorCount API
```
| RPC Method                          | Forest | Lotus |
|-------------------------------------|--------|-------|
| Filecoin.StateMinerSectorCount (60) | Valid  | Valid |
```
> Implemented Filecoin.StateMinerSectorCount API

- CHANGELOG.md
- src/rpc/mod.rs
- src/rpc/mpool_api.rs
- src/rpc_api/mod.rs
- src/rpc_client/mpool_ops.rs
- src/tool/subcommands/api_cmd.rs
- Filecoin.MpoolGetNonce Lotus-compatible RPC
work on https://github.com/ChainSafe/forest/issues/3639
Tested with: `cargo forest-tool api compare --filter MpoolGetNonce --lotus /dns/127.0.0.1/tcp/1234/http snapshot-latest`
> [Feature] Filecoin.MpoolGetNonce Lotus-compatible RPC.

- README.md
- snapshot links got broken (DO app got removed), this fixes the CI errors like https://github.com/ChainSafe/forest/actions/runs/7200174133/job/19613514256?pr=3820
Closes
> fix broken snapshot links

- src/rpc/mod.rs
- src/rpc/state_api.rs
- src/rpc_api/mod.rs
- src/rpc_client/state_ops.rs
- src/tool/subcommands/api_cmd.rs
- Added support for Filecoin.MsigGetAvailableBalance API
```
| RPC Method                       | Forest | Lotus |
|----------------------------------|--------|-------|
| Filecoin.MsigGetAvailableBalance | Valid  | Valid |
```
> Implemented Filecoin.MsigGetAvailableBalance API

- Cargo.lock
- rust-toolchain.toml
- src/chain_sync/mod.rs
- src/db/migration/migration_map.rs
- src/ipld/mod.rs
- src/ipld/selector/mod.rs
- src/ipld/tests/cbor_test.rs
- src/libp2p_bitswap/mod.rs
- src/rpc_api/data_types.rs
- src/rpc_client/mod.rs
- src/shim/state_tree.rs
- src/utils/io/mod.rs
- Fix all clippy warnings
Closes
https://releases.rs/docs/1.75.0/
> chore: upgrade rust toolchain to 1.75.0

- Cargo.lock
- Cargo.toml
- src/tool/subcommands/api_cmd.rs
- tests/lint.rs
- Bump non-fvm crate minor versions
- Fix build errors
Manually tested api compare output
```
Running `target/debug/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-01-03_height_1231457.forest.car.zst --filter Eth`
| Filecoin.EthAccounts       | Valid  | Valid |
| Filecoin.EthBlockNumber    | Valid  | Valid |
| Filecoin.EthChainId        | Valid  | Valid |
| Filecoin.EthGasPrice       | Valid  | Valid |
| Filecoin.EthGetBalance (4) | Valid  | Valid |
```
Closes
> chore(deps): bump dependency minor versions

- .github/workflows/docker.yml
- .github/workflows/docs.yml
- .github/workflows/forest.yml
- .github/workflows/rust-lint.yml
- Disable S3 sccache for foreign PRs.
- Disable wallet tests for foreign PRs.
Closes
> ci: greenlight foreign prs

- Cargo.lock
- Cargo.toml
- src/beacon/drand.rs
- src/beacon/tests/drand.rs
- Add `ask_and_verify_beacon_entry_success` unit test
- Add timeout and retry to remote beacon fetch logic
- Add network hash to the remote beacon url
- Avoid heap allocations in message construction logic in `verify_entry`
- Enable `multicore` feature for `bls-signatures` crate (to benefit `verify_bls_aggregate`)
Closes
> test: more verify_beacon_entry tests

- src/networks/drand.rs
- Add unit tests for drand configs
Closes
> test: unit tests for drand configs

- .github/workflows/forest.yml
- Some devnet jobs seem to be failing, we need logs to properly debug them.
https://github.com/ChainSafe/forest/pull/3889#issuecomment-1900254632
Closes
> always dump docker logs in devnet

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db/migration/migration_map.rs
- prepare release v0.16.5 `Pinecone Deactivation`
Closes
> prepare release v0.16.5 Pinecone Deactivation

- .github/workflows/docker-latest-tag.yml
- .github/workflows/docker.yml
- Dockerfile
As part of https://github.com/ChainSafe/forest/issues/3892
- generate fat docker images that contain proof parameter files (choosing `-fat` suffix as it's shorter for typing)
- update CI workflows accordingly
- actor bundle inclusion will be done in a separate PR, together with readme updates
Closes
> feat: generate fat docker image that contains proof parameters

- Dockerfile
- documentation/src/environment_variables.md
- src/daemon/bundle.rs
As part of https://github.com/ChainSafe/forest/issues/3892
This PR tries to provide a way of saving the actor bundle into the forest fat docker images and avoid downloading on node bootstrap.
~Changes to the Dockerfile will be made after either https://github.com/ChainSafe/forest/pull/3902 or https://github.com/ChainSafe/forest/pull/3904 is merged.~
```Dockerfile
...
ENV FOREST_ACTOR_BUNDLE_PATH="/var/tmp/forest_actor_bundle.car.zst"
...
RUN forest-tool state-migration actor-bundle $FOREST_ACTOR_BUNDLE_PATH
...
```
- allow specifying local actor bundle path via the `FOREST_ACTOR_BUNDLE_PATH` environment variable
- update docs accordingly
- generate actor bundle in fat docker image
Closes https://github.com/ChainSafe/forest/issues/3892
[1]: …
> feat: allow specifying local actor bundle path via environment variable

- src/blocks/header.rs
- src/chain_sync/chain_muxer.rs
- src/chain_sync/tipset_syncer.rs
- src/shim/clock.rs
I've recently seen quite a few slow or timeout CI jobs that get stuck in `forest-cli sync wait`, the forest node takes a very long time to sync to the latest successfully, see https://github.com/ChainSafe/forest/actions/runs/7695770546/job/20969652867#step:6:2624
I suspect that the forest node receives time-traveling blocks that fail block validation thus block the sync process. This PR tries to fix the problem by logging and filtering out those time-traveling blocks in `evaluate_network_head`.
A few cases caught by this PR:
https://github.com/ChainSafe/forest/actions/runs/7706715957/job/21002855670?pr=3914#step:6:1679
https://github.com/ChainSafe/forest/actions/runs/7706715957/job/21002855567?pr=3914#step:6:1753
Manually re-run the CI jobs for this PR a few times and did not reproduce …
> fix(ci): `forest-cli sync wait` tasks always get stuck

- .github/workflows/forest.yml
- Offline RPC check seems to flaky, disabling the check until fixed 
Issue created: https://github.com/ChainSafe/forest/issues/3926
Closes
> Disable Offline RPC Check

- Cargo.lock
- Cargo.toml
- src/interpreter/vm.rs
- src/shim/trace.rs
- src/state_manager/utils.rs
- in preparation for NV22, bump FVM4 to 4.1.2,
- make adjustments based on the breaking changes.
Closes
> bump fvm4 to 4.1.2

- Cargo.lock
- Cargo.toml
- src/ipld/util.rs
- Removes `kanal` library in favour of `flume`. 
Closes https://github.com/ChainSafe/forest/issues/3906
> [Chore] Remove kanal, simplify logic.

- src/ipld/util.rs
- A comment requested here https://github.com/ChainSafe/forest/pull/3925#discussion_r1475729528
Closes
> [Comment] Panic in unorederd graph traversal.

- src/beacon/drand.rs
- potentially fixes issues like this [CI fiasco](https://github.com/ChainSafe/forest/actions/runs/7753388955/job/21144598103).
Closes
> increase timeout for drand tests

- src/beacon/drand.rs
- src/beacon/mock_beacon.rs
- src/blocks/header.rs
- incorporate latest changes from https://github.com/filecoin-project/lotus/pull/11572  (unfortunately it's impossible to reference the changes because the upstream PR does not keep the commit history)
Closes
> fix: incorporate latest changes from lotus FIP-0063 implementation PR

- .github/workflows/forest.yml
Increase test script timeout to mitigate the timeout issue we've recently seen
- increase test script timeout
Closes
> fix(ci): increase test script timeout

- src/networks/drand.rs
- this _time_, there's a drand test that needs a bit more _time_ from _time_ to _time_. It doesn't fail all the _time_, but happened last _time_ [here](https://github.com/ChainSafe/forest/actions/runs/7815832292/job/21320028325?pr=3945). It's _time_ to get rid of such failures!
Closes
> increase timeout in drand tests

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db/migration/migration_map.rs
- prepare release `v0.16.6` Pinecone Reactivation
Closes
> prepare release 0.16.6

- src/chain/store/chain_store.rs
- src/chain_sync/chain_muxer.rs
- src/chain_sync/tipset_syncer.rs
- src/cli/subcommands/snapshot_cmd.rs
- src/fil_cns/validation.rs
- src/libp2p/chain_exchange/provider.rs
- src/message_pool/msgpool/provider.rs
- src/rpc/chain_api.rs
- src/rpc/eth_api.rs
- src/rpc/gas_api.rs
- src/rpc/mpool_api.rs
- src/rpc/node_api.rs
- src/rpc/state_api.rs
- src/rpc_api/data_types.rs
- src/rpc_api/mod.rs
- src/state_manager/mod.rs
Part of https://github.com/ChainSafe/forest/issues/3861
`TipsetKey` should not be empty and can be refactored using `NonEmpty` collections. However, this is blocked by the RPC implementations that assume `TipsetKey` to be empty and fall back to the heaviest tipset. This PR tries to refactor RPC implementations to use `ApiTipsetKey(Option<TipsetKey>)` instead. The actual refactoring to the `TipsetKey` struct will come in a subsequent PR.
- refactor RPC implementations to use `ApiTipsetKey(Option<TipsetKey>)`
- rename `ChainStore::load_required_tipset` to `ChainStore::load_required_tipset_with_fallback`
- fix non-RPC code that misuses the `_with_fallback` version of `load_*_tipset`
Closes
[1]: …
> fix: refactor RPC implementations to use ApiTipsetKey(Option<TipsetKey>) to not assume TipsetKey to be empty

- src/libp2p/chain_exchange/message.rs
Originally part of https://github.com/ChainSafe/forest/pull/3984  
Use a small PR to make it easier to review
- refactor `fts_from_bundle_parts` to not indexing slicing
Closes
> fix: refactor `fts_from_bundle_parts` to not indexing slicing

- src/chain/store/chain_store.rs
- src/rpc/chain_api.rs
- src/rpc/mpool_api.rs
- src/rpc/state_api.rs
> refactor: load_required_tipset_with_fallback

- src/genesis/mod.rs
- src/message_pool/msg_chain.rs
- src/message_pool/msgpool/mod.rs
Originally part of https://github.com/ChainSafe/forest/pull/3984  
Use a small PR to make it easier to review
- refactor msg chain to reduce indexing slicing
Closes
> fix: refactor msg chain to reduce indexing slicing

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db/migration/migration_map.rs
- prepare release v0.16.7 "Etaoin shrdlu"
Closes
> prepare release v0.16.7 "Etaoin shrdlu"

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/db/migration/migration_map.rs
- Release version 0.16.8 of Forest.
Closes
> release: 0.16.8 "English Channel"

- build/known_blocks.yaml
- updated known blocks
Closes https://github.com/ChainSafe/forest/issues/4015
> update known blocks

- .github/workflows/rust-lint.yml
- .github/workflows/unit-tests.yml
- .gitmodules
- README.md
- src/blocks/tests/serialization-vectors/README.md
- src/blocks/tests/serialization-vectors/block_headers.json
- src/blocks/tests/serialization-vectors/message_signing.json
- src/blocks/tests/serialization-vectors/unsigned_messages.json
- src/blocks/tests/serialization_vectors.rs
- the submodule is archived and pretty small (a few kilobytes), so it doesn't make sense to keep it as a submodule. Let's have it copied in.
- the other submodule was not a submodule, probably a leftover from the one crate refactor,
Closes
> chore: no submodules

- Cargo.lock
- Cargo.toml
- src/rpc/channel.rs
- src/rpc/mod.rs
- src/rpc_client/mod.rs
- retire `jsonrpc-v2`
- upgrade `jsonrpsee`
Closes #4008, #4003
> fix(deps): retire jsonrpc-v2

- src/chain_sync/network_context.rs
- src/chain_sync/tipset_syncer.rs
- src/daemon/db_util.rs
- Fix a bug in assembling chain exchange messages into full tipets when the response length is different from the request length
- Add some basic validation to `handle_chain_exchange_request` when request type is `MESSAGE`
Closes
> fix(p2p): validate chain exchange responses & bug fix

- src/rpc/chain_api.rs
- src/rpc/mod.rs
- src/rpc_api/mod.rs
- src/rpc_client/chain_ops.rs
- src/tool/subcommands/api_cmd.rs
- implement `Filecoin.ChainGetTipSetAfterHeight` RPC method
Closes
> feat(rpc): implement Filecoin.ChainGetTipSetAfterHeight

- CHANGELOG.md
- src/cli/subcommands/net_cmd.rs
- src/libp2p/behaviour.rs
- src/libp2p/discovery.rs
- src/libp2p/service.rs
- src/rpc/mod.rs
- src/rpc/net_api.rs
- src/rpc_api/mod.rs
- src/rpc_client/net_ops.rs
- src/tool/subcommands/api_cmd.rs
- added support for `Filecoin.NetAgentVersion` RPC command,
- added `--agent/-a` flag to `forest-cli net peers` subcommand.
Sample output:
```
❯ forest-cli net peers --agent
12D3KooWQPYouEAsUQKzvFUA9sQ8tz4rfpqtTzh2eL6USd9bwg7x, [/dns4/calibration.node.glif.io/tcp/1237/p2p/12D3KooWQPYouEAsUQKzvFUA9sQ8tz4rfpqtTzh2eL6USd9bwg7x], lotus-1.25.1+calibnet+git.1e0c8bb
12D3KooWJzQZHgMkMWipdUGKfBrnBbvi7UiC3pp8TQAWGrnNMNvF, [/ip4/52.14.121.29/tcp/34000/p2p/12D3KooWJzQZHgMkMWipdUGKfBrnBbvi7UiC3pp8TQAWGrnNMNvF], forest-0.16.7+git.1f8c947
12D3KooWS3ZRhMYL67b4bD5XQ6fcpTyVQXnDe8H89LvwrDqaSbiT, [/dns4/bootstrap-calibnet-1.chainsafe-fil.io/tcp/34000/p2p/12D3KooWS3ZRhMYL67b4bD5XQ6fcpTyVQXnDe8H89LvwrDqaSbiT], forest-0.16.6+git.fbd880d …
```
> implement `--agent` for `net peers`

- src/chain_sync/tipset_syncer.rs
Follow-up of https://github.com/ChainSafe/forest/pull/4027
https://github.com/ChainSafe/forest/pull/4027 fixed a bug in chain exchange logic when `request len != response len`, however, the incomplete response leads to the below error(which does not block the sync tho). This PR tries to improve `get_batch` logic to get complete response with multiple chain exchange requests, to get rid of the below error.
```
bafy2bzacecvrbndaxoxqwgdx4ydlauxakrqyhdhorpx75hsrnkv3sauihneda] in EPOCH = 1413731 failed: Validation error: Validation error: Could not compute base fee: Invalid tipset: no msg root with cid 
```
-
Closes
> fix(p2p): improve chain exchange client logic

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepare release v0.17.0 "Smaug" - updated changelog and bumped versions
Closes
> prepare release v0.17.0 "Smaug" :dragon: 

- Cargo.lock
- Cargo.toml
- src/state_migration/common/state_migration.rs
- it's the only place we use `crossbeam`, let's use `flume` everywhere.
Closes https://github.com/ChainSafe/forest/issues/4041
> remove crossbeam dependency in favor of flume

- .github/workflows/api_tests.yml
- a triggered workflow needs to be first on a default branch to get triggered https://github.com/orgs/community/discussions/25288. Let's have a dummy one to unblock https://github.com/ChainSafe/forest/pull/4053
Closes
> dummy rpc api tests workflow

- Cargo.toml
- src/cli_shared/cli/mod.rs
- mention tokio-console memory issues.
Closes
Once the new version of `console-subscriber` is released - we need to upgrade and test this.
> [Comment] Tokio-console memory leak.

- Cargo.lock
- Cargo.toml
- src/cli/subcommands/attach_cmd.rs
> chore(deps): bump boa-* to 0.18

- CHANGELOG.md
- scripts/tests/calibnet_offline_rpc_check.sh
- src/tool/subcommands/api_cmd.rs
- support multiple snapshots in the `forest-tool api serve` command,
- minor cleanup of the existing code.
Closes https://github.com/ChainSafe/forest/issues/4058
> support multiple snapshots in `api serve`

- .github/workflows/docker.yml
- fixes a regression in https://github.com/ChainSafe/forest/actions/runs/8295123967/job/22702037896 caused by https://github.com/ChainSafe/forest/pull/4053
Closes
> Fix `push` in docker workflow

- scripts/tests/api_compare/.env
- Updates Lotus version in the JSON-RPC API tests to the latest release.
> [automated] Update Lotus version in API tests

- .github/workflows/docker.yml
- https://github.com/ChainSafe/forest/pull/4063 uncovered yet another Docker action expectation I held to, which cracked. 
Closes
> Really fix push in docker workflow

- scripts/tests/api_compare/api_compare.sh
- scripts/tests/api_compare/filter-list
- src/tool/subcommands/api_cmd.rs
- add a filter file feature to the `api compare` to whitelist or blacklist tests,
- blacklisted tests that are consistently failing. The rest is run in CI.
Closes
> add api-compare filter list

- src/rpc/mod.rs
- src/rpc/net_api.rs
- src/rpc_api/mod.rs
- src/rpc_client/net_ops.rs
- src/tool/subcommands/api_cmd.rs
- Implement RPC method `Filecoin.NetVersion`
Test output:
```
➜  forest git:(hm/rpc-net-version) cargo run --bin forest-tool -- api compare --filter NetVersion ~/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-03-20_height_1453001.forest.car.zst
Finished dev [unoptimized] target(s) in 0.35s
Running `target/debug/forest-tool api compare --filter NetVersion /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-03-20_height_1453001.forest.car.zst`
| RPC Method          | Forest | Lotus |
|---------------------|--------|-------|
| Filecoin.NetVersion | Valid  | Valid |
```
Lotus code:
```go
func (a *EthModule) NetVersion(_ context.Context) (string, error) {
return strconv.FormatInt(build.Eip155ChainId, 10), nil
}
```
Closes
[1]: …
> feat(rpc): implement Filecoin.NetVersion

- CHANGELOG.md
- scripts/tests/api_compare/filter-list
- src/rpc_api/data_types.rs
- src/state_manager/utils.rs
This PR is addressing changes regarding the new Tracing API introduced in Lotus `v1.26.0-rc3` (see [CHANGELOG](https://github.com/filecoin-project/lotus/blob/v1.26.0-rc3/CHANGELOG.md#tracing-api)) and port them to Forest.
- Remove `code_cid` in `MessageTrace`
- Add support for `ActorTrace`
```console
$ RUST_LOG=forest_filecoin::rpc_client=debug ./target/debug/forest-tool api compare --lotus /ip4/127.0.0.1/tcp/1234/http --forest /ip4/127.0.0.1/tcp/2345/http forest_snapshot_calibnet_2024-03-18_height_1448006.forest.car.zst --filter StateCall
| RPC Method               | Forest | Lotus |
|--------------------------|--------|-------|
| Filecoin.StateCall (114) | Valid  | Valid |
```
Closes
> Fix `Filecoin.StateCall`

- src/cid_collections/hash_set.rs
- src/ipld/util.rs
- src/tool/subcommands/snapshot_cmd.rs
- Replace `recurse_links_hash` with `stream_chain` as it is much nicer.
Closes
> refactor: replace manual async IPLD recursion with a stream

- Cargo.lock
- Cargo.toml
- scripts/devnet/.env
- scripts/devnet/lotus.dockerfile
- src/networks/actors_bundle.rs
- src/networks/devnet/mod.rs
- src/networks/mainnet/mod.rs
- prepare dependencies and Cids for the upcoming Dragon upgrade for mainnet
Closes
> prepare dragon mainnet

- Makefile
- https://github.com/ChainSafe/forest/issues/4109
```
error: 1 denied warning found!
Crate:     yaml-rust
Version:   0.4.5
Warning:   unmaintained
Title:     yaml-rust is unmaintained.
Date:      2024-03-20
ID:        RUSTSEC-2024-0320
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0320
Dependency tree:
yaml-rust 0.4.5
└── insta 1.36.1
└── forest-filecoin 0.17.0
See .config/audit.toml
make: *** [Makefile:54: audit] Error 1
```
Closes
> suppress RUSTSEC-2024-0320

- src/cli/subcommands/sync_cmd.rs
Realized `sync wait` logic is outdated when implementing `Filecoin.EthSyncing`, update it to match lotus 
- update sync wait logic to match lotus 
[lotus code](https://github.com/filecoin-project/lotus/blob/master/cli/sync.go#L280):
```go
working := -1
for i, ss := range state.ActiveSyncs {
switch ss.Stage {
case api.StageSyncComplete:
default:
working = i
case api.StageIdle:
// not complete, not actively working
}
}
if working == -1 {
working = len(state.ActiveSyncs) - 1
}
ss := state.ActiveSyncs[working]
```
Closes
> fix(cli): match sync wait logic with lotus

- scripts/tests/calibnet_offline_rpc_check.sh
- src/tool/subcommands/api_cmd.rs
- use memory db for offline RPC server
Closes #4089, #3962
> fix(tool): use memory db for offline RPC server

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepare release v0.17.1 [Villentretenmerth](https://witcher.fandom.com/wiki/Villentretenmerth)
Closes
> prepare v0.17.1 Villentretenmerth

- scripts/tests/api_compare/docker-compose.yml
- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- src/rpc_client/chain_ops.rs
- src/shim/state_tree.rs
- src/shim/state_tree_v0.rs
- src/tool/subcommands/api_cmd.rs
- Use shared_tipset that is 10 epochs older than the heaviest one in the snapshot (for offline RPC server)
- Add more debug info
Closes
> fix(rpc): fix rpc tests for offline server

- src/rpc/state_api.rs
- src/state_manager/circulating_supply.rs
- src/state_manager/mod.rs
- rename and documentation for `get_state_circulating_supply`
Closes https://github.com/ChainSafe/forest/issues/4153
> [Enhcancement] get_state_circulating_supply.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepare mandatory release v0.17.2 (to merge after https://github.com/ChainSafe/forest/pull/4151)
Closes
> prepare release v0.17.2 "Dovakhin"

- src/cli/subcommands/chain_cmd.rs
- src/cli/subcommands/snapshot_cmd.rs
- src/lotus_json/mod.rs
- src/rpc/auth_layer.rs
- src/rpc/beacon_api.rs
- src/rpc/chain_api.rs
- src/rpc/mod.rs
- src/rpc/mpool_api.rs
- src/rpc/snapshots/.gitattributes
- src/rpc/snapshots/forest_filecoin__rpc__tests__openrpc.snap
- src/rpc/types.rs
- src/rpc_client/chain_ops.rs
- src/shim/error.rs
- src/tool/subcommands/api_cmd.rs
> refactor: migrate chain_api to use trait RpcMethod (part 1)

- CHANGELOG.md
- src/rpc/auth_layer.rs
- src/rpc/eth_api.rs
- src/rpc/mod.rs
- src/rpc_client/eth_ops.rs
- src/tool/subcommands/api_cmd.rs
- Add `Filecoin.Web3ClientVersion` RPC method
```console
2024-04-09T13:13:53.442487Z  TRACE forest_filecoin::tool::subcommands::api_cmd: forest Ok(String("0.17.2+git.42ee8f8a6b"))
2024-04-09T13:13:53.442580Z  TRACE forest_filecoin::tool::subcommands::api_cmd: lotus  Ok(String("1.26.1+calibnet+git.9dc9a5cf4.dirty"))
| Filecoin.Web3ClientVersion | Valid  | Valid |
```
Closes #4166
> feat: Implement `Filecoin.Web3ClientVersion` method

- .config/forest.dic
- CHANGELOG.md
- documentation/src/SUMMARY.md
- documentation/src/healthcheck.md
- scripts/tests/calibnet_kademlia_check.sh
- scripts/tests/calibnet_stateless_mode_check.sh
- src/cli_shared/cli/client.rs
- src/cli_shared/cli/mod.rs
- src/daemon/mod.rs
- src/health/endpoints.rs
- src/health/mod.rs
- src/lib.rs
- src/libp2p/peer_manager.rs
- implemented `/healthz`, `/readyz` and `/livez` healthcheck endpoints.
Closes https://github.com/ChainSafe/forest/issues/3949
> implement healthcheck endpoints

- src/db/migration/v0_12_1.rs
- src/db/migration/v0_16_0.rs
- removed redundant clones that ended up being in abandonware issue
Closes https://github.com/ChainSafe/forest/issues/3691
> remove redundant clones

- Cargo.lock
- Cargo.toml
- src/rpc_client/state_ops.rs
- src/state_manager/mod.rs
- src/tool/subcommands/api_cmd.rs
Part of https://github.com/ChainSafe/forest/issues/4164 merge after https://github.com/ChainSafe/fil-actor-states/pull/287 being released and published
- implement Filecoin.StateMarketBalance and tests
```
| Filecoin.StateMarketBalance (28)                | Valid  | Valid |
```
Closes #4189
> feat(rpc): implement Filecoin.StateMarketBalance

- src/rpc/methods/gas.rs
- src/rpc/mod.rs
- src/rpc/snapshots/forest_filecoin__rpc__tests__openrpc.snap
- src/rpc_client/gas_ops.rs
- src/shim/crypto.rs
- src/tool/subcommands/api_cmd.rs
- Fix the gas limit computation by signing the incoming message (with a dummy signature).
- Verify exact compliance of `GasEstimateGasLimit` against Lotus.
Closes #901
> feat: fix and verify GasEstimateGasLimit

- src/rpc/auth_layer.rs
- src/rpc/methods/state.rs
- src/rpc/mod.rs
- src/rpc_client/state_ops.rs
- src/tool/subcommands/api_cmd.rs
- Added `Filecoin.StateMinerSectors` rpc and test
```
forest-tool api compare forest_snapshot_calibnet_2024-04-16_height_1530489.forest.car.zst --filter Filecoin.StateMinerSectors
| Filecoin.StateMinerSectors | Valid  | Valid |
```
Closes #4194 
> Implement StateMinerSectors RPC 

- src/chain_sync/chain_muxer.rs
- src/cli/subcommands/mpool_cmd.rs
- src/cli_shared/cli/mod.rs
- src/cli_shared/mod.rs
- src/libp2p/keypair.rs
- src/message_pool/msgpool/msg_pool.rs
- src/message_pool/msgpool/test_provider.rs
- src/utils/io/mod.rs
- src/utils/tests/files.rs
- src/wallet/subcommands/wallet_cmd.rs
- random cleanups intended to reduce reallocations in our codebase
Closes
> reduce reallocations

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- `StateMinerSectors` is failing [here](https://github.com/ChainSafe/forest/actions/runs/8702364320/job/23866696397).
Closes
> blacklist StateMinerSectors

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/general_report.md
- .github/ISSUE_TEMPLATE/new_issue.md
- .github/ISSUE_TEMPLATE/task_req.md
- Use the same formatting as in PR templates
Closes
> templates uniformed

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- src/rpc/auth_layer.rs
- src/rpc/methods/state.rs
- src/rpc/mod.rs
- src/rpc/types/mod.rs
- src/rpc_client/state_ops.rs
- src/state_manager/mod.rs
- src/tool/subcommands/api_cmd.rs
- Fix the RPC method and migrate to the new RPC framework
- Fix the tests
```
| Filecoin.StateListMessages (243)                | Valid  | Valid |
```
Closes
> fix(rpc): Filecoin.StateListMessages

- src/rpc/reflect/mod.rs
- src/tool/subcommands/api_cmd.rs
- deduplicate RPC tests
Closes
> fix(test): deduplicate RPC tests

- src/cli/main.rs
- src/cli/subcommands/info_cmd.rs
- src/cli/subcommands/snapshot_cmd.rs
- src/rpc/auth_layer.rs
- src/rpc/methods/state.rs
- src/rpc/methods/state/types.rs
- src/rpc/mod.rs
- src/rpc_client/state_ops.rs
- src/state_manager/mod.rs
- src/tool/subcommands/api_cmd.rs
- src/wallet/main.rs
> refactor: migrate StateNetworkName, StateReplay to trait RpcMethod

- Cargo.lock
- bump rustls to fix cargo audit errors.
Closes
> bump rustls

- .github/workflows/docs.yml
- .github/workflows/forest.yml
- .github/workflows/release.yml
- .github/workflows/rust-lint.yml
- .github/workflows/unit-tests.yml
- Makefile
- README.md
- documentation/src/basic_usage.md
- get rid of multiple occurrences in our CI where we needlessly queried Canonical repositories - GH images are pretty self-contained and have most of the tools needed. https://github.com/actions/runner-images?tab=readme-ov-file#software-and-image-support
- removed unused dependencies
Closes
> cleanup CI dependencies

- .lycheeignore
- Adds `.lycheeignore` file to manage inaccessible links.
Closes
> [Fix] OpenRPC link check.

- src/db/gc/mod.rs
- use sequential graph traversal for now
- store/retrieve last gc epoch and use that for further runs
work on #3863 
We definitely need to debug the parallel graph traversal to see what goes wrong. 
In the meantime I have several takeaways:
- parallel graph traversal needs proper testing and fixes
- calibnet GC works, because the system requirements for calibnet nodes aren't huge. it works on a 4GB RAM node with 3GB of swap
- problems with mainnet GC likely have something to do with the fact that we consume as much as possible memory for car file indexing and the snapshot is quite big. needs to be tested
> [Fix] GC issues on calibnet.

- build/known_blocks.yaml
- Update list of known blocks.
Closes #4279 
> cron: update known blocks

- documentation/src/developer_documentation/rpc_api_compatibility.md
- added docs for miner creation that is used in RPC conformance tests.
Closes
> docs: Lotus miner creation for tests

- src/rpc/methods/state.rs
- src/shim/actors/market.rs
- src/shim/actors/market/balance_table.rs
- src/shim/actors/mod.rs
- src/shim/mod.rs
- src/state_manager/mod.rs
- src/tool/subcommands/api_cmd.rs
Part of https://github.com/ChainSafe/forest/issues/4164
- implement RPC method `Filecoin.StateMarketParticipants`
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-05-07_height_1591906.forest.car.zst --filter StateMarketParticipants`
| RPC Method                            | Forest | Lotus |
|---------------------------------------|--------|-------|
| Filecoin.StateMarketParticipants (10) | Valid  | Valid |
```
Lotus code:
```go
func (a *StateAPI) StateMarketParticipants(ctx context.Context, tsk types.TipSetKey) (map[string]api.MarketBalance, error) {
out := map[string]api.MarketBalance{}
ts, err := a.Chain.GetTipSetFromKey(ctx, tsk)
return nil, …
```
> feat(rpc): implement Filecoin.StateMarketParticipants

- build/bootstrap/calibnet
- build/bootstrap/mainnet
- calibnet nodes were decommissioned, see https://github.com/filecoin-project/lotus/pull/11672
- mainnet nodes unmaintained, see https://github.com/filecoin-project/lotus/pull/11983 and https://filecoinproject.slack.com/archives/C039RBG3RPC/p1715255422205499
Closes
> chore: remove unmaintained bootstrap nodes

- src/metrics/mod.rs
- src/rpc/methods/eth.rs
- src/rpc/methods/gas.rs
- src/rpc/methods/state.rs
- remove stale `#[allow(clippy::unused_async)]` annotations
Closes
> chore(lint): remove stale `#[allow(clippy::unused_async)]`

- CHANGELOG.md
- src/networks/butterflynet/mod.rs
- src/networks/calibnet/mod.rs
- src/networks/devnet/mod.rs
- src/networks/mainnet/mod.rs
- src/networks/mod.rs
- src/rpc/methods/state.rs
- src/shim/version.rs
- src/state_manager/circulating_supply.rs
- src/tool/subcommands/api_cmd.rs
- implemented `Filecoin.StateGetNetworkParams`,
- added missing network information so that all the data is available for that endpoint, for all supported networks,
- temporary workaround for bad Lotus behaviour until a new release, see https://github.com/filecoin-project/lotus/commit/7e005be751d3695bb05010292ed24f10c1d583bf, though we'd also need to update our proof definitions for networks so that synthetic PoRep variants are included.
Closes https://github.com/ChainSafe/forest/issues/4299
> feat: impl `Filecoin.StateGetNetworkParams`

- src/rpc/methods/eth.rs
- src/rpc/methods/eth/types.rs
- src/tool/subcommands/api_cmd.rs
- implement RPC method `Filecoin.EthGetCode`
Closes
> feat(rpc): implement Filecoin.EthGetCode

- src/blocks/tipset.rs
> [Docs] Document lazy init in Tipset/FullTipset.

- src/daemon/mod.rs
- stateless nodes don't do state migration and don't do validations, and so they don't require actor bundles and proof param files downloaded at runtime.
Closes
> chore: stateless nodes don't need bundles

- src/rpc/methods/sync.rs
- Introduces a `follow` check for SyncSubmitBlock RPC
- Introduces a `tipset channel full` check for SyncSubmitBlock RPC
Work on #4245 
> [Fix] Additional checks for Filecoin.SyncSubmitBlock.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- release Forest v0.18.0 BIG BANG!
Closes
> release: v0.18.0 BIG BANG

- documentation/src/SUMMARY.md
- documentation/src/bootstrap_node.md
- added docs for the stateless node as requested in Filecoin Slack.
Closes
> docs: stateless node

- src/rpc/auth_layer.rs
- src/rpc/methods/auth.rs
- src/rpc/methods/beacon.rs
- src/rpc/methods/chain.rs
- src/rpc/methods/common.rs
- src/rpc/methods/eth.rs
- src/rpc/methods/gas.rs
- src/rpc/methods/miner.rs
- src/rpc/methods/mpool.rs
- src/rpc/methods/msig.rs
- src/rpc/methods/net.rs
- src/rpc/methods/node.rs
- src/rpc/methods/state.rs
- src/rpc/methods/sync.rs
- src/rpc/methods/wallet.rs
- src/rpc/mod.rs
- src/rpc/reflect/mod.rs
- src/tool/subcommands/shed_cmd.rs
- Only one place to think about and document the macro
- Simpler code for OpenRPC, decoupling serving from schema generation
- Makes planned CLI tools a lot easier
Closes
> refactor: for_each_method pattern, and remove SelfDescribingRpcModule

- CHANGELOG.md
- src/rpc/methods/net.rs
- src/rpc/mod.rs
- introduced NetProtectAdd RPC endpoint
Closes #4353 
Perhaps needs a follow-up #4355 
> [Feature] NetProtectAdd RPC.

- documentation/src/bootstrap_node.md
- add disclaimer for people that want to use Forest as bootstrap node. See https://github.com/ChainSafe/forest/issues/4346
Closes
> chore: add disclaimer for bootstrap node in docs

- src/chain_sync/chain_muxer.rs
(Part of https://github.com/ChainSafe/forest/issues/4346 investigation)
In a regular(stateful) forest node, the pubsub blocks are assembled into full tipsets by bitswapping the missing messages. While in a stateless node, this logic does not add value but bloats the database and makes tons of bitswap requests. Disabling this logic could mitigate 1. database size growth  2. bitswap failures
- do not assemble Pubsub blocks into full tipsets in stateless mode
Closes
> fix(p2p): do not assemble Pubsub blocks into full tipsets in stateless mode

- build/known_blocks.yaml
- I only updated on calibnet, mainnet did not reach the 86400 epoch difference yet (it should happen around tomorrow afternoon/evening if we want to include it). I'm not sure I'll be around anymore to add it.
Closes https://github.com/ChainSafe/forest/issues/4378
> feat: update known blocks on calibnet

- src/rpc/types/deal_impl.rs
- src/rpc/types/mod.rs
- Derive `Clone` for `DealProposal` and drop the manual implementation.
Closes https://github.com/ChainSafe/fil-actor-states/issues/255
> fix: simplify Clone implementation for DealProposal

- CHANGELOG.md
- src/lotus_json/allocation.rs
- src/lotus_json/mod.rs
- src/rpc/methods/state.rs
- src/rpc/mod.rs
- src/state_manager/mod.rs
- src/tool/subcommands/api_cmd.rs
- Filecoin.StateGetAllocation RPC endpoint
Closes #4335 
> [Feature] Filecoin.StateGetAllocation RPC endpoint.

- src/rpc/methods/state.rs
- src/rpc/mod.rs
- src/shim/actors/mod.rs
- src/shim/actors/verifreg.rs
- src/shim/actors/verifreg/state.rs
- src/state_manager/mod.rs
- src/tool/subcommands/api_cmd.rs
- implement RPC method `Filecoin.StateGetAllocations`
- Fix API compare tests for `Filecoin.StateGetAllocation`
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-05_height_1675679.forest.car.zst --filter StateGetAllocation`
| RPC Method                         | Forest | Lotus |
|------------------------------------|--------|-------|
| Filecoin.StateGetAllocation (381)  | Valid  | Valid |
| Filecoin.StateGetAllocations (108) | Valid  | Valid |
```
Closes https://github.com/ChainSafe/forest/issues/4394
Closes https://github.com/ChainSafe/forest/issues/4386
> fix(rpc): implement Filecoin.StateGetAllocations

- CHANGELOG.md
- src/lotus_json/message.rs
- src/lotus_json/signed_message.rs
> Fix `SignedMessage` JSON formatting

- Cargo.lock
- src/rpc/methods/net.rs
- src/rpc/methods/state.rs
- src/rpc/mod.rs
- src/shim/actors/verifreg.rs
- src/shim/actors/verifreg/state.rs
- src/shim/state_tree.rs
- src/state_manager/mod.rs
- src/tool/subcommands/api_cmd.rs
Blocked by https://github.com/ChainSafe/fil-actor-states/pull/304
- Implement RPC method `Filecoin.StateGetClaims`
- API compare tests for `Filecoin.StateGetClaims`
- Fix API compare tests for `Filecoin.StateGetClaim`
- Fix API version constraints for some V0 methods
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-07_height_1680830.forest.car.zst --filter StateGetClaim`
| RPC Method                   | Forest | Lotus |
|------------------------------|--------|-------|
| Filecoin.StateGetClaim (78)  | Valid  | Valid |
| Filecoin.StateGetClaims (31) | Valid  | Valid |
```
Closes https://github.com/ChainSafe/forest/issues/4399
[1]: …
> feat(rpc): implement Filecoin.StateGetClaims

- src/tool/subcommands/api_cmd.rs
- API compare test for StateMarketDeals
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-12_height_1694998.forest.car.zst --filter StateMarketDeal`
| RPC Method                     | Forest | Lotus |
|--------------------------------|--------|-------|
| Filecoin.StateMarketDeals (10) | Valid  | Valid |
```
Closes
> chore(rpc): API compare test for StateMarketDeals

- src/rpc/methods/state.rs
- src/rpc/mod.rs
- src/shim/actors/miner.rs
- src/shim/actors/miner/state.rs
- src/tool/subcommands/api_cmd.rs
- implement RPC method `Filecoin.StateMinerSectorAllocated`
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-13_height_1698074.forest.car.zst --filter StateMinerSectorAllocated`
| RPC Method                               | Forest | Lotus |
|------------------------------------------|--------|-------|
| Filecoin.StateMinerSectorAllocated (130) | Valid  | Valid |
```
Closes
> feat(rpc): implement Filecoin.StateMinerSectorAllocated

- src/message/mod.rs
- src/rpc/methods/state.rs
- src/rpc/methods/state/types.rs
- src/state_manager/mod.rs
- src/tool/subcommands/api_cmd.rs
- fix RPC method `Filecoin.StateReplay`
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-14_height_1700822.forest.car.zst --filter StateReplay`
| RPC Method                | Forest | Lotus |
|---------------------------|--------|-------|
| Filecoin.StateReplay (26) | Valid  | Valid |
```
Closes
> fix(rpc): Filecoin.StateReplay

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- disabled flaky tests - failures were in https://github.com/ChainSafe/forest/actions/runs/9593268587/job/26453560366
```
2024-06-20T07:33:52.1840474Z | Filecoin.StateCall                                | CustomCheckFailed                     | Valid                                 |
2024-06-20T07:33:52.1853702Z | Filecoin.StateReplay                              | CustomCheckFailed                     | Valid   
```
[logs_25110535510.zip](https://github.com/user-attachments/files/15912665/logs_25110535510.zip)
Closes
> fix: disable StateReplay and StateCall (flaky tests)

- src/rpc/methods/gas.rs
- Demote owned object to a reference, avoiding an unnecessary clone.
Closes
> chore: avoid unnecessary clones in gas calculations

- src/rpc/methods/state.rs
- src/tool/subcommands/api_cmd.rs
Part of #4424
- cover invalid miner address case in API compare test for `Filecoin.StateSectorPreCommitInfo`
- cover invalid sector number case in API compare test for `Filecoin.StateSectorPreCommitInfo`
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-19_height_1714793.forest.car.zst --filter StateSectorPreCommitInfo`
| RPC Method                             | Forest
| Lotus                                                                                    |
|----------------------------------------|-----------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------- …
```
> fix(rpc): test coverage for StateSectorPreCommitInfo-not-found

- src/lotus_json/message.rs
Part of https://github.com/ChainSafe/forest/issues/4424
> 2) 'Message` deserialization has required fields that are optional in Lotus and default to 0 there
- Make some fields in `MessageLotusJson` optional for JSON serialization to match lotus behavior
Manual test result
Payload: 
```json
{"jsonrpc":"2.0","id":0,"method":"Filecoin.GasEstimateGasLimit","params":
[
{
"From": "f15ydyu3d65gznpp2qxwpkjsgz4waubeunn6upvla",
"To": "f15ydyu3d65gznpp2qxwpkjsgz4waubeunn6upvla",
"Value": "1000000000000000000"
},
[
{
"/": "bafy2bzacedejh3rhguvzgnt6wergwcuuecgw42kx2uxmqdwpuyzvdwjwla4wq"
},
{
"/": "bafy2bzacebp67qmhv6okvhgdtjhh4v5ewpw7ar77dfbhhmsqx2vwnkrv3is56"
},
{
"/": "bafy2bzaceciiv7y65ony3eg4h2ah5kpaiymjxmjbje62h7i77kivwufunlx7m"
}
]
]
}
```
lotus response …
> fix(rpc): make some fields of MessageLotusJson optional for deserialization

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
#4446 
- filter out failing tests for Filecoin.StateCirculatingSupply to unblock a few other PRs
Local test result on `main`
```
Request dump: Request { method_name: "Filecoin.StateCirculatingSupply", params: Array [Array [Object {"/": String("bafy2bzacecdxr5iaglcfqb3kxraibhpswlo2yhk6pfovjscyy5vtnaqbuvkig")}, Object {"/": String("bafy2bzaceabow7mgfusizsia3a7b4sql6tmg3fyracejbnpeihph2q734higo")}]], result_type: PhantomData<serde_json::value::Value>, api_version: V0, timeout: 60s }
Request params JSON: [[{"/":"bafy2bzacecdxr5iaglcfqb3kxraibhpswlo2yhk6pfovjscyy5vtnaqbuvkig"},{"/":"bafy2bzaceabow7mgfusizsia3a7b4sql6tmg3fyracejbnpeihph2q734higo"}]]
Forest response: "49004778106792872959172253"
Lotus response: "49004777084917872959172252"
Diff: …
```
> fix(rpc test): filter out failing tests for Filecoin.StateCirculatingSupply

- .config/forest.dic
- Cargo.lock
- Cargo.toml
- src/networks/mod.rs
- src/rpc/methods/eth.rs
- src/shim/address.rs
- simplify a few Display implementations with `displaydoc`
Closes
https://crates.io/crates/displaydoc
> chore: simplify a few Display implementations with displaydoc

- src/cli_shared/cli/mod.rs
- The GC is broken and should not be enabled by default.
Closes
> fix: disable the gc by default

- CHANGELOG.md
- src/rpc/methods/state.rs
- src/rpc/mod.rs
- src/shim/actors/miner.rs
- src/shim/actors/miner/state.rs
(Part of #4424)
This PR fixes `StateSectorPreCommitInfo` RPC method against the v1 spec and uses it for both v0 and v1 endpoints until #3960 is resolved. (Keeping the v0 implementation with a different name for now)
- update `StateSectorPreCommitInfo` against v1 spec
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-24_height_1729537.forest.car.zst --filter StateSectorPreCommitInfo`
| RPC Method                             | Forest
| Lotus                                                                                    |
|----------------------------------------|-----------------------------------------------------------------------------------------------------|---------------------- …
```
> fix(rpc): update StateSectorPreCommitInfo against v1 spec

- build/known_blocks.yaml
- updated known blocks
Closes https://github.com/ChainSafe/forest/issues/4458
> chore: update checkpoints

- CHANGELOG.md
- src/message/mod.rs
- src/rpc/methods/eth.rs
- src/rpc/methods/eth/types.rs
- src/rpc/mod.rs
- src/rpc/reflect/mod.rs
- src/tool/subcommands/api_cmd.rs
Note: This PR does not contain the bug fix yet https://github.com/filecoin-project/lotus/pull/12177
- implement RPC method `Filecoin.EthFeeHistory`
- fix serialization logic for null optional parameters in RPC client
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-07-03_height_1755669.forest.car.zst --filter EthFeeHis`
| RPC Method                  | Forest | Lotus |
|-----------------------------|--------|-------|
| Filecoin.EthFeeHistory (20) | Valid  | Valid |
```
Closes
Lotus code: https://github.com/filecoin-project/lotus/blob/v1.28.0-rc1/node/impl/full/eth.go#L627
> feat(rpc): implement Filecoin.EthFeeHistory

- src/tool/subcommands/api_cmd.rs
- add mpool tests with tipset
Closes
> fix(rpc test): add mpool tests with tipset

- CHANGELOG.md
- prepare release `v0.19.0` _Pastel de nata`.
Closes
> chore: prepare release v0.19.0 Pastel de nata

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
For details check out #4485
-
Closes
> fix(rpc test): disable flacky tests for MpoolSelect

- Cargo.lock
- Cargo.toml
- src/rpc/methods/eth.rs
- src/rpc/mod.rs
- src/tool/subcommands/api_cmd.rs
- Impl `Filecoin.EthGetTransactionCount` RPC and Test
```
| RPC Method                           | Forest | Lotus      |
|--------------------------------------|--------|------------|
| Filecoin.EthGetTransactionCount (10) | Valid  | Valid      |
```
Contributes to https://github.com/ChainSafe/forest/issues/4165
> feat(rpc) Filecoin.EthGetTransactionCount 

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- src/message_pool/msg_chain.rs
- src/message_pool/msgpool/provider.rs
- src/message_pool/msgpool/selection.rs
- src/rpc/methods/mpool.rs
- src/tool/subcommands/api_cmd.rs
- fix `Filecoin.MpoolSelect`
- re-enable parity tests
Manually verified with a previously failing case
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-07-05_height_1760963.forest.car.zst --filter MpoolSel`
| RPC Method                | Forest | Lotus |
|---------------------------|--------|-------|
| Filecoin.MpoolSelect (11) | Valid  | Valid |
```
Closes #4485
> fix(rpc): Filecoin.MpoolSelect and re-enable parity tests

- src/rpc/client.rs
- src/rpc/methods/auth.rs
- src/rpc/methods/beacon.rs
- src/rpc/methods/chain.rs
- src/rpc/methods/common.rs
- src/rpc/methods/eth.rs
- src/rpc/methods/gas.rs
- src/rpc/methods/miner.rs
- src/rpc/methods/mpool.rs
- src/rpc/methods/msig.rs
- src/rpc/methods/net.rs
- src/rpc/methods/node.rs
- src/rpc/methods/state.rs
- src/rpc/methods/sync.rs
- src/rpc/methods/wallet.rs
- src/rpc/mod.rs
- src/rpc/reflect/mod.rs
- src/rpc/request.rs
- src/tool/subcommands/api_cmd.rs
- src/tool/subcommands/shed_cmd.rs
- Remove `ApiVersion` and replace it with `ApiPaths`, a closed set of URLs.
- Add plumbing for filtering at the `forest-tool openrpc shed` level
- note this does NOT change how we mount and serve RPC requests
- note this does NOT change how we test RPC endpoints
- part of #3960
> feat: forest-tool openrpc shed <path>

- CHANGELOG.md
- src/rpc/methods/state.rs
- src/rpc/mod.rs
- src/shim/actors/market.rs
- src/shim/actors/market/state.rs
- src/tool/subcommands/api_cmd.rs
- implement RPC method `Filecoin.StateGetAllocationIdForPendingDeal`
- fix changelog entry position for `Filecoin.StateMinerAllocated`
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-07-11_height_1777770.forest.car.zst --filter StateGetAllocationIdForPendingDeal`
| RPC Method                                       | Forest | Lotus |
|--------------------------------------------------|--------|-------|
| Filecoin.StateGetAllocationIdForPendingDeal (40) | Valid  | Valid |
```
Closes #4508
> feat(rpc): implement Filecoin.StateGetAllocationIdForPendingDeal

- CHANGELOG.md
- src/rpc/methods/state.rs
- src/rpc/mod.rs
- src/tool/subcommands/api_cmd.rs
- implement RPC method `Filecoin.StateGetAllocationForPendingDeal`
- avoid panic in `new_eth_tx_from_signed_message` in `api_cmd`
```
| RPC Method                                     | Forest | Lotus |
|------------------------------------------------|--------|-------|
| Filecoin.StateGetAllocationForPendingDeal (40) | Valid  | Valid |
```
Closes #4507
> feat(rpc): implement Filecoin.StateGetAllocationForPendingDeal

- src/rpc/methods/eth.rs
- src/rpc/mod.rs
- src/tool/subcommands/api_cmd.rs
- Implement `Filecoin.EthGetTransactionHashByCid` RPC method 
```
| RPC Method                                      | Forest | Lotus |
|-------------------------------------------------|--------|-------|
| Filecoin.EthGetTransactionHashByCid (10)        | Valid  | Valid |
```
Contributes to https://github.com/ChainSafe/forest/issues/4165
> feat(rpc) Implement Filecoin.EthGetTransactionHashByCid

- src/db/gc/mod.rs
- src/db/memory.rs
- src/db/mod.rs
- src/db/parity_db.rs
- Report the number of rows affected by the GC.
- 
Closes
> [Enhancement] Count garbage collected rows on every GC run.

- src/rpc/methods/state.rs
- added Waffle to the `GetStateNetworkParams`
Closes
> chore: update `Filecoin.GetStateNetworkParams`

- .github/workflows/forest.yml
It should have been fixed by #4523 as well
-
Closes
> fix(ci): re-enable eth mapping check

- CHANGELOG.md
- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- src/libp2p/service.rs
- src/rpc/error.rs
- src/rpc/methods/net.rs
- src/rpc/methods/net/types.rs
- src/rpc/mod.rs
- src/tool/subcommands/api_cmd.rs
- src/utils/flume/mod.rs
- src/utils/mod.rs
- src/utils/p2p/mod.rs
- implement `Filecoin.NetFindPeer`
- fix `Filecoin.NetPeers` result to match lotus (multiaddr without p2p part)
- move `net` types to a separate file
Manual test result
forest
```json
{"jsonrpc":"2.0","id":0,"result":{"ID":"12D3KooWABQ5gTDHPWyvhJM7jPhtNwNJruzTEo32Lo4gcS5ABAMm","Addrs":["/dns/bootstrap-calibnet-0.chainsafe-fil.io/tcp/34000"]}}
```
lotus
```json
{"id":0,"jsonrpc":"2.0","result":{"ID":"12D3KooWABQ5gTDHPWyvhJM7jPhtNwNJruzTEo32Lo4gcS5ABAMm","Addrs":["/ip4/148.113.17.89/tcp/34000","/ip6/2402:1f00:8300:959::/tcp/34000"]}}
```
Closes #4562
> feat(rpc): implement Filecoin.NetFindPeer

- src/rpc/reflect/mod.rs
This might be less surprising for some users
-
Closes
> refactor(openrpc): rename Filecoin.Foo::Result -> Filecoin.Foo.Result

- Cargo.lock
- Cargo.toml
- src/tool/subcommands/api_cmd.rs
- src/tool/subcommands/shed_cmd.rs
- tests/tool_tests.rs
#4542 
```bash
#!/usr/bin/env bash
set -x
alias forest-tool=./forest/target/release/forest-tool
alias filecoin-common-node-api-tool=./filecoin-common-node-api/tool/target/release/filecoin-common-node-api-tool
alias lotus=./lotus/lotus
snapshot=./forest_snapshot_calibnet_2024-07-16_height_1794697.forest.car.zst
forest-tool api dump-tests "$snapshot" --path v1 | pv > dump-tests-v1
forest-tool api dump-tests "$snapshot" --path v0 | pv > dump-tests-v0
filecoin-common-node-api-tool json-rpc play --remote http://127.0.0.1:2345 < dump-tests-v0 | pv > play-forest-v0
filecoin-common-node-api-tool json-rpc play --remote http://127.0.0.1:1234/rpc/v0 < dump-tests-v0 | pv > play-lotus-v0
filecoin-common-node-api-tool json-rpc play --remote http://127.0.0.1:2345 < dump-tests-v1 | pv > play-forest-v1 …
```
> feat: forest-tool api dump-tests

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- how come nobody caught it :rofl: 
Closes
> fix incorrect filtering

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepare release v0.19.1
Closes
> release: prepare release v0.19.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepare release that fixes the previous one's incompatibility with Prometheus
Closes
> release: prepare release v0.19.2

- build/known_blocks.yaml
- updated known blocks.
Closes https://github.com/ChainSafe/forest/issues/4604
> chore: update known blocks

- .github/workflows/scripts-lint.yml
- monitoring/README.md
- this fixes recent issues we had with `docker-compose not found`, see https://github.com/actions/runner-images/issues/9692 for details.
Closes
> fix: migrate to docker compose v2

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- See issue: https://github.com/ChainSafe/forest/issues/4630
Closes
> fix(ci): filter out flaky `StateMinerProvingDeadline`

- src/tool/offline_server/mod.rs
- src/tool/offline_server/server.rs
- src/tool/subcommands/api_cmd.rs
- the `api_cmd.rs` is already massive, ~2k LoC, this helps a bit while making it easier for few engineers to work together without introducing massive conflicts. Plus, it's easier to reason about.
Closes
> chore: move offline RPC server to a separate file

- src/lotus_json/signature_type.rs
> fix: JsonSchema for BlsSignature

- src/tool/subcommands/snapshot_cmd.rs
-  Rename the validate command to validate-diffs and add a new validate command that checks each file separately.
example:
```bash
$ ./target/debug/forest-tool snapshot validate  test-snapshots/chain4*
Validating test-snapshots/chain4.car
Checking IPLD integrity:       ❌ Invalid IPLD data!
Error: missing key: bafy2bzacebpkfyohjp7thdmpjy44lkimctgphlxu3apnkgwtrkxy723vhbk5y
Validating test-snapshots/chain4.car.zst
Checking IPLD integrity:       ❌ Invalid IPLD data!
Error: missing key: bafy2bzacebpkfyohjp7thdmpjy44lkimctgphlxu3apnkgwtrkxy723vhbk5y
Validating test-snapshots/chain4.forest.car.zst
Checking IPLD integrity:       ❌ Invalid IPLD data!
Error: missing key: bafy2bzacebpkfyohjp7thdmpjy44lkimctgphlxu3apnkgwtrkxy723vhbk5y
Error: validate failed …
```
> snapshot validate each file separately

- src/rpc/error.rs
- src/rpc/methods/net.rs
As per https://github.com/ChainSafe/forest/issues/4528#issuecomment-2284051504
> feat: stub NetProtectList and NetProtectRemove

- src/rpc/methods/chain.rs
- src/rpc/methods/chain/types.rs
- src/rpc/methods/misc.rs
- src/rpc/mod.rs
- src/rpc/types/mod.rs
Per https://github.com/ChainSafe/forest/issues/4528#issuecomment-2284051504
> feat: stub GetActorEventsRaw and ChainGetEvents

- f3-sidecar/README.md
This PR adds a mermaid diagram on how F3 sidecar interacts with Forest.
To preview the diagram: https://github.com/ChainSafe/forest/blob/hm/f3-doc/f3-sidecar/README.md
-
Closes
> doc: how F3 sidecar interact with forest

- CHANGELOG.md
- Dockerfile
- Dockerfile-alpine
- documentation/src/docker.md
- scripts/devnet/docker-compose.yml
- make the default docker user `root`,
- added additional check for `forest-wallet` in the Dockerfiles
Closes https://github.com/ChainSafe/forest/issues/4672
> feat: root as default docker user

- Dockerfile
- f3-sidecar/Dockerfile
- scripts/devnet/lotus.dockerfile
Reverts ChainSafe/forest#4731
https://github.com/ChainSafe/forest/actions/runs/10734792180/job/29770709671
> Revert "chore(docker): use ubuntu:24.04 in forest dockerfiles"

- Dockerfile
Use upstream xx in Dockerfile since rate limit is no longer a problem, *likely*.
-
Closes
> chore: use upstream xx in Dockerfile

- scripts/tests/api_compare/filter-list-offline
- src/libp2p/service.rs
- src/rpc/methods/f3.rs
- src/rpc/methods/net.rs
- src/tool/subcommands/api_cmd.rs
- impl Filecoin.NetProtectAdd and NetProtectRemove
- removes `#[allow(dead_code)]` from https://github.com/ChainSafe/forest/pull/4742/files#diff-4c7830ac5276b0c3eac19556e3ef6814eff768b6af5d52682a1bc772af1d870cR352
- api compare tests
Closes #4753
> feat(rpc): impl Filecoin.NetProtectAdd and NetProtectRemove

- CHANGELOG.md
- src/rpc/methods/eth.rs
- src/rpc/methods/eth/filter/event.rs
- src/rpc/methods/eth/filter/mempool.rs
- src/rpc/methods/eth/filter/mod.rs
- src/rpc/methods/eth/filter/store.rs
- src/rpc/methods/eth/filter/tipset.rs
- src/rpc/mod.rs
- src/tool/subcommands/api_cmd.rs
- Implement `EthUninstallFilter` with alias `eth_uninstallFilter` and test.
```
| RPC Method          | Forest | Lotus |
|---------------------|--------|-------|
| eth_uninstallFilter | Valid  | Valid |
```
Closes #4668 
> feat(rpc): Implement EthUninstallFilter

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepared the "Brexit" release commemorating @aatifsyed 
Closes
> chore: prepare release 0.20.0 "Brexit"

- .github/PULL_REQUEST_TEMPLATE.md
- added mention to the docs standard in Notion. If need be (aka we have more than one external contributor per quarter), we can later make it public by putting said document in GH.
Closes
> chore: add docs practices mention in the checklist

- f3-sidecar/Dockerfile
- f3-sidecar/api.go
- f3-sidecar/ec.go
- f3-sidecar/ec_test.go
- f3-sidecar/go.mod
- f3-sidecar/go.sum
- go.work
- go.work.sum
- interop-tests/README.md
- interop-tests/src/tests/go_app/go.mod
- src/rpc/methods/f3.rs
- src/rpc/mod.rs
Part of https://github.com/ChainSafe/forest/issues/4775
- upgrade `go-f3` to v0.3.0 in `f3-sidecar`
- upgrade go compiler to 1.22 which is required by `go-f3`: https://github.com/filecoin-project/go-f3/pull/581/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3
- add a blank implementation for `Finalize`
CI log https://github.com/ChainSafe/forest/actions/runs/10935137803/job/30356509181?pr=4776#step:8:575
```
2024-09-19T05:52:20.562Z	INFO	f3	go-f3@v0.3.0/host.go:662	reached a decision	{"instance": 10, "ecHeadEpoch": 19}
2024-09-19T05:52:20.572Z	INFO	f3	go-f3@v0.3.0/host.go:284	backing off for: 47.12s
2024-09-19T05:52:20.610Z	INFO	f3	go-f3@v0.3.0/host.go:662	reached a decision	{"instance": 11, "ecHeadEpoch": 23} …
```
> chore(f3): upgrade `go-f3` to 0.3.0

- README.md
to unblock CI https://github.com/ChainSafe/forest/actions/runs/11003593316/job/30552913544#step:5:79
-
Closes
> fix: deadlinks in REAME.md

- scripts/tests/calibnet_wallet_check.sh
- src/rpc/methods/state.rs
- src/tool/subcommands/api_cmd.rs
- update RPC method `Filecoin.StateSearchMsg` to be V1-compatible
- update API compare tests accordingly
- update wallet test script accordingly
Closes #4767
> fix(rpc): update Filecoin.StateSearchMsg to be V1-compatible

- .github/CHECKPOINT_ISSUE_TEMPLATE.md
- updated label of the checkpoint template to our new set of labels.
Closes
> chore: update checkpoint template labels

- Makefile
- cleaned up the Makefile a bit out of unused/non-relevant rules.
Closes
> chore: cleanup makefile

- .github/workflows/scripts-lint.yml
- scripts/devnet-curio/lotus.dockerfile
- scripts/devnet/lotus.dockerfile
- added our other images to the CI linter and fixed reported issues.
Closes
> chore: include script images in linters

- .github/workflows/docs.yml
- CHANGELOG.md
- README.md
- the workflow was broken, see https://github.com/ChainSafe/forest/actions/runs/11178236397
- fixed it + fixed offenses
Closes
> fix: docs workflow

- CHANGELOG.md
- f3-sidecar/api.go
- src/rpc/methods/f3.rs
- src/rpc/mod.rs
- implement `Filecoin.F3IsRunning`
- manual testing (API compare tests will come later once F3 is enabled by default in Lotus)
Closes #4864
> feat(rpc): Filecoin.F3IsRunning

- f3-sidecar/run.go
- CatchUpAlignment setup for f3 sidecar
Closes https://github.com/ChainSafe/forest/issues/4863
> chore: setup CatchUpAlignment for f3-sidecar

- Cargo.toml
- added `thin` LTO to regular release builds,
- added `release-lto-fat` profile 
Closes
See the discussion: https://github.com/ChainSafe/forest/discussions/4858
> chore: add LTO to release builds + fat LTO profile

- build/bootstrap/butterflynet
- src/networks/butterflynet/mod.rs
- src/state_migration/mod.rs
- update butterflynet assets
Closes https://github.com/ChainSafe/forest/issues/4799
> feat: Butterflynet update

- src/f3/mod.rs
The default values of F3 manifest server in chain config may not work or not be needed. We should be able to unset the server config and use static F3 manifest by setting FOREST_F3_MANIFEST_SERVER=""
- unset F3 manifest server by setting FOREST_F3_MANIFEST_SERVER=""
- update unit test
Closes
> fix(f3): allow unsetting manifest server with FOREST_F3_MANIFEST_SERVER=""

- src/rpc/methods/eth.rs
- src/rpc/methods/eth/types.rs
- src/tool/subcommands/api_cmd.rs
- Rename `Int64` and `Uint64` to `EthInt64` and `EthUint64`, respectively
This should help move forward with the issue https://github.com/ChainSafe/filecoin-common-node-api/issues/21
Closes
> Rename `Int64` and `Uint64` to `EthInt64` and `EthUint64`, respectively

- scripts/tests/api_compare/.env
- scripts/tests/bootstrapper/.env
- scripts/tests/snapshot_parity/.env
This reverts commit 94dabc64a6809bd521bc4ba94dc51d5c921c4d7c.
- it appears the Lotus bump introduced some in-correctness in results of `StateMinerPreCommitDepositForPower`. I'll investigate it more. For the moment, let's omit that RC to avoid flakiness in CI. https://github.com/ChainSafe/forest/issues/4879
Closes
> Revert "[automated] Update Lotus version in API tests (#4866)"

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- see https://github.com/ChainSafe/forest/issues/4890
Closes 
> fix: disable flaky `StateMinerInitialPledgeCollateral`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- apply the weight calculation fix to resolve `StateMinerInitialPledgeCollateral` intermittent errors. https://github.com/ChainSafe/fil-actor-states/pull/337
Closes https://github.com/ChainSafe/forest/issues/4890
> fix: pull weight calculation fix

- f3-sidecar/README.md
- f3-sidecar/ec.go
- f3-sidecar/ec_test.go
- f3-sidecar/ffi_gen.go
- f3-sidecar/ffi_impl.go
- f3-sidecar/main.go
- f3-sidecar/run.go
- src/daemon/mod.rs
- src/f3/go_ffi.rs
- src/f3/mod.rs
- src/rpc/methods/f3.rs
- set permissions for F3.Finalize and F3.Sign to WRITE and SIGN respectively
- pass JWT token to F3 sidecar
- add JWT handling logic to F3 sidecar
- update docs
Closes #4901
> fix(f3): handle jwt properly in f3 sidecar and set proper permissions for F3.* RPC methods

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
-prepare v0.21.0 "Songthaew"
Closes
> release: prepare v0.21.0 "Songthaew"

- rust-toolchain.toml
> chore: upgrade rust toolchain to 1.82.0

- CHANGELOG.md
- src/daemon/mod.rs
- Garbage collection is broken. Disable until fixed.
Closes
> temp fix: disable the garbage collector

- CHANGELOG.md
- src/rpc/methods/eth.rs
- Fix `Filecoin.EthBlockNumber` method return type
Closes
> Fix `Filecoin.EthBlockNumber` method return type

- src/rpc/methods/f3.rs
This PR makes a performance optimization for F3 late participation scenarios where F3 catches up from scratch and tries to finalize tipsets that are too old.
- skip finalizing chain head when the finalized tipset is too old
Closes
> fix(f3): skip finalizing chain head when the finalized tipset is too old

- f3-sidecar/ffi_impl.go
This PR sets `f3` log level to WARN to suppress noises. We could change it back to INFO if https://github.com/filecoin-project/go-f3/pull/724 is accepted and released.
-
Closes
> fix(f3): suppress INFO logs under f3 to reduce noises

- f3-sidecar/run.go
This PR ports https://github.com/filecoin-project/lotus/pull/12648/files to Forest
-
Closes #4944
> fix(f3): Change the F3 HeadLookback parameter to 4

- FUNDING.json
- added ChainSafe's Filecoin funding address for the RetroPGF
- https://docs.drips.network/get-support/claim-your-repository/#how-drips-manages-project-access
Closes
> chore: add FUNDING.json for drips

- CHANGELOG.md
- src/blocks/tipset.rs
- src/cid_collections/small_cid_vec.rs
- src/cli/subcommands/f3_cmd.rs
- src/rpc/methods/f3.rs
- src/rpc/methods/f3/types.rs
- templates/cli/f3/certificate.stpl
Part of #4934
-
Forest output:
```
➜  lotus git:(master) ✗ forest-cli f3 certs get 1
Instance:     1
Power Table:
Next:       bafy2bzaceab236vmmb3n4q4tkvua2n4dphcbzzxerxuey3mot4g3cov5j3r2c
Delta:      None
Finalized Chain:
Length:     100
Epochs:     2080774-2080875
Chain:
├──2080774 (length: 4): [bafy2bzacedkl7pbti6lapivwkuhtspffsts2axnkcamatkmkclfk63ay2nzo4, bafy2bzacedh2x5sftutfzv26jmn227pmqh4uotgd23xmkjmz266qoblsgom3e, ...]
├──2080775 (length: 3): [bafy2bzacearf6rm6gw6l6msik7rsshkmqovtq3kw3o5lhqesbff3f46bcpjes, bafy2bzacebu6nrrwuej2qzjxbsgzomojfchsu3utaxobuoulf3mcc6fdx5mlo, ...]
├──2080776 (length: 1): [bafy2bzacecinm7enz5o6oemtw7b33m6xwyjsqk2gnmnvz3kz2bqaxkkozfl7c]
├──2080777 (length: 1): …
```
> feat(cli): forest-cli f3 certs get

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- Adds several methods affected by #4968 to api tests ignore list
Closes
> temp fix: ignore failing RPC tests

- CHANGELOG.md
- build/manifest.json
- src/networks/actors_bundle.rs
- src/networks/mainnet/mod.rs
- src/state_migration/mod.rs
- added support for Tuk Tuk for mainnet
```
2024-11-07T12:24:40.967+0100    WARN    statemgr        stmgr/forks.go:211      COMPLETED migration     {"height": "4413260", "from": "bafy2bzacebt7gq4niq7nrjx2qkgvjdggq7o6lgf2hu2gwmpf3fb2cgyxs2glk", "to": "bafy2bzacecafy5oatpx4kinynu76sgcrjx2wym5y3opzirgqo62mksu4cdwcm", "duration": 48.300762845}
2024-11-07T10:51:02.824427Z  INFO compute_tipset_state_blocking: forest_filecoin::state_migration: State migration at height TukTuk(epoch 4413260) was successful, Previous state: bafy2bzacebt7gq4niq7nrjx2qkgvjdggq7o6
lgf2hu2gwmpf3fb2cgyxs2glk, new state: bafy2bzacecafy5oatpx4kinynu76sgcrjx2wym5y3opzirgqo62mksu4cdwcm, new state actors: bafy2bzacedbt6jrwgw43h7ugue37hqvyr77zbl7dqtecfddhkvcxti5hfqbzy. Took: …
```
> feat: tuktuk support for mainnet

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepared Forest v0.22.0 "Pad Thai" release, which is @hanabi1224's favourite Thai dish. 
Closes
> release: prepare Forest v0.22.0 "Pad Thai"

- .cargo/audit.toml
- Cargo.lock
- Cargo.toml
- Fixes audit problems due to an unmaintained dependency of indicatif
Closes
> fix: update indicatif

- CHANGELOG.md
- src/rpc/methods/eth.rs
- src/rpc/mod.rs
- src/tool/subcommands/api_cmd.rs
- Implement `EthGetTransactionReceiptLimited` method
Closes https://github.com/ChainSafe/forest/issues/4704
> feat(rpc) Implement `Filecoin.EthGetTransactionReceiptLimited`

- CHANGELOG.md
- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- src/rpc/methods/eth.rs
- src/rpc/methods/eth/filter/mod.rs
- Fix the `logs` member in `EthTxReceipt` that was initialized with a default value.
- Remove `Filecoin.EthGetTransactionReceipt` from the filter lists
Closes
> Add logs to EthTxReceipt

- Cargo.lock
https://github.com/ChainSafe/forest/actions/runs/12008829969/job/33472291576#step:7:46
```
Crate:     rustls
Version:   0.23.16
Title:     rustls network-reachable panic in `Acceptor::accept`
error: 1 vulnerability found!
Date:      2024-11-22
ID:        RUSTSEC-2024-0399
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0399
Solution:  Upgrade to >=0.23.18
```
Closes
> fix: RUSTSEC-2024-0399

- src/rpc/methods/f3.rs
This PR demotes log level of `F3 finalized tsk ... at epoch ...` to DEBUG to reduce stdout noices
-
Closes
> fix(f3): demote F3.Finalize log level to DEBUG

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
Disable flaky tests until https://github.com/ChainSafe/forest/issues/4996 is resolved.
-
Closes
> fix: disable flaky RPC tests

- scripts/tests/api_compare/docker-compose.yml
Currently, the `dump Docker logs` step in API compare CI job takes ~5min, and most of the logs are DEBUG like below. This PR tries to suppress these debug logs to speed up the CI job and reduce noices in the log ouput.
(With this change, the `dump Docker logs` step now takes ~5s)
```
2024-11-25T07:34:18.4429443Z 2024-11-25T07:22:13.595288Z DEBUG forest_filecoin::rpc::auth_layer: Decoded JWT Claims: read,write,sign,admin
2024-11-25T07:34:18.4430327Z 2024-11-25T07:22:13.595396Z DEBUG forest_filecoin::rpc::log_layer: RPC#57bb04 OK: F3.GetParent. Took 98.814µs
2024-11-25T07:34:18.4432999Z 2024-11-25T07:22:13.595988Z DEBUG forest_filecoin::rpc::auth_layer: JWT from HTTP Header: ***
2024-11-25T07:34:18.4434140Z 2024-11-25T07:22:13.596058Z DEBUG forest_filecoin::rpc::auth_layer: Decoded JWT …
```
> fix(ci): adjust forest log level in API compare tests

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
> fix: disable flaky RPC test

- src/cli/subcommands/f3_cmd.rs
- src/rpc/methods/f3.rs
Closes #4993
- impl `forest-cli f3 powertable get`
Lotus output:
```
➜  lotus git:(master) lotus f3 pt g 39700
{
"Instance": 39700,
"FromEC": false,
"PowerTable": {
"CID": "bafy2bzacebizusujrnxrhj5jwvbj7b2zv4buypxuc23rho4jllgdjzigglfw6",
"Entries": [
{
"ID": 17387,
"Power": "952541588226048",
"PubKey": "shWKOAuULgme5MdSKSHWOFmOu0h/l8XV7Qaim6R/YgUTMW96WWsKTVr/c0MnXCEv"
},
{
"ID": 138097,
"Power": "839889444667392",
"PubKey": "rtueHy9OIKamMnuRNrhHKxbx9WzsK22TQaEql9yQo56T8Ca67+6gm3UH478fxwmB"
},
{
"ID": 143103,
"Power": "477084967239680",
"PubKey": "jML8VZM8BBPnY7Y7ELExs+U/V4guDHkjHeCtoyJ+Ae2BfWieMVCHQXCkova1kM2T"
},
{
"ID": 4040,
"Power": "275702540664832",
"PubKey": "ipsAUF/twU7d5SJ46iKfT+kegIkPX4lRIAZj5B+ANJhvVv/Vk/TmqaKCqB7439wc"
},
{
"ID": 95029, …
```
> feat(f3): impl `forest-cli f3 powertable get`

- .github/workflows/lotus-api-bump.yml
The current script does not update Lotus image to the stable version when it's currently on RC
https://github.com/ChainSafe/forest/actions/runs/12119378584/job/33785824131#step:3:18
> Lotus version is already up to date
with the fix
https://github.com/ChainSafe/forest/actions/runs/12119629769/job/33786601972#step:3:18
> Updating Lotus version to v1.31.0
-
Closes
> fix(ci): fix lotus api bump job

- CHANGELOG.md
- src/cli/subcommands/f3_cmd.rs
- implement `forest-cli f3 powertable get-proportion`
Lotus output:
```
➜  lotus git:(master) lotus f3 pt gp 1179 1167
{
"Instance": 43254,
"FromEC": false,
"PowerTable": {
"CID": "bafy2bzacebf32gcvjz7qy65yz634ekyng5hknegnytda7z6wfm5seoaqebbj4",
"ScaledTotal": 65524
},
"ScaledSum": 15,
"Proportion": 0.0002289237531286246
}
```
Forest output:
```
➜  lotus git:(master) forest-cli f3 pt gp 1179 1167
{
"Instance": 43254,
"FromEC": false,
"PowerTable": {
"CID": "bafy2bzacebf32gcvjz7qy65yz634ekyng5hknegnytda7z6wfm5seoaqebbj4",
"ScaledTotal": 65524
},
"ScaledSum": 15,
"Proportion": 0.0002289237531286246
}
```
Closes #4994
> feat(cli): forest-cli f3 powertable get-proportion

- src/libp2p/hello/behaviour.rs
- src/libp2p_bitswap/request_manager.rs
To address https://github.com/ChainSafe/forest/discussions/5004
- demote some WARN logs to DEBUG a reduce noises
Closes
> fix(log): demote some WARN logs to DEBUG to reduce noises

- src/cli/subcommands/f3_cmd.rs
The current `f3 power-table` subcommand has an unexpected `-`. Update to align with Lotus
(Skipping changelog as the existing entries use the desired name)
-
```
➜  lotus git:(master) lotus f3
NAME:
lotus f3 - Manages Filecoin Fast Finality (F3) interactions
USAGE:
lotus f3 command [command options] [arguments...]
COMMANDS:
list-miners, lm  Lists the miners that currently participate in F3 via this node.
powertable, pt
certs, c         Manages interactions with F3 finality certificates.
manifest         Gets the current manifest used by F3.
status           Checks the F3 status.
help, h          Shows a list of commands or help for one command
OPTIONS:
--help, -h  show help
➜  lotus git:(master) forest-cli f3
Manages Filecoin Fast Finality (F3) …
```
> fix(cli): update forest-cli f3 powertable subcommand name to align with lotus

- CHANGELOG.md
- build/manifest.json
- src/networks/actors_bundle.rs
- src/networks/calibnet/mod.rs
- src/state_migration/mod.rs
- support NV25 migration for calibration network.
Arbitrary epoch test:
```
2024-12-09T14:47:22.940129Z  INFO compute_tipset_state_blocking: forest_filecoin::state_migration: State migration at height Teep(epoch 2214100) was successful, Previous state: bafy2bzacectrvm6p4uzz4j6ta3rrbfs2gzjxgzneivw7cqrrnjnsdfaeadzv4, new state: bafy2bzacea4kiuxij6xbwgn4uc6lczj6qmvxhl6oz52oxq6fy2wxpyacw3fv2, new state actors: bafy2bzacebgpvvh4w6l7zqbybyo53rmuc6sudysfe72pz4fc6n2md4k57gtzc. Took: 0.956676s.
```
```
2024-12-09T15:49:03.662+0100    WARN    statemgr        stmgr/forks.go:211      COMPLETED migration     {"height": "2214100", "from": "bafy2bzacectrvm6p4uzz4j6ta3rrbfs2gzjxgzneivw7cqrrnjnsdfaeadzv4", "to": …
```
> feat: support v25 for calibnet

- Cargo.lock
- Cargo.toml
- src/libp2p/discovery.rs
Part of #5058
- upgrade `hickory-resolver` in Forest
Closes
> chore(deps): upgrade hickory-resolver

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepared release _Saenchai_ for NV25 upgrade for calibnet
Closes
> release: v0.23.0 Saenchai

- src/shim/actors/builtin/market/mod.rs
- src/shim/actors/builtin/reward/mod.rs
- Moved additional methods in `fil_actors_states` to `shim/actors`
Contributes to [#338](https://github.com/ChainSafe/fil-actor-states/issues/338)
> Move extra methods from actor states

- Cargo.lock
- deny.toml
- upgrade `idna`
- update `deny.toml`
Closes #5058
> fix: RUSTSEC-2024-0421

- .github/workflows/docker.yml
- .github/workflows/forest.yml
- .github/workflows/rust-lint.yml
- .github/workflows/unit-tests.yml
- Skip tests/checks/docker if only files in `docs/` have changed
- Only run code linters if Rust files are changed
Note: I believe this closes #4721. Please consider any other changes that might be relevant and not addressed in this PR.
Closes #4721 
> Specify paths for GHA

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
Related to https://github.com/ChainSafe/forest/issues/5085
- ignore Filecoin.StateMarketDeals
Closes
> fix(ci): ignore Filecoin.StateMarketDeals to unblock CI

- .github/dependabot.yml
- Adds `npm`/`yarn` ecosystem check for `docs/` directory
Related to #5045 
> Add dependabot config for docs

- .github/workflows/docs-deploy.yml
- Adds previous docs deployment workflow
- Migrates from `pages-action` to `wrangler-action` (see [deprecation notice](https://github.com/marketplace/actions/cloudflare-pages-github-action))
Related to #5045 
> Add docs deployment workflow

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- Add `Filecoin.StateMinerSectors` to filter lists
Closes
> Add Filecoin.StateMinerSectors to filter lists

- .github/workflows/forest.yml
- created an umbrella job for all ITGs so that we can assert that they pass in other places (GH required jobs, overrides in https://github.com/ChainSafe/forest/pull/5118) without too much repetition. It will also ease up adding new required integration tests without intervention from repo admins.
Closes
> chore: umbrella job for all ITGs

- rust-toolchain.toml
- took away Hailong's job
Closes
> chore: bumped rust toolchain

- .github/workflows/docs-auto-update.yml
- fixes silly bug in doc updates
Closes
> fix: invalid docs script directory

- docs/docs/users/reference/cli.md
- Updates Forest CLI docs to the latest commit in the `main` branch.
> [automated] Update Forest CLI docs

- src/chain_sync/chain_muxer.rs
- Split `process_gossipsub_event` into `inc_gossipsub_event_metrics`, `upd_peer_information`, `get_gossipsub_tipset`, and `shallow_validate_tipset`.
Part of #5160
> refactor: split gossipsub event function into four smaller functions

- docs/docs/users/openrpc.json
- I removed some methods that were crashing the docs; see https://github.com/ChainSafe/forest/issues/5159. This is a workaround. Hopefully, it will be temporary.
Closes
> fix: removed crashing methods from doc spec

- build/manifest.json
- scripts/devnet/.env
- scripts/devnet/lotus.dockerfile
- src/networks/actors_bundle.rs
- src/networks/devnet/mod.rs
- current NV25 bundle is in place and changed Lotus to a compatible branch in devnet checks
State migration PR will follow once Lotus has this implemented and made it available on a branch.
Closes
> feat: update actors for NV25 (devnet)

- .config/lychee.toml
- added ignores to sites that introduce bot prevention (which lychee essentially is)
Closes
> fix: fix lychee link checker fiascos

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- `Filecoin.EthGetLogs` is failing in https://github.com/ChainSafe/forest/actions/runs/13056003783/job/36427606647?pr=5206 after https://github.com/ChainSafe/forest/pull/5185. Adding to ignored for now and opening https://github.com/ChainSafe/forest/issues/5213
Closes
> fix: add `Filecoin.EthGetLogs` to ignored

- scripts/devnet/.env
- scripts/devnet/lotus.dockerfile
- src/state_migration/nv25/evm.rs
- src/state_migration/nv25/migration.rs
- src/state_migration/nv25/mod.rs
- implemented state migration for FIP-0097
Closes https://github.com/ChainSafe/forest/issues/5187
> feat: FIP-0097 state migration for NV25

- scripts/tests/api_compare/filter-list
- Fix incorrect merge from #5205
Closes
> Remove `Filecoin.StateReplay` from filter-list

- .github/workflows/checkpoints.yml
- .github/workflows/docker-latest-tag.yml
- .github/workflows/dockerfile-check.yml
- .github/workflows/docs-auto-update.yml
- .github/workflows/docs-check.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/docs-required-override.yml
- .github/workflows/link-check.yml
- .github/workflows/lotus-api-bump.yml
- .github/workflows/rpc_test_repeat.yml
- .github/workflows/rust-lint.yml
- .github/workflows/scripts-lint.yml
- .github/workflows/unit-tests.yml
- Makefile
- ARM-powered workers are [cheaper](https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-actions/about-billing-for-github-actions) and supposedly more performant. Even if the latter is exaggerated (some sources say it's 40% faster), paying less is also okay.
- we got rid of buildjet!
Closes
> chore: use more ARM-powered workers

- build/bootstrap/mainnet
- update the mainnet nodes list, see the corresponding Lotus PR https://github.com/filecoin-project/lotus/pull/12792
Closes
> chore: add magik bootstrap nodes (mainnet)

- .github/workflows/link-check.yml
- I added the support for ARM runners in https://github.com/lycheeverse/lychee-action/pull/273, so we should be good now.
Closes
> chore: arm for link check

- .github/workflows/butterflynet.yml
- scripts/tests/butterflynet_check.sh
Once the workflow lands on `main` branch, it could be manually triggered against dev branches to test butterflynet reset. 
An example run: https://github.com/ChainSafe/forest/actions/runs/13171927734/job/36763721375?pr=5245
-
Closes
> feat(ci): on-demand CI job for testing butterflynet reset branches

- Cargo.lock
- Cargo.toml
- f3-sidecar/ffi_gen.go
- f3-sidecar/ffi_impl.go
- f3-sidecar/go.mod
- f3-sidecar/go.sum
- interop-tests/src/tests/go_app/bitswap_impl.go
- interop-tests/src/tests/go_app/go.mod
- interop-tests/src/tests/go_app/go.sum
- interop-tests/src/tests/go_app/kad_impl.go
- upgrade `rust2go` to `v0.4`
Closes
> chore(deps): bump rust2go

- CHANGELOG.md
- src/rpc/methods/eth.rs
- src/rpc/methods/eth/trace.rs
- src/rpc/methods/eth/types.rs
- src/rpc/mod.rs
- src/tool/subcommands/api_cmd.rs
- Adds `EthTraceReplayBlockTransactions` RPC 
- Create `EthTrace` struct to hold common fields between `EthTraceReplayBlockTransactions` and `EthTraceBlock`
- Exposes `EthTraceReplayBlockTransactions` API
Closes: #4709 
> feat(api): add EthTraceReplayBlockTransactions RPC

- scripts/tests/api_compare/filter-list-offline
- Remove `eth_estimateGas` method from filter offline list
Closes #4555
> Remove method from filter offline list

- .github/workflows/butterflynet.yml
- .github/workflows/checkpoints.yml
- .github/workflows/docker-latest-tag.yml
- .github/workflows/dockerfile-check.yml
- .github/workflows/docs-auto-update.yml
- .github/workflows/docs-check.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/docs-required-override.yml
- .github/workflows/link-check.yml
- .github/workflows/lotus-api-bump.yml
- .github/workflows/rpc_test_repeat.yml
- .github/workflows/rust-lint.yml
- .github/workflows/scripts-lint.yml
- .github/workflows/unit-tests.yml
- following on suggestion from a PM @ Github https://github.com/orgs/community/discussions/148648#discussioncomment-12099312
Closes
> fix: downgrade ARM runners to ubuntu-22.04

- CHANGELOG.md
- scripts/tests/calibnet_wallet_check.sh
- fixed a breaking change introduced in https://github.com/ChainSafe/forest/pull/5277. Wallet tests are not run for external contributors, so it was not caught in the CI.
Closes
> fix: breaking wallet usage

- src/rpc/methods/gas.rs
- src/rpc/methods/net.rs
- src/rpc/methods/state.rs
- fixed naming of some RPC method params, mostly converted from snake_case to camelCase for consistency.
Closes #5280
> fix(rpc): verify and adjust common node API parameter names 2/4

- src/rpc/methods/state.rs
- src/rpc/methods/sync.rs
- fixed naming of some RPC method params, mostly converted from `snake_case` to `camelCase` for consistency.
Closes https://github.com/ChainSafe/forest/issues/5281
> chore: correct CNA method names 3/4

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- src/tool/subcommands/api_cmd.rs
- added a test for `mpoolgetnonce`. Previous issues might have come from using an ever-changing address. If this happens again, we'll revisit it.
Closes https://github.com/ChainSafe/forest/issues/5149
I'll move test cases into a separate file in a follow-up PR, so the introduced constant will have less information leakage.
> fix: MpoolGetNonce test

- src/tool/subcommands/api_cmd/api_compare_tests.rs
- it seems code formatting (more precisely, `all lint checks` was not a required check. I'll make it required in a follow-up (we need docs workaround for this).
Closes
> fix: format code

- README.md
- the Forest channel was archived, and we don't use Discord for comms
Closes
> chore: remove discord link

- .github/workflows/butterflynet.yml
- .github/workflows/checkpoints.yml
- .github/workflows/docker-latest-tag.yml
- .github/workflows/dockerfile-check.yml
- .github/workflows/docs-auto-update.yml
- .github/workflows/docs-check.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/docs-required-override.yml
- .github/workflows/link-check.yml
- .github/workflows/lotus-api-bump.yml
- .github/workflows/rpc_test_repeat.yml
- .github/workflows/rust-lint.yml
- .github/workflows/scripts-lint.yml
- .github/workflows/unit-tests.yml
- based on https://github.com/orgs/community/discussions/148648#discussioncomment-12205917, the issue with checkout errors on `ubuntu-24.04-arm` should be gone now. If not, we'll revert.
Closes
> chore: upgrade arm workers to ubuntu 24.04

- CHANGELOG.md
- src/db/memory.rs
- src/tool/subcommands/api_cmd.rs
- src/tool/subcommands/api_cmd/generate_test_snapshot.rs
- src/tool/subcommands/api_cmd/test_snapshot.rs
- src/tool/subcommands/api_cmd/test_snapshots.txt
- Extend RPC test snapshots to support Eth methods that require an index
- Backfill db with index data if present in `.rpcsnap.json` files
```bash
$ ./forest-tool api test testsnap/filecoin_ethgetbalance_1740048634847419.rpcsnap.json
2025-02-20T13:51:19.372028Z  INFO forest::genesis: Initialized genesis: bafy2bzacecyaggy24wol5ruvs6qm73gjibs2l2iyhcqmvi7r7a4ph7zx3yqd4
Running RPC test with snapshot testsnap/filecoin_ethgetbalance_1740048634847419.rpcsnap.json ...  Succeeded
```
Closes #5293
> Add support for writing eth mappings in .rcpsnap.json file

- src/daemon/mod.rs
Explicitly set heaviest tipset in case HEAD_KEY has already been set in the current setting store, e.g. importing a new snapshot to an existing Forest node database
- 
Closes
> fix: explicitly set heaviest tipset after importing a snapshot

- CHANGELOG.md
- src/rpc/methods/eth.rs
- switched all parameters in the Eth API to _camelCase_, as outlined in the linked issue.
Part of https://github.com/ChainSafe/forest/issues/5312
> chore: eth param names in camelCase

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepare Treebeard :deciduous_tree: :mage_man: 
Closes
> chore: prepare 0.24.0 release

- docs/docs/users/knowledge_base/snapshot_service.md
- fixes:
```
* [404] [https://docs.rs/forest-filecoin/latest/forest_filecoin/db/car/forest/index.html](https://docs.rs/forest-filecoin/latest/forest_filecoin/db/car/forest/index.html) | Network error: Not Found
```
Closes
> fix: fix link due to package name change

- deny.toml
- fixes https://github.com/ChainSafe/forest/actions/runs/13716815884/job/38363288062
- we'll probably need a libp2p update (once it's there) to resolve this...
Closes
> fix(ci): ignore `ring` RUSTSEC-2025-0009

- CHANGELOG.md
- src/rpc/methods/eth.rs
- src/tool/subcommands/api_cmd.rs
- src/tool/subcommands/api_cmd/api_compare_tests.rs
- src/tool/subcommands/api_cmd/generate_test_snapshot.rs
- src/tool/subcommands/api_cmd/test_snapshot.rs
- src/tool/subcommands/api_cmd/test_snapshots.txt
- src/utils/rand/mod.rs
- the implementation is more in accordance with the Lotus one (and Geth one for that matter), and it should be relatively fast (~4ms on my machine, about the same as Lotus). There's still some room for improvement in the internal methods, but it should be good enough for now.
- allow for the result between Lotus and Forest to mismatch in the test snapshot generation tool.
Closes https://github.com/ChainSafe/forest/issues/5356
> fix: ethgasprice faster & better

- src/chain/store/errors.rs
- src/state_manager/circulating_supply.rs
- src/state_manager/mod.rs
- src/state_manager/utils.rs
- reduce `to_string`, `to_owned` boilerplate via static method.
Closes https://github.com/ChainSafe/forest/issues/3880
> chore: reduce error state boilerplate

- deny.toml
- this should make this file more readable. If in doubt, one should go to the `cargo deny` docs.
Closes
> chore: remove template entries that are not used

- docs/dictionary.txt
- docs/docs/users/guides/running_bootstrap_node.md
- documentation/src/SUMMARY.md
- moved the existing bootstrap node guide to docs with some changes,
- hardware requirements around a bootstrap node should be tackled in https://github.com/ChainSafe/forest/issues/5207
Closes https://github.com/ChainSafe/forest/issues/5199
> docs: bootstrap node guide

- Cargo.toml
- deny.toml
Upgrade cargo resolver to v3(a Rust-version aware dependency resolver) since `cargo-spellcheck` has fixed the compatibility issue in its latest release.
https://doc.rust-lang.org/stable/edition-guide/rust-2024/cargo-resolver.html
-
Closes
> chore: upgrade cargo resolver to v3

- f3-sidecar/api.go
- f3-sidecar/manifest.go
- f3-sidecar/run.go
- f3-sidecar/utils.go
- f3-sidecar/utils_test.go
- src/daemon/mod.rs
- src/f3/mod.rs
- src/networks/mod.rs
Related to https://github.com/filecoin-project/go-f3/issues/916
-
Closes
> fix(f3): backfill static power table if unset in contract

- .github/RPC_PARITY_ISSUE_TEMPLATE.md
- .github/workflows/docs-auto-update.yml
- .github/workflows/forest.yml
- .github/workflows/link-check.yml
- .github/workflows/lotus-api-bump.yml
- .github/workflows/rpc-parity.yml
A test run: https://github.com/ChainSafe/forest/actions/runs/13856239026/job/38773601882
- run RPC parity tests on schedule
- disable RPC parity tests for PRs
- adjust nightly job schedules to fit the whole team
Closes https://github.com/ChainSafe/forest/issues/5411
> chore(ci): run RPC parity tests on schedule

- .github/DOCKER_ISSUE_TEMPLATE.md
- .github/SNAPSHOT_PARITY_ISSUE_TEMPLATE.md
- .github/workflows/dockerfile-check.yml
- .github/workflows/snapshot-parity.yml
- use exact workflow url in `DOCKER_ISSUE_TEMPLATE.md` and `SNAPSHOT_PARITY_ISSUE_TEMPLATE.md`
Closes
> fix(ci): use exact workflow url in issue template

- Cargo.lock
- Cargo.toml
- tests/lint.rs
-
Closes https://github.com/ChainSafe/forest/issues/5351
> chore: upgrade fvm to v4.6

- Makefile
- docs/docs/users/reference/env_variables.md
- src/chain/store/chain_store.rs
- src/daemon/mod.rs
- src/message/chain_message.rs
- src/rpc/methods/gas.rs
- src/rpc/methods/sync.rs
- src/rpc/mod.rs
- src/tool/offline_server/server.rs
- src/tool/subcommands/api_cmd/generate_test_snapshot.rs
- src/tool/subcommands/api_cmd/test_snapshot.rs
It turned out that the `messages_for_tipset` can be a massive bottleneck, so I added a cache similar to the one in migrations. This increased the performance of the `Filecoin.EthGasPrice` significantly (from ~4M requests handled in 30s to ~6M). See comparison with Lotus on mainnet:
Closes https://github.com/ChainSafe/forest/issues/5410
> feat(perf): optimize `Filecoin.EthGasPrice`

- .github/workflows/dockerfile-check.yml
- .github/workflows/rpc-parity.yml
- .github/workflows/snapshot-parity.yml
> fix(ci): empty workflow url link in issues

- scripts/devnet/lotus.dockerfile
> chore(ci): update lotus devnet dockerfile

- src/networks/mod.rs
- src/state_manager/circulating_supply.rs
- This PR updates `upgrade_teep_initial_fil_reserved` for testnets.
Closes
> fix: amend initial_fil_reserved for testnets

- src/daemon/context.rs
- src/daemon/db_util.rs
- src/daemon/mod.rs
- src/rpc/methods/sync.rs
- src/rpc/methods/sync/types.rs
- src/rpc/mod.rs
- src/tool/offline_server/server.rs
- src/tool/subcommands/api_cmd/generate_test_snapshot.rs
- src/tool/subcommands/api_cmd/test_snapshot.rs
- Some reshuffling and encapsulation to make the code more readable and avoid redundant operations in tests (creating ParityDB when it's not needed). 
Closes
> fix: simplify snapshot tracker usage

- .config/lychee.toml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepare release for the upcoming calibnet release.
Closes
> chore(release): prepare Forest v0.25.0 Bombadil release

- .gitignore
- scripts/tests/bootstrapper/.env
- scripts/tests/snapshot_parity/.env
- this fixes seemingly empty PRs like https://github.com/ChainSafe/forest/pull/5443 and updates the Lotus versions correctly.
Closes
> fix: automated api bumps

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- see https://github.com/ChainSafe/forest/issues/5465
Closes
> fix(ci): disable flaky EthTraceFilter

- .github/RPC_PARITY_ISSUE_TEMPLATE.md
- Make those issues a bit more unique so it's easier to reference them in discussions. https://github.com/ChainSafe/forest/issues?q=is%3Aissue%20state%3Aopen%20RPC%20parity%20test%20failure
Closes
Used formatting from https://momentjs.com/docs/#/displaying/format/
> chore: make parity tests issues more unique

- .github/RPC_PARITY_ISSUE_TEMPLATE.md
- a wild colon appeared there, which shouldn't be there https://github.com/ChainSafe/forest/issues/5469. Let's remove it.
Closes
> chore: less colons in rpc test issue

- CONTRIBUTING.md
- README.md
- Small fixes in the readme docs:
- dead link in the readme.md
- updating information about docs' source as they are public now
> chore: update contributing readme

- CHANGELOG.md
- rust-toolchain.toml
- src/cli/humantoken.rs
- src/db/car/forest/index/mod.rs
- src/db/db_mode.rs
- src/interpreter/fvm2.rs
- src/interpreter/fvm3.rs
- src/interpreter/fvm4.rs
- src/ipld/selector/mod.rs
- src/rpc/methods/eth.rs
- upgrade rust toolchain to `1.86.0`
```
warning: manual implementation of `ok`
--> src/db/db_mode.rs:29:13
|
29 | /             match version {
30 | |                 Ok(version) => Some(version),
...  |
34 | |             }
| |_____________^ help: replace with: `version.ok()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_ok_err
= note: `#[warn(clippy::manual_ok_err)]` on by default
warning: struct pattern is not needed for a unit variant
--> src/ipld/selector/mod.rs:328:29
|
328 |         ExploreRecursiveEdge { .. } => true,
|                             ^^^^^^^ help: remove the struct pattern
|
= help: for further information visit …
```
> chore: rust toolchain 1.86.0

- CHANGELOG.md
- fixed a changelog typo in version
Closes
> fix: changelog typo

- .github/workflows/snapshot-parity.yml
- issues should not be created on triggers against feature branches, e.g., https://github.com/ChainSafe/forest/issues/5537 for https://github.com/ChainSafe/forest/actions/runs/14331158947
Closes
> fix(ci): dont create compare issues on branch triggers

- Cargo.toml
- Panics are bugs and we shouldn't try to unwind them.
Closes #3153
> chore: abort on panic

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- prepares the Smeagol release, without which the Ring Bearer might get lost in Mordor of forks
Closes
> chore(release): prepare v0.25.3 smeagol

- docs/dictionary.txt
- docs/docs/users/guides/gc.md
- docs/docs/users/guides/interacting_with_wallets.md
- docs/docs/users/guides/methods_filtering.md
- docs/docs/users/guides/running_bootstrap_node.md
- docs/docs/users/guides/running_with_curio.md
- docs/docs/users/guides/running_with_gateway.md
- documents integration of Forest with the Lotus Gateway
Closes https://github.com/ChainSafe/forest/issues/5474
> docs: add lotus-gateway integration doc

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
- Add rpc method to the filter lists
Closes
> blacklist `Filecoin.ChainGetEvents`

- scripts/tests/api_compare/filter-list
- scripts/tests/api_compare/filter-list-offline
> disable flaky EthTraceFilter

- .github/workflows/release.yml
- .github/workflows/release_dispatch.yml
- documentation/src/developer_documentation/release_checklist.md
- added automated `cargo publish` on release, sample, dry run https://github.com/ChainSafe/forest/actions/runs/14615700487/job/41003351802
Closes https://github.com/ChainSafe/forest/issues/5524
> feat(ci): cargo publish on release

- .github/workflows/lotus-api-bump.yml
- automatically apply RPC label on Lotus API bumps, given they have a big chance of introducing regressions.
Closes
> chore: automatically apply RPC label on Lotus API bumps

- Cargo.lock
- deny.toml
- upgrade `fvm` and `fvm_shared` to `v4.7.2`
Closes
> chore(fvm): bump fvm and fvm_shared

- src/rpc/set_extension_layer.rs
> fix(rpc): default to v1 when version not set in url

- src/daemon/main.rs
Remove the `Error: Invalid subcommand: chain. All subcommands have been moved to forest-cli tool.` message from `forest` deamon.
-
Closes
> fix: remove subcommand moved message from daemon

- docs/docs/users/guides/interacting_with_wallets.md
- updated wallet docs based on user feedback
Closes
> chore: update wallet docs

- build/manifest.json
- src/networks/actors_bundle.rs
- src/networks/butterflynet/mod.rs
- src/networks/mod.rs
Test on CI: https://github.com/ChainSafe/forest/actions/runs/15466465537/job/43539593863
```
2025-06-05T12:11:13.781967Z  INFO forest::state_manager: Evaluating tipset: EPOCH=179, blocks=3, tsk=[bafy2bzaceaheairlcn77bn42uvdtt7lizcuxgds5ddaoavy5bhiorwfnsliqk, bafy2bzacecv73dmwqnealgpim44cxwzrj6x2p6d7datxvccnqrhsuw2hh7gcy, bafy2bzacedftonsgff3runxhdph47fke2ab4fxsv6wrpeonkg2yzxmzbzyww2]
Status: Synced (0 epochs behind)
Node Head: Epoch 180 ([bafy2bzaceard2ld355t5f4tcriq7qbry7tufzlnl6q55lh56q57criifztx74, ...])
Network Head: Epoch 180
Last Update: 2025-06-05T12:11:13.789388777+00:00
Active Sync Tasks: None
Sync complete!
```
-
Closes
> chore: reset butterflynet

- CHANGELOG.md
- src/chain_sync/chain_follower.rs
My stuck nodes on both mainnet and calibnet get fixed by this PR
-
Closes https://github.com/ChainSafe/forest/issues/5679
> fix: chain get stuck

- CHANGELOG.md
> chore: add read state API entry in CHANGELOG

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Prepares the `Whisperer in Darkness` release (v0.27.0)
Closes: #5698 
> chore(release): prepare v0.27.0 Whisperer in Darkness

- docs/docs/users/reference/cli.md
- src/cli_shared/cli/mod.rs
- The mentioned PR was merged, so the issue was, hopefully, resolved.
Closes
> chore: remove outdated memory leak mention

- src/daemon/mod.rs
- src/libp2p/behaviour.rs
- src/libp2p/discovery.rs
- src/libp2p/gossip_params.rs
- src/libp2p/service.rs
- src/networks/mod.rs
- src/networks/network_name.rs
- src/rpc/methods/f3.rs
- src/rpc/methods/state.rs
- src/state_manager/mod.rs
- typifies network names to reduce the probability of having issues with mismatches (yes, yes, yes, "testnetnet" is mainnet) in the future.
Closes https://github.com/ChainSafe/forest/issues/5808
> chore: typify network names

- src/message_pool/msgpool/selection.rs
- added link for the source of the cbor gen limit (which addresses https://github.com/ChainSafe/forest/pull/5732#discussion_r2190286629)
Closes
> chore(doc): add cbor-gen source link

- Cargo.lock
- I think someone committed some change to `Cargo.toml` without committing the lockfile (but it somehow passed? not sure). Regardless, this should fix the dry-run publish check.
Closes
> fix: uncommitted changes to lockfile
