ChainSafe/forest

src/state_migration/tests/mod.rs

- Disable state migration unit tests until [actor bundle inlining feature](https://github.com/ChainSafe/forest/issues/2765) is landed, to mitigate test timeout on CI
Closes

fix(test): disable state migration unit tests until actor bundle inlining feature is landed

---

src/genesis/mod.rs
src/utils/net.rs

- When downloading without `aria2c`, we would always decompressed the data. This is the wrong behavior when fetching a snapshot.
- The new code only decompresses _if_ we explicitly ask for it.
Closes

fix: don't decompress files unless necessary

---

src/utils/db/car_index/hash.rs
src/utils/db/car_index/index_header.rs

- The default hasher is not stable over time. CIDs are stable so use them in the ForestCAR.zst format.
Closes

fix: use stable hash algorithm

---

CHANGELOG.md
src/chain/mod.rs
src/chain/store/errors.rs
src/cli/subcommands/archive_cmd.rs
src/cli/subcommands/snapshot_cmd.rs
src/cli_shared/snapshot.rs
src/db/car/forest.rs
src/ipld/util.rs
src/rpc/chain_api.rs
src/utils/io/writer_checksum.rs

- `forest-cli snapshot export` generates `.forest.car.zst` output,
- `forest-cli archive export` generates `.forest.car.zst` output.
- bug fix: use tipset timestamp (rather than `now()`) when exporting.
It's more work to generate `.forest.car.zst` files but the new encoder is much faster than the old one. All in all, exporting is now a lot faster and the generated compressed files can be loaded directly into Forest.
Closes

feat: generate .forest.car.zst files by default

---

CHANGELOG.md
scripts/tests/forest_cli_check.sh
scripts/tests/harness.sh
src/chain/mod.rs
src/cli/subcommands/archive_cmd.rs
src/ipld/util.rs
src/rpc/chain_api.rs
src/utils/net.rs

- add `--diff` flag for exporting the set difference of two snapshots.
Closes #3204

feat: add `--diff` flag to `archive export`

---

CHANGELOG.md
scripts/gen_coverage_report.sh
scripts/tests/calibnet_other_check.sh
src/chain_sync/chain_muxer.rs
src/cli/subcommands/net_cmd.rs
src/libp2p/service.rs
src/rpc/mod.rs
src/rpc/net_api.rs
src/rpc_api/mod.rs
src/rpc_client/net_ops.rs
src/state_migration/tests/mod.rs

As part of https://github.com/ChainSafe/forest/issues/3218
- Add `forest-cli net info` command that prints libp2p stats directly from [`Swarm::network_info`](https://docs.rs/libp2p/latest/libp2p/struct.Swarm.html#method.network_info) API
Sample output:
```console
forest libp2p swarm info:
num peers: 47
num connections: 59
num pending: 3
num pending incoming: 0
num pending outgoing: 3
num established: 56
```
Closes

feat: forest-cli net info

---

src/message_pool/msgpool/provider.rs
src/rpc/beacon_api.rs
src/rpc/chain_api.rs
src/rpc/common_api.rs
src/rpc/db_api.rs
src/rpc/gas_api.rs
src/rpc/net_api.rs
src/rpc/node_api.rs
src/rpc/state_api.rs
src/rpc/wallet_api.rs
src/state_manager/mod.rs

Came across the issue when implementing https://github.com/ChainSafe/forest/pull/3292
- Simplify `Blockstore` type constraint in RPC APIs
Closes

fix: simplify blockstore type constraint in RPC APIs

---

Cargo.lock
src/chain_sync/chain_muxer.rs
src/state_migration/tests/mod.rs

As part of https://github.com/ChainSafe/forest/issues/3218 and as follow-up of https://github.com/ChainSafe/forest/pull/3292#discussion_r1279489109
To make it possible to count full peers that are ready for sending chain exchain requests to with this metrics
- Unset heaviest tipset epoch metrics (to -1) for disconnected peers
Closes

fix: unset heaviest tipset metrics for disconnected peers

---

src/db/car/mod.rs

- Reduce cache of z-frames from 2GiB to 1GiB.
Benchmarks in #3288 showed that there's little benefit to using a large cache. Going from 2GiB to 1GiB should have no impact on performance but will lessen the memory strain.
Closes

chore: reduce car cache from 2GiB to 1GiB

---

src/db/car/many.rs

- revert parallelization of get introduced in https://github.com/ChainSafe/forest/pull/3293. It turns out, it ends up being significantly less performant than a single-threaded version (at least when using two, three snapshots that have similar entries). We may look into it more in the future, for now let's remove the performance degradation.
Closes

Revert paralell manycar get

---

CHANGELOG.md
src/utils/db/car_stream.rs

- multiple frames are disallowed by default but we need them for the ForestCAR.zst format.
Closes

fix: allow streaming of CAR.zst files with multiple frames

---

.cargo/config.toml
CHANGELOG.md
src/bin/forest-tool.rs
src/lib.rs
src/tool/main.rs
src/tool/mod.rs
src/tool/subcommands/benchmark_cmd.rs
src/tool/subcommands/mod.rs

- introduce new `forest-tool` binary.
- add `forest-tool benchmark` command.
Closes

feat: add `forest-tool benchmark` command

---

CHANGELOG.md
src/blocks/persistence.rs
src/chain/store/chain_store.rs
src/daemon/mod.rs
src/db/memory.rs
src/db/mod.rs
src/db/parity_db.rs
src/db/rolling/gc.rs
src/db/rolling/impls.rs
src/db/tests/subtests/mod.rs
src/genesis/mod.rs
src/libp2p/chain_exchange/provider.rs
src/message_pool/config.rs
src/rpc/sync_api.rs
src/utils/db/file_backed_obj.rs

- moved most of the file-backed entries to the database. There is one left, `DbIndex`, but having the DB govern itself doesn't seem right.
- This is a breaking change. We could have a 'migration' in theory. Happy to discuss if we want it.
Closes https://github.com/ChainSafe/forest/issues/3231

Migrate settings to db

---

.clippy.toml
src/state_migration/tests/mod.rs
tests/car_tests.rs

- banned the `NamedTempFile::new` method. While it is valid in contexts where we don't persist the data, it is difficult to enforce the usage in contexts where we actually need it. The issue surfaced a few times already (https://github.com/ChainSafe/forest/pull/2893#issuecomment-1576755240, https://github.com/ChainSafe/forest/pull/2693) and wasn't caught by the CI as the runners have a single fs.
Closes
https://docs.rs/tempfile/latest/tempfile/struct.TempPath.html#method.persist
>  Note: Temporary files cannot be persisted across filesystems. Also neither the file contents nor the containing directory are synchronized, so the update may not yet have reached the disk when persist returns.
[1]: …

ban tempfile default c-tor

---

CHANGELOG.md
src/chain/mod.rs
src/cli/subcommands/archive_cmd.rs
src/rpc/chain_api.rs
src/tool/subcommands/benchmark_cmd.rs
src/utils/mod.rs
src/utils/stream.rs

- Exporting a snapshot involves two CPU-bound tasks: Walking the graph, and encoding the ForestCAR.zst file. This PR moves each task to a separate thread, nearly doubling the throughput.
Benchmark (three runs each):
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `export calibnet (par-buffer)` | 27.646 ± 0.295 | 27.324 | 27.904 | 1.00 |
| `export calibnet (baseline)` | 48.516 ± 0.458 | 47.999 | 48.873 | 1.75 |
Closes

feat: use multiple threads when exporting snapshots

---

scripts/tests/forest_cli_check.sh

- Two assertions didn't take null tipsets into account. Disable them until they can be replaced with better checks.
Closes

ci: disable two invalid assertions

---

CHANGELOG.md
src/cli/subcommands/snapshot_cmd.rs

- A depth of 2000 is the default but other depths are useful. This PR adds a flag to using a custom depth when exporting.
Closes

feat: add --depth flag to snapshot export

---

CHANGELOG.md
src/cli/subcommands/archive_cmd.rs

- Add `--diff-depth` flag to `forest-cli archive export`. All values reachable in the diff depth will not be included in diff snapshots.
- Fix type of `diff` from `ChainEpochDelta` to `ChainEpoch`.
Closes

feat: add flag for limiting the diff depth of snapshots

---

Cargo.lock
src/db/memory.rs
src/db/mod.rs
src/db/parity_db.rs
src/db/rolling/impls.rs
src/message_pool/config.rs

@LesnyRumcajs let me know if I'm wrong but I did not find the logic that transfers settings to the new database during garbage collection in https://github.com/ChainSafe/forest/pull/3320. This PR tries to fix the issue
- transfer settings store data during GC
Closes

fix: transfer settings store data during GC

---

.cargo/audit.toml
Makefile

Prompted by `cargo audit` beginning to fail in pipelines due to RUSTSEC-2022-0093

feat: better cargo-audit practice

---

.config/forest.dic
src/ipld/frozen_cids.rs

The old code would generate ONE arbitrary CID, it should be many

fix: Arbitrary implementation for FrozenCids

---

src/daemon/bundle.rs

- Add better error message when actor bundle files are not properly downloaded
Closes

fix: better error message when actor bundle files are not properly downloaded

---

.github/workflows/forest.yml
src/daemon/bundle.rs

- Make it a compile time error when the actor bundle size is invalid
- Add a `cargo publish --dry-run` CI job to capture errors like assets are invalid, assets are not properly included, and temporary crate patch, etc. that blocks cargo publishing.
Closes

fix: make it a compile time error when the actor bundle size is invalid

---

src/daemon/bundle.rs
src/ipld/cid_hashmap.rs
src/ipld/frozen_cids.rs
src/utils/cid/mod.rs

- Renamed `CidVariant` to `SmallCid` and modified type structure to hide enum details from users.
Closes #3367 

`CidVariant` refactor

---

CHANGELOG.md
src/cli/subcommands/archive_cmd.rs
src/cli/subcommands/snapshot_cmd.rs

- `forest-cli archive export` doesn't currently warn before overwriting the `output-path`. Added prompt if the output path already exists and a `--force` flag to suppress the prompt.
Closes associated task in #3322 

Add prompt to overwrite existing file during `archive export` and `--force` flag to suppress prompt

---

.cargo/audit.toml
CHANGELOG.md
src/cli/subcommands/snapshot_cmd.rs

- The `snapshot export` and `snapshot compress` subcommands for `forest-cli` are now both consistent with `forest-cli archive export` in supporting a short-form output path flag `-o` and a long-form output path flag `--output-path`. The flag `--output` for the `snapshot compress` subcommand was replaced by `--output-path`.
Closes #3322 

Use consistent output path flags for `archive export`, `snapshot export`, and `snapshot compress`

---

.cargo/audit.toml
Cargo.lock

- Fix RUSTSEC-2022-0093 with `cargo update -p libp2p-identity`
- Fix RUSTSEC-2023-0053 with `cargo update -p rustls-webpki@0.101.3`  (Failed to create an automatic PR in https://github.com/ChainSafe/forest/security/dependabot/46)
- Update `.cargo/audit.toml`
Closes
https://github.com/ChainSafe/forest/issues/3371
https://github.com/ChainSafe/forest/issues/3410

fix: RUSTSEC-2023-0053 and RUSTSEC-2022-0093

---

.cargo/audit.toml
Cargo.lock
Cargo.toml
src/libp2p/service.rs

Remove `webpki` crate from `Cargo.lock` by
- cargo update -p reqwest
- Remove `websocket` feature from `libp2p` as it does not seem to be useful at the moment
Closes https://github.com/ChainSafe/forest/issues/3410

fix: RUSTSEC-2023-0052

---

.config/forest.dic
.github/workflows/forest.yml
Cargo.lock
Cargo.toml
README.md
documentation/src/developer_documentation/database_migrations.md
documentation/src/environment_variables.md
scripts/tests/calibnet_db_migration.sh
src/cli/subcommands/state_cmd.rs
src/daemon/mod.rs
src/db/db_mode.rs
src/db/migration/db_migration.rs
src/db/migration/migration_map.rs
src/db/migration/mod.rs
src/db/migration/v0_12_1.rs
src/db/mod.rs
src/tool/subcommands/db_cmd.rs
src/utils/version/mod.rs
tests/db_migration_tests.rs
tests/db_mode_tests.rs

- Introduced a database migration framework: this should ensure we no longer have to manually re-create Forest databases going forward.
- More post-migration checks would be great to implement - I can either do this here or in a follow-up PR,
- the integration test should ensure we catch breaking changes early and we always have a migration at hand (and that the person that breaks it has the golden opportunity to implement the migration!)
- implemented a PoC migration from `0.12.1`. This migration won't be performed outside of tests (unless someone manually changes the `paritydb` directory to `0.12.1`)
- adhered (mostly) to the [agreed design](https://github.com/ChainSafe/forest/blob/main/documentation/src/developer_documentation/database_migrations …

feat: automatically migrate database folder, ensuring eternal backwards compatibility

---

src/chain/mod.rs
src/cli/subcommands/car_cmd.rs
src/cli/subcommands/snapshot_cmd.rs
src/db/car/forest.rs
src/tool/subcommands/benchmark_cmd.rs

This PR tries to remove the duplicate hard-coded frame size and compression level parameters from `fn forest::Encoder::compress_stream`
- Add const DEFAULT_FOREST_CAR_FRAME_SIZE
- Add const DEFAULT_FOREST_CAR_COMPRESSION_LEVEL
- Add `fn compress_stream_default` that defaults `zstd_frame_size_tripwire` and `zstd_compression_level` to `DEFAULT_FOREST_CAR_FRAME_SIZE` and `DEFAULT_FOREST_CAR_COMPRESSION_LEVEL` respectively
Closes

feat: add `fn forest::Encoder::compress_stream_default` to reduce duplicate code

---

src/cli/subcommands/archive_cmd.rs
src/ipld/util.rs
src/tool/subcommands/benchmark_cmd.rs

- all blocks going back to genesis should be included when calculating diff sets
- this fix reduces the file size of diff files
Closes

fix: include all blocks when calculating diff sets

---

CHANGELOG.md
documentation/src/configuration.md
src/cli_shared/cli/client.rs
src/cli_shared/cli/mod.rs
src/daemon/mod.rs

This PR tries to implement below feature decribed in https://github.com/ChainSafe/forest/issues/3334
> Add flag --consume-snapshot. It should do the same as --import-snapshot, but it'll move or delete the snapshot.
- add `--consume-snapshot` to `forest` daemon
Closes https://github.com/ChainSafe/forest/issues/3334

feat: add `--consume-snapshot` to `forest` daemon

---

Cargo.lock
Cargo.toml
src/daemon/bundle.rs
src/tool/subcommands/state_migration_cmd.rs

- remove `futures-io` as we're moving towards tokio.
A follow-up PR will get rid of the external CAR reader/writer entirely.
Closes #3084

chore: remove futures-io feature from async_compression

---

Cargo.lock
Cargo.toml
src/utils/encoding/cid_de_cbor.rs
tests/import_snapshot_tests.rs

- Bumps serde-ipld-dagcbor to 0.4.1 that fixes some ser/de roundtrip errors.
Closes https://github.com/ChainSafe/forest/issues/3395

[Chore] Bump serde-ipld-dagcbor to 0.4.1.

---

CHANGELOG.md
src/tool/subcommands/archive_cmd.rs

- add `forest-tool archive merge`.
- this command is similar to `forest-tool car union` but outputs a valid Filecoin snapshot.
- testing left as an exercise for the reader. Tracking issue: https://github.com/ChainSafe/forest/issues/3347
Closes

feat: command for merging snapshot files

---

.config/forest.dic
Cargo.lock
src/ipld/cid_hashmap.rs
src/utils/cid/mod.rs

- Added an `Arbitrary` implementation for `CidHashMap` and replaced `generate_hash_maps` function with the `Arbitrary` impl.
Closes #3413 

Replace `generate_hash_maps` method with `Arbitrary` implementation

---

src/db/car/forest.rs
src/ipld/util.rs
src/tool/subcommands/benchmark_cmd.rs
src/utils/db/car_stream.rs
src/utils/db/car_util.rs

- Rename `Block` to `CarBlock` to avoid name clashes with filecoin blocks.
Part of #3490

chore: rename `Block` to `CarBlock`

---

src/state_migration/tests/mod.rs

- Disable the nv17 migration test. The nv18 and nv19 tests were already disabled for the same reason.
Closes

fix: disable flaky migration test

---

Cargo.lock
Cargo.toml
Dockerfile
Dockerfile-alpine
Makefile
documentation/src/basic_usage.md
src/cli_shared/logger/mod.rs
src/cli_shared/snapshot.rs
src/daemon/mod.rs
src/tool/main.rs

- Download snapshots from CloudFlare.
- Use `reqwest` instead of `aria2c`.
- Log to stderr in `forest-tool`.
Closes

feat: download snapshots from CloudFlare

---

src/auth/mod.rs
src/cli/subcommands/auth_cmd.rs
src/daemon/mod.rs

-  Change `Lazy<Vec<String>>` to `&[&str]`
This PR does not update RPC-related struct fields to take `&str` though, which might require some workarounds to work with  `json_rpc` framework
Closes https://github.com/ChainSafe/forest/issues/3499

fix: Lazy<Vec<String>> should just be &[&str]

---

src/daemon/mod.rs
src/rpc/sync_api.rs
src/rpc_api/data_types.rs

- Remove the unused `new_mined_block_tx` field in `RPCState`.
Closes

chore: remove unused RPCState field

---

Cargo.lock

- `cargo update -p quinn-proto`
Closes https://github.com/ChainSafe/forest/issues/3512

fix(ci): fix RUSTSEC-2023-0063 to unblock CI

---

src/chain_sync/tipset_syncer.rs

- `find_range` shouldn't return a future.
Closes

chore: refactor futures in the ChainMuxer and TipsetProcessor

---

Cargo.lock
Cargo.toml
src/daemon/mod.rs
src/libp2p/behaviour.rs
src/libp2p/service.rs

- Bump versions of `toml`, `dialoguer` and `memmap2`
- Bump patch versions of all crates
- Fix `dialoguer` build errors.
- Fix `libp2p` build warnings (from patch upgrade).
> warning: use of deprecated module `libp2p::libp2p_swarm::keep_alive`: Configure an appropriate idle connection timeout via `SwarmBuilder::idle_connection_timeout` instead. To keep connections alive 'forever', use `Duration::from_secs(u64::MAX)`.
Closes

chore(deps): upgrade non-fvm deps

---

scripts/tests/calibnet_db_migration.sh

- Show DB migration results in the github-worker output. This makes it a bit easier to see when something goes wrong.
- The sync output is still hidden. You must re-run the code locally to see the errors if something goes wrong during sync.
Closes

ci: send db-migration output to stdout rather than a file

---

src/db/migration/migration_map.rs

- Fixes a `create_migrations` macro bug that caused it to fail with more than one migration
Closes

[Fix] create_migrations macro.

---

src/shim/machine/manifest.rs
src/shim/machine/mod.rs
src/state_migration/common/macros/system.rs
src/state_migration/common/macros/verifier.rs
src/state_migration/nv17/migration.rs
src/state_migration/nv17/miner.rs
src/state_migration/nv18/eam.rs
src/state_migration/nv18/eth_account.rs
src/state_migration/nv18/migration.rs
src/state_migration/nv19/migration.rs

#3076
- Use `fil_actor_states`' list of actors and their names rather than defining our own
- Don't have a stringy API for getting builtin actors
- Better names for everything

refactor: manifest

---

src/cli/subcommands/attach_cmd.rs
src/cli/subcommands/auth_cmd.rs
src/cli/subcommands/chain_cmd.rs
src/cli/subcommands/config_cmd.rs
src/cli/subcommands/db_cmd.rs
src/cli/subcommands/info_cmd.rs
src/cli/subcommands/net_cmd.rs
src/cli/subcommands/send_cmd.rs
src/cli/subcommands/shutdown_cmd.rs
src/cli/subcommands/sync_cmd.rs

- taking ownership of the arguments is slightly cleaner
Closes

chore: take ownership of command arguments

---

src/chain_sync/tipset_syncer.rs

As part of https://github.com/ChainSafe/forest/issues/3185
- refactor `TipsetRangeSyncerFuture` into idiomatic futures
- (`TipsetProcessorFuture` no longer exists)
Closes 

fix: refactor TipsetRangeSyncerFuture into idiomatic futures

---

src/db/rolling/impls.rs

- the test is sometimes timing out because of many values quickcheck wants to provide. The rolling db is going away, so let's not spend more time on this than necessary. See https://github.com/ChainSafe/forest/pull/3504
Closes

remove flaky rolling db test

---

.github/workflows/unit-tests.yml

Since `/home/fuzzy/.cache/sccache` is preserved after each CI job (and we need to clean it up periodically), there's no point in using a remote backend for `sccache` on `fuzzy`, to slightly speedup the job
Question: do we really need both `test` and `test-release`? As they won't run in parallel with the single `fuzzy` runner, disabling one of them could reduce the in-queue time.  @lemmih @LesnyRumcajs 
- Update `sccache` config to use local FS for jobs that run on `fuzzy`
https://github.com/ChainSafe/forest/actions/runs/6466767740/job/17556501553?pr=3564#step:15:2
> Compile requests                     991
Compile requests executed            7[6](https://github.com/ChainSafe/forest/actions/runs/6466767740/job/17556501553?pr=3564#step:15:6)6
Cache …

fix(ci): use local FS for sccache on fuzzy

---

Cargo.lock
scripts/gen_coverage_report.sh

https://github.com/ChainSafe/forest/actions/runs/6484148389/job/17610655915
has no logs, and failed twice.
Maybe this will help?

chore: trace verbose coverage report

---

scripts/devnet/ci_check.sh

- Change `params` to `param`.
At present, the Forest RPC doesn't care if the `param` field is missing. But this may change in the future to align us more with Lotus. Ideally, we want a valid call to Forest to be a valid call to Lotus.
Closes

wibble: fix RPC parameter in ci_check script 

---

CHANGELOG.md
Cargo.lock
src/db/car/forest.rs

- When gathering the mapping from hash to zstd frame offset, use a vector rather than a hashmap. Colliding hashes should be able to point to different zstd frames.
There is a small chance some of the archival ForestCAR files are invalid. Fortunately, it is easy to verify. I'll re-scan the files and re-generate any broken archives.
Closes

fix: don't drop colliding keys from ForestCAR

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/db/migration/migration_map.rs
src/db/migration/mod.rs
src/db/migration/v0_12_1.rs
src/db/migration/void_migration.rs

- added void migrator to be re-used across new versions not needing any migration logic,
- bump the version to 0.14.0 
Closes

Prepare release v0.14.0 "Hakuna Matata" :boar: :lion: 

---

CHANGELOG.md
Cargo.lock
src/tool/subcommands/car_cmd.rs

- add `forest-tool car validate` command.
This new command verifies the invariants expected to be true for all CAR files (not just Filecoin CAR files).
Closes

feat: basic validation of CAR files

---

Cargo.lock
src/cli/main.rs
src/cli/subcommands/info_cmd.rs
src/cli/subcommands/mod.rs
tests/config.rs

- remove command-line flags that were meant for the daemon (such as `--halt-after-import`).
After:
```
forest-filecoin 0.13.0+git.6674ad36d
ChainSafe Systems <info@chainsafe.io>
Rust Filecoin implementation.
USAGE:
forest-cli [OPTIONS] <COMMAND>
SUBCOMMANDS:
chain     Interact with Filecoin blockchain
auth      Manage RPC permissions
net       Manage P2P network
sync      Inspect or interact with the chain synchronizer
mpool     Interact with the message pool
state     Interact with and query Filecoin chain state
config    Manage node configuration
snapshot  Manage snapshots
archive   Manage archives
send      Send funds between accounts
info      Print node info
db        Database management
attach    Attach to daemon via a JavaScript console …
```

fix: remove unused cli options from `forest-cli`

---

.github/workflows/docs.yml
Cargo.toml
Makefile
build/vendored-docs-redirect.index.html
lychee.toml
src/lib.rs
src/shim/mod.rs
src/utils/encoding/fallback_de_ipld_dagcbor.rs
src/utils/encoding/mod.rs

- Include dependencies in hosted docs, which unblocks #3595 
- Move rustdoc `#[allow(..)]` and `#[deny(..)]` policies to `src/lib.rs`
- Include private items in builds for <https://docs.rs>
- Get rid of the nightly documentation toolchain, and just redirect <https://chainsafe.github.io/forest/rustdoc/> to <https://chainsafe.github.io/forest/rustdoc/forest_filecoin/>
The previous landing page was ugly and empty
- Commonise `lychee` config
- Fix dead link bugs.
Lychee previously didn't pick up eg https://chainsafe.github.io/forest/rustdoc/forest_filecoin/utils/encoding/de/index.html containing a dead link to https://chainsafe.github.io/forest/rustdoc/forest_filecoin/utils/encoding/trait.Deserialize.html

chore: rework hosted docs

---

CHANGELOG.md
scripts/gen_coverage_report.sh
src/cli/main.rs
src/cli/subcommands/attach_cmd.rs
src/cli/subcommands/auth_cmd.rs
src/cli/subcommands/chain_cmd.rs
src/cli/subcommands/config_cmd.rs
src/cli/subcommands/db_cmd.rs
src/cli/subcommands/info_cmd.rs
src/cli/subcommands/mpool_cmd.rs
src/cli/subcommands/net_cmd.rs
src/cli/subcommands/send_cmd.rs
src/cli/subcommands/shutdown_cmd.rs
src/cli/subcommands/snapshot_cmd.rs
src/cli/subcommands/state_cmd.rs
src/cli/subcommands/sync_cmd.rs

- Remove the `Config` and `Client` structures from the `forest-cli` command-line handling.
- Add `--expire-in` flags to `forest-cli auth create-token` and `forest-cli auth api-info` commands.
- Move `finality` out of the client. The node is responsible for correctness.
Closes

feat/fix: simplify configuration for `forest-cli`

---

src/cli/subcommands/attach_cmd.rs

It would be challenging to prove that panics are impossible during serialization/deserialization of `JsValue`'s. Let's play it safe and remove the unwraps.
- Remove calls to `unwrap` in the `attach` subcommand.
Closes #3575

Remove calls to unwrap

---

Cargo.lock

- fixes a warning during installation
```
warning: package `ahash v0.8.3` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```
Closes

bump yanked ahash version

---

src/utils/io/mmap.rs
tests/tool_tests.rs

- more checks for actors bundle,
- don't create test artefacts in the repo root (without this change, each invocation of `make test` would create `actor_bundles.car.zst` in the root, making the directory dirty)
Closes

don't create test artefacts in repo root

---

src/ipld/util.rs

- Aborts workers when channels are empty. 
Closes

[Fix] Parallel graph walk stuck.

---

.github/workflows/forest.yml
scripts/tests/calibnet_no_discovery_check.sh
scripts/tests/harness.sh
src/libp2p/discovery.rs

- Connect to seed peers when `kademlia` is disabled
Closes https://github.com/ChainSafe/forest/issues/3633

fix: forest is not able to sync when kademlia is disabled

---

src/daemon/mod.rs
src/libp2p/service.rs

Currently, RPC and metrics endpoints are listened on before a forest node is detached. This PR tries to make p2p endpoints being listened on before a forest node is detached as well, to facilitate getting peer addresses in testing scripts without extra waiting 
(and remove `wait_until_p2p_is_ready` in https://github.com/ChainSafe/forest/pull/3593/files#diff-176041f18568d006c10ca85238739cb3238bd6c39f777bdab37a5ce55fa69fa7R108)
- listen on p2p endpoints before being detached
- fail fast if the no provided listen addresses are valid
Closes

fix: listen on p2p endpoints before being detached

---

src/chain_sync/chain_muxer.rs

As part of https://github.com/ChainSafe/forest/issues/3509
The change was originally introduced as part of https://github.com/ChainSafe/forest/pull/3593/files#diff-15b238f8e8b4bd891cf02219c996ebe094b39e766988d33755861440bb118b27R420 but it's no longer relevant to that PR 
More discussion here: https://github.com/ChainSafe/forest/pull/3593#discussion_r1369815140
- remove peer_tipset_epoch metric records for disconnected peers to avoid bloating metrics
Closes

fix: remove peer_tipset_epoch metric records for disconnected peers

---

.config/nextest.toml
src/networks/actors_bundle.rs

- Addresses a timeout [failure](https://github.com/ChainSafe/forest/actions/runs/6692088982/job/18180570367?pr=3593#step:7:1095) in the CI. Now, each GET will take no more than 30s. Given many futures are spawned in parallel, this should not compound. Note that this may be too little on a horrible internet connection, but on a regular one, it should be fine. The test will fail if both sources are completely down (this will mean we don't have enough redundancy)
Closes

add GET timeout to mirror tests

---

src/daemon/bundle.rs
src/daemon/mod.rs
src/networks/actors_bundle.rs
src/networks/mod.rs
src/state_migration/tests/mod.rs
src/tool/subcommands/snapshot_cmd.rs

- there is no point in downloading bundles for calibnet and devnet when running mainnet-only. This change makes it so that only actor bundles for the network at hand are downloaded.
Closes

daemon: download only bundles for the given network

---

CHANGELOG.md
src/rpc/chain_api.rs
src/rpc/mod.rs
src/rpc_api/data_types.rs
src/rpc_api/mod.rs

- implement Filecoin.ChainGetMessagesInTipset API (server side)
Manually tested on calibnet
request payload:
```json
{
"jsonrpc": "2.0",
"id": 2,
"method": "Filecoin.ChainGetMessagesInTipset",
"params": [
[
{
"/": "bafy2bzacecctsgyvam3fxhppheh2ubkarpgjvkn7cyvesrmhttuusuwzspk6o"
},
{
"/": "bafy2bzacedt2daxg7mcvbv5sdg47zruj2ogx2wxzrjidoiwpcmyzzyfazjtcu"
},
{
"/": "bafy2bzaceavd2unelg7g2mghiaq2te3qkfyghdjapdyr6ltjti7dlglhuqsni"
},
{
"/": "bafy2bzacebr63zjyie3oqjj7gjxr6mwifazolv44d764hc6g7mhhdehlkgel6"
}
]
]
}
```
Lotus response
```json
{
"jsonrpc": "2.0",
"result": [
{
"Cid": {
"/": "bafy2bzaceatwgj5tnix7n2rb3d5vig23wjypzw577rkl4tuq7kxkanbos55yk"
},
"Message": {
"Version": 0,
"To": "t01022", …
```

feat: implement `Filecoin.ChainGetMessagesInTipset` API (server side)

---

.github/workflows/forest.yml
scripts/tests/calibnet_db_migration_car_db.sh

- [CI] Adds a migration check for `car_db`-enabled forest versions.
Closes https://github.com/ChainSafe/forest/issues/3690

[CI] Add 'car_db' migration checks.

---

src/rpc_api/mod.rs
src/rpc_client/state_ops.rs
src/tool/subcommands/api_cmd.rs

- Tests for `StateAccountKey`, `StateCirculatingSupply` and `StateDecodeParams`. Note, Forest does not support these methods yet.
- The tests are run manually with the `forest-tool api compare` command.
Part of #3639

test: compare Lotus compatibility for `StateAccountKey`, `StateCirculatingSupply` and `StateDecodeParams`

---

src/cli/subcommands/chain_cmd.rs
src/lotus_json/signed_message.rs
src/rpc_client/chain_ops.rs

Lotus uses `ChainReadObj` API to print full signed message in `lotus chain getmessage [CID]` output, this PR tries to match it in `forest-cli chain message -c [CID]`.
Note: The output still slightly differs, `forest-cli` prints `SignatureType` in string format while `lotus` prints it in Integer format, which has been addressed by https://github.com/ChainSafe/forest/pull/3698
- align forest-cli chain message output with lotus
`forest-cli chain message -c bafy2bzacedpkf2v5kgm4mvvljer6q3s45yfcdzaiyl3xdoivt5m53iv77v76w` output
```json
{
"Message": {
"Version": 0,
"To": "t410famf46pkqzlieylsxhenre5ajqkutbbrb652rziy",
"From": "t410fot3vkzzorqg4alowvghvxx4mhofhtazixbm6z2i",
"Nonce": 26944, …
```

fix: align forest-cli chain message output with lotus

---

src/chain_sync/network_context.rs
src/libp2p/service.rs

We're observing an increasing amount of `bitswap` and  `hello` timeouts on mainnet(with forest@0.16.0, forest@0.15.2, and forest@0.15.0), which slows down the Tipset sync speed in forest. This PR tries to make a quick fix by increasing these timeout. Further investigation is still needed
Manually tested on `mainnet`, both timeouts are *almost* gone.
- increase `bitswap` timeout
- increase `hello` timeout
Closes

fix(libp2p): increase bitswap timeout

---

src/libp2p/behaviour.rs

As a follow-up of https://github.com/ChainSafe/forest/pull/3713
Currently, `target_peer_count` is only used to decide whether or not to perform proactive kad queries, while it does not prevent forest from accepting inbound connections. When total connections reach 2k+(test on @0.16.0, @0.15.2 and @0.15.0), timeout rate of `hello` and `bitswap` become high. This PR tries to setup `connection_limits` behaviour with `target_peer_count` to limit the total active connections
Manually tested on mainnet, smaller connection limits could also mitigate timeouts in `bitswap` and `hello` 
- Calculate the connection limits from `target_peer_count`, instead of using static values.
Manually tested on mainnet, forest is able to sync with normal performance.
Closes …

fix(libp2p): reduce connection limits

---

scripts/tests/calibnet_wallet_check.sh
src/lotus_json/key_info.rs
src/lotus_json/signature.rs
src/lotus_json/signature_type.rs
src/lotus_json/signed_message.rs
src/rpc_api/mod.rs
src/rpc_client/state_ops.rs
src/shim/version.rs
src/tool/subcommands/api_cmd.rs

- `StateLookupID`
- `StateNetworkVersion`
- `WalletBalance`
- Changed `SignatureType` to always be encoded as an integer. Lotus requires this in certain places.
- Test wallet import/export roundtripping in a more flexible way.
Part of #3639

test: check compatibility for three more RPC calls

---

CHANGELOG.md
src/tool/subcommands/api_cmd.rs

This PR tries to address 
> Right now, only the last 20 tipsets are used. It would be nice to sample a greater range.
- add `--n-tipsets` option to `forest-tool api compare` to allow customizing the number of tipsets to test against
Closes

feat: add `--n-tipsets` option to `forest-tool api compare`

---

CHANGELOG.md
src/rpc/mod.rs
src/rpc/state_api.rs
src/rpc_api/mod.rs
src/shim/state_tree.rs
src/state_manager/mod.rs
src/tool/subcommands/api_cmd.rs

- implement Filecoin.StateAccountKey RPC API
(Manually changed the code to compare the last 500 tipsets)
```
Running `target/release/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2023-11-21_height_1108092.forest.car.zst --filter StateAccount`
| RPC Method                     | Forest | Lotus |
|--------------------------------|--------|-------|
| Filecoin.StateAccountKey (476) | Valid  | Valid |
```
Lotus code:
```go
func (m *StateModule) StateAccountKey(ctx context.Context, addr address.Address, tsk types.TipSetKey) (address.Address, error) {
ts, err := m.Chain.GetTipSetFromKey(ctx, tsk)
return address.Undef, xerrors.Errorf("loading tipset …
```

feat: implement Filecoin.StateAccountKey RPC API

---

CHANGELOG.md
src/rpc/mod.rs
src/rpc/state_api.rs
src/rpc_api/mod.rs
src/state_manager/mod.rs
src/tool/subcommands/api_cmd.rs

- implement Filecoin.StateLookupID RPC API
- fix a typo and bug in Filecoin.StateAccountKey
```
Running `target/debug/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2023-11-23_height_1113729.forest.car.zst --filter StateLook -n 500`
| RPC Method                   | Forest | Lotus |
|------------------------------|--------|-------|
| Filecoin.StateLookupID (341) | Valid  | Valid |
```
Lotus code:
```go
func (m *StateModule) StateLookupID(ctx context.Context, addr address.Address, tsk types.TipSetKey) (address.Address, error) {
ts, err := m.Chain.GetTipSetFromKey(ctx, tsk)
return address.Undef, xerrors.Errorf("loading tipset %s: %w", tsk, err) …
```

feat: implement Filecoin.StateLookupID RPC API

---

CHANGELOG.md
src/chain/store/index.rs

- Tipset lookup _must_ be fast. Looking up tipsets in `O(n)` time breaks Forest.
- This PR is a work-around until we can implement a better lookup function.
Closes

fix: bump tipset lookup cache

---

Cargo.lock
Cargo.toml
src/utils/reqwest_resume/mod.rs
src/utils/reqwest_resume/tests.rs

As a follow-up of https://github.com/ChainSafe/forest/pull/3753
- remove `hyper` from Cargo dependencies so that we don't need to manually upgrade it to `1.0`
- bump minor versions of `nonempty` and `unsigned-varint`
- bump patch versions
Closes

chore: remove `hyper` from Cargo dependencies

---

Cargo.lock
Cargo.toml
src/state_manager/mod.rs

- in light of a deadlock in https://github.com/ChainSafe/forest/pull/3756, this is an alternative to achieve 64 MiB stack required by FVM.
Closes

increase stack size to 64 MiB for FVM calls

---

src/utils/reqwest_resume/mod.rs

- use the global HTTP client in the `reqwest_resume`, same as in the rest of the Forest codebase.
Closes

Use global HTTP client in reqwest_resume

---

.github/workflows/scripts-lint.yml

- Pin rubocop to version 1.57 to avoid unexpected surprises when new versions are released.
Closes

ci: pin rubocop version to 1.57

---

.github/workflows/scripts-lint.yml
scripts/linters/find_unused_deps.rb

- Bumped `rubocop` version from 1.57 to 1.58 and corrected the resulting "offenses."
Closes #3780 

chore: bump rubocop version to 1.58 and correct offenses

---

.github/workflows/docker.yml
.github/workflows/unit-tests.yml

- Fuzzy is still being re-homed. Use buildjet until the transfer is complete.
Closes

CI: fuzzy is down, switching to buildjet

---

CHANGELOG.md
src/lotus_json/mod.rs
src/rpc/eth_api.rs
src/rpc/gas_api.rs
src/rpc/mod.rs
src/rpc/rpc_util.rs
src/rpc_api/mod.rs
src/rpc_client/eth_ops.rs
src/tool/subcommands/api_cmd.rs

As part of https://github.com/ChainSafe/forest/issues/3640
- Implement `Filecoin.EthGasPrice` RPC API
- Test coverage in `forest-tool api compare`
```console
Running `target/debug/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2023-12-07_height_1153690.forest.car.zst --filter EthGas`
| RPC Method           | Forest | Lotus |
|----------------------|--------|-------|
| Filecoin.EthGasPrice | Valid  | Valid |
```
Lotus code
```go
func (a *EthModule) EthGasPrice(ctx context.Context) (ethtypes.EthBigInt, error) {
// According to Geth's implementation, eth_gasPrice should return base + tip
// Ref: https://github.com/ethereum/pm/issues/328#issuecomment-853234014
ts := a.Chain.GetHeaviestTipSet()
baseFee := …
```

feat: impl EthGasPrice RPC API

---

src/tool/subcommands/snapshot_cmd.rs

- Use a shorter help message when listing available commands.
- Full help message is still available when asking for help with the `state-compute` command.
Before:
```
$ cargo run --bin forest-tool -- snapshot 
Manage snapshots
Usage: forest-tool snapshot <COMMAND>
Commands:
fetch          Fetches the most recent snapshot from a trusted, pre-defined location
validate       Validates the snapshot
compress       Make this snapshot suitable for use as a compressed car-backed blockstore
compute-state  Filecoin keeps track of "the state of the world", including: wallets and their balances; storage providers and their deals; etc...
help           Print this message or the help of the given subcommand(s)
Options:
-h, --help  Print help
```
After:
```
$ …
```

fix: shorten help message for `state-compute` when listing available commands

---

.github/workflows/forest.yml
Cargo.lock

- re-enable kad ci checks since stateless mode is re-enabled by https://github.com/ChainSafe/forest/pull/3820
Closes

fix(ci): re-enable kad ci checks

---

src/rpc_client/mod.rs
src/tool/subcommands/api_cmd.rs

Some APIs are designed to not fail fast when a request cannot be fulfilled, e.g. StateWaitMsg. This PR tries to add a timeout to `RpcTest` to prevent the test command from waiting infinitely.
- add default timeout 1min
- add `fn with_timeout` to `RpcTest`
- add `Timeout` to `EndpointStatus`
Example output (By tweaking the timeout setting locally)
```
| RPC Method                 | Forest  | Lotus |
|----------------------------|---------|-------|
| Filecoin.StateWaitMsg (24) | Timeout | Valid |
| Filecoin.StateWaitMsg (2)  | Valid   | Valid |
```
Closes

feat: add timeout to api compare command

---

src/tool/subcommands/api_cmd.rs

- Added `max_concurrent_requests` to limit max concurrent test runs which prevents overloading the rpc servers.
This issue was observed for `lotus` only and not for `forest`, when approx 1000+ RPC tests were executed simultaneously.
Closes

Fix: RPC parallel test runs

---

src/chain/store/base_fee.rs
src/chain_sync/chain_muxer.rs
src/cli/subcommands/mpool_cmd.rs
src/message_pool/msgpool/msg_pool.rs
src/message_pool/msgpool/test_provider.rs
src/rpc/chain_api.rs
src/rpc/gas_api.rs
src/state_manager/chain_rand.rs
src/state_manager/mod.rs

As part of https://github.com/ChainSafe/forest/issues/3861 and follow-up of https://github.com/ChainSafe/forest/pull/3858
- use `.first()` instead of `[0]` for NonEmpty block headers in Tipset
Closes

fix: use `.first()` instead of `[0]` for NonEmpty block headers in Tipset

---

CHANGELOG.md
scripts/tests/forest_cli_check.sh
src/cli_shared/snapshot.rs

Filops snapshot service has been shut down, update the code and CI accordingly.
https://github.com/ChainSafe/forest/actions/runs/7551462787/job/20562704877?pr=3873#step:6:50
```
+ forest-tool snapshot fetch --chain calibnet --vendor filops
2024-01-17T08:24:58.902367Z ERROR forest_filecoin::cli_shared::cli: Failed fetching the snapshot: error sending request for url (https://snapshots.calibrationnet.filops.net/minimal/latest.zst): error trying to connect: dns error: failed to lookup address information: No address associated with hostname
```
- remove `Filops` from `TrustedVendor`
- fix CI
Closes

fix: remove filops snapshot provider and fix ci

---

Cargo.lock

Fix CI error: https://github.com/ChainSafe/forest/actions/runs/7566287645/job/20603409701?pr=3881#step:7:75
```
Crate:     h2
Version:   0.4.0
Title:     Resource exhaustion vulnerability in h2 may lead to Denial of Service (DoS)
Date:      2024-01-17
ID:        RUSTSEC-2024-0003
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0003
Solution:  Upgrade to ^0.3.24 OR >=0.4.2
```
- Upgrade `h2`
Closes

fix(ci): make audit errors

---

.github/workflows/forest.yml

CI check scripts sometimes fail after 1h, this PR adds timeouts to all the scripts so that they fail fast.
e.g. https://github.com/ChainSafe/forest/actions/runs/7566287643/job/20603550273?pr=3881
- add timeout to CI check scripts
Closes

fix(ci): add timeout to CI check scripts

---

src/chain/store/tipset_tracker.rs
src/cli/subcommands/attach_cmd.rs
src/cli/subcommands/sync_cmd.rs
src/lotus_json/nonempty.rs
src/rpc/sync_api.rs
src/rpc_api/data_types.rs

As part of https://github.com/ChainSafe/forest/issues/3861
- Change `active_syncs: Vec<SyncState>` to `active_syncs: NonEmpty<SyncState>`
- Replace `active_syncs[0]` with `active_syncs.first()`
Closes

fix: use NonEmpty for active_syncs in RPCSyncState

---

scripts/devnet/lotus.dockerfile

I have recently seen quite a few ci failures in the devnet checks job, this PR tries to upgrade lotus to the latest and see if the issue get mitigated (even not we need the upgrade anyway)
- bump lotus version in devnet check CI job
Closes

chore(ci): bump lotus version in devnet check

---

.github/workflows/docker.yml

As part of https://github.com/ChainSafe/forest/issues/3892 and a follow-up of https://github.com/ChainSafe/forest/pull/3902
The fat image is built on top of the slim one with extra steps fetching data from the internet. There's a chance that the slim image is successfully built and pushed but the fat image fails. After reversing the order, it should either both fail(fail fast) or both succeed as the build-slim-image step should have been cached when the build-fat-image step is successful.
- build and push fat docker image before the slim one
Closes

fix(ci): build and push fat docker image before the slim one

---

src/cli_shared/snapshot.rs
src/daemon/mod.rs

Context: https://github.com/ChainSafe/forest/issues/3710
- use .frdownload extension for partially downloaded snaphsot
- improve logging
- small improvements on url and filename construction logic
Closes https://github.com/ChainSafe/forest/issues/3710

fix(tool): use .frdownload extension for partially downloaded snaphsot

---

CHANGELOG.md
src/utils/proofs_api/paramfetch.rs

Given that the log got stuck at `forest::progress: Loading 3180 (elapsed time: 9s)`, it means that it was using the `reader` method from the `utils/net.rs` file. Now, it means that either a snapshot was being downloaded or there was a download from IPFS (`download_ipfs_file_trustlessly`). Snapshot download during snapshot validation? Certainly not. It means we need to muzzle the IPFS download and fail faster.
- added a timeout of 30 minutes to the parameters fetch.
Closes https://github.com/ChainSafe/forest/issues/3857

timeout on paramfetch

---

.github/workflows/forest.yml

We still see CI timeout failures when downloading the proof parameter files, see https://github.com/ChainSafe/forest/actions/runs/7706724002/job/21002879420#step:6:29
This PR tries to mitigate the issue by caching proof param files in that job
- cache proof param files in `forest-cli-check` job
Closes

fix(ci): cache proof param files in `forest-cli-check` job

---

src/rpc_client/mod.rs

- Propagate user-friendly (friendlier?) error messages.
Calling `forest-wallet list` without a token:
Before: `Error: error decoding response body: expected value at line 1 column 1 (code=0)`
After: `Error: Permission denied: Token required. (code=403)`
Creating a new key-pair with a read-only token:
Before: `Error: error decoding response body: expected value at line 1 column 1 (code=0)`
After: `Error: Permission denied: Insufficient rights. (code=403)`
Using an invalid token:
Before: `Error: error decoding response body: expected value at line 1 column 1 (code=0)`
After: `Error: Unknown error after making RPC call. Code: 0. Error: "InvalidToken"  (code=500)`
Closes

fix: propagate RPC error messages

---

src/chain/mod.rs
src/chain_sync/network_context.rs
src/daemon/bundle.rs
src/db/car/forest.rs
src/db/car/plain.rs
src/libp2p/chain_exchange/message.rs
src/libp2p/chain_exchange/provider.rs
src/networks/actors_bundle.rs
src/rpc/state_api.rs
src/tool/subcommands/archive_cmd.rs
src/tool/subcommands/benchmark_cmd.rs
src/tool/subcommands/car_cmd.rs
src/utils/db/car_stream.rs
src/utils/db/car_util.rs

Part of https://github.com/ChainSafe/forest/issues/3861
As per the [IPLD CAR doc](https://ipld.io/specs/transport/car/carv1/#constraints)
> The roots array must contain one or more CIDs, each of which should be present somewhere in the remainder of the CAR.
- use NonEmpty type for car roots
- change `roots[0]` to `roots.first()`
Closes

fix: use NonEmpty type for car roots

---

CHANGELOG.md
src/utils/io/progress_log.rs

- Divide by `time_in_seconds` to get the real progress in units per second.
Closes

fix: progress rates were overcounted by 5x

---

src/chain_sync/chain_muxer.rs

The previous fix in https://github.com/ChainSafe/forest/pull/3914 assumes it's sufficient to check only the first block, but we are still seeing timed-out CI jobs stuck in `sync wait`. This PR changes the logic to check all blocks
- check all blocks are within clock drift in `evaluate_network_head`
Closes

fix: check if all blocks are within clock drift in `evaluate_network_head`

---

Cargo.lock
Cargo.toml
rust-toolchain.toml
src/utils/reqwest_resume/tests.rs

- updated Rust toolchain to 1.76.0
- removed `const-random` dependency; the macro started blowing up after the update, most likely to be resolved via https://github.com/tkaitchuck/constrandom/pull/33. The resulting code ended up more straightforward anyway.
Closes

update rust toolchain to 1.76

---

src/interpreter/fvm4.rs
src/networks/butterflynet/mod.rs
src/networks/calibnet/mod.rs
src/networks/devnet/mod.rs
src/networks/mainnet/mod.rs
src/networks/mod.rs
src/state_migration/mod.rs
src/state_migration/nv17/migration.rs
src/state_migration/nv17/miner.rs
src/state_migration/nv18/migration.rs
src/state_migration/nv19/migration.rs
src/state_migration/nv21/migration.rs
src/state_migration/nv21/miner.rs
src/state_migration/nv21fix/migration.rs
src/state_migration/nv21fix2/migration.rs
src/state_migration/tests/mod.rs

- move height infos to a map, to avoid indexing errors and/or the need to declare all the heights for the network logic to work correctly.
- removed heights not used by the current chains
Closes

Move `HeightInfos` to a `HashMap`

---

src/cli_shared/cli/client.rs
src/cli_shared/cli/mod.rs

- `--token` doesn't make sense it the daemon context (it does from the `forest-cli`, though). It was unused anyway.
Closes https://github.com/ChainSafe/forest/issues/2076

remove unused token param from deamon

---

documentation/src/environment_variables.md

- fix incorrect keystore phrase environmental variable name in the docs, see: https://github.com/ChainSafe/forest/blob/11b21eebf872ca22b3860b3a174eac856662d6c3/src/key_management/keystore.rs#L34
Closes

fix incorrect keystore phrase env

---

CHANGELOG.md
src/libp2p/keypair.rs
src/tool/subcommands/shed_cmd.rs
tests/tool_tests.rs

- added ` forest-tool shed peer-id-from-key-pair`
```
❯ forest-tool shed peer-id-from-key-pair ~/.local/share/forest/libp2p/keypair
12D3KooWArH4uiryCt2etoPU9gbQ7nToLWvDGPL1emC6m7ZsXUSk
```
Closes

add keypair to peerid command

---

CHANGELOG.md
Cargo.lock
Cargo.toml
documentation/src/SUMMARY.md
documentation/src/backups.md
src/cli_shared/cli/mod.rs
src/cli_shared/mod.rs
src/tool/main.rs
src/tool/subcommands/backup_cmd.rs
src/tool/subcommands/db_cmd.rs
src/tool/subcommands/fetch_params_cmd.rs
src/tool/subcommands/mod.rs
src/wallet/subcommands/wallet_cmd.rs
tests/tool_tests.rs

- added `forest-tool backup` to abstract away the process of making backups for Forest.
- minor refactoring around the interfaces I stumbled upon.
Closes https://github.com/ChainSafe/forest/issues/3981

add backup tool

---

scripts/tests/calibnet_kademlia_check.sh

In the current kademlia test, a forest node is bootstrapped with another forest node, and exit when more peers get connected. This PR extends the test to make sure the forest node can re-sync
- run cli sync wait in kad test
CI log: https://github.com/ChainSafe/forest/actions/runs/8047437734/job/21976975078?pr=3989#step:7:1127
```
2024-02-26T10:44:00.408135Z  INFO forest_filecoin::chain_sync::tipset_syncer: Successfully synced tipset range: [1387259, 1387260]
Worker: 0; Base: 1387259; Target: 1387260; (diff: 1)
State: complete; Current Epoch: 1387260; Todo: 0
Done!
```
Closes

fix(test): run cli sync wait in kad test

---

build/bootstrap/mainnet

- PL-managed bootstrap nodes were decommissioned, see https://github.com/filecoin-project/lotus/pull/1149
Closes

remove decomissioned PL-managed bootstrap nodes

---

Cargo.lock
Cargo.toml

- Forest fails to connect to more strict bootstrap peers. This change permits upgrading the connections to encrypted ones (to my understanding):
```
2024-02-27T12:11:47.625785Z DEBUG Transport::dial{address=/dns4/bootstrap-venus.mainnet.filincubator.com/tcp/8888/p2p/QmQu8C6deXwKvJP2D8B6QGyhngc3ZiDnFzEHBDx8yeBXST}: multistream_select::dialer_select: Dialer: Received confirmation for protocol: /noise
2024-02-27T12:11:47.894584Z DEBUG Transport::dial{address=/dns4/bootstrap-venus.mainnet.filincubator.com/tcp/8888/p2p/QmQu8C6deXwKvJP2D8B6QGyhngc3ZiDnFzEHBDx8yeBXST}: libp2p_identity::keypair: support for RSA was disabled at compile-time
2024-02-27T12:11:47.894605Z DEBUG Transport::dial{address=/dns4/bootstrap-venus.mainnet.filincubator.com/tcp/8888/p2p/Q …
```

enable rsa feature for libp2p

---

Cargo.lock

To fix build warning
```
warning: package `bumpalo v3.15.0` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```
- `cargo update -p bumpalo`
Closes

fix(deps): upgrade bumpalo from yanked verson

---

scripts/tests/calibnet_no_discovery_check.sh

`/dns4/bootstrap-0.calibration.fildev.network/tcp/1347/p2p/12D3KooWCi2w8U4DDB9xqrejb5KYHaQv2iA2AJJ6uzG3iQxNLBMy` has been inaccessible for a while, causing CI test stuck. Use `calib` instead that is shared in all hostnames
```
/dns4/bootstrap-0.calibration.fildev.network/tcp/1347/p2p/12D3KooWCi2w8U4DDB9xqrejb5KYHaQv2iA2AJJ6uzG3iQxNLBMy
/dns4/bootstrap-1.calibration.fildev.network/tcp/1347/p2p/12D3KooWDTayrBojBn9jWNNUih4nNQQBGJD7Zo3gQCKgBkUsS6dp
/dns4/bootstrap-2.calibration.fildev.network/tcp/1347/p2p/12D3KooWNRxTHUn8bf7jz1KEUPMc2dMgGfa4f8ZJTsquVSn3vHCG
/dns4/bootstrap-3.calibration.fildev.network/tcp/1347/p2p/12D3KooWFWUqE9jgXvcKHWieYs9nhyp6NF4ftwLGAHm4sCv73jjK
/dns4/calibration.node.glif.io/tcp/1237/p2p/12D3KooWQPYouEAsUQKzvFUA9sQ8tz4rfpqtTzh2eL6USd9bwg7x …
```

fix(ci): check against a more stable live node in no discovery check

---

CHANGELOG.md
src/daemon/db_util.rs
src/db/car/many.rs

- Query ParityDB first
- Read-only CAR files are sorted by heaviest tipset
Closes
To exercise some load, I've imported 44 diff calibnet car files and done a simple export.
`forest-cli snapshot export -t 1395675 -d 900`
| branch | elapsed time |
| - | - |
| main | 92s |
| db-query-optim | 60s |

Query DB optims

---

scripts/devnet/.env

This PR uses a lotus-devnet image built from feat/nv22 branch of lotus instead of a custom branch since https://github.com/filecoin-project/lotus/pull/11632 has been merged.
https://github.com/ChainSafe/forest/actions/runs/8090295814/job/22107558133#step:7:1109
```
#11 [lotus-builder 4/5] RUN git clone --depth 1 --branch feat/nv22 https://github.com/filecoin-project/lotus.git .
```
- update lotus devnet image tag
Closes

chore(ci): update lotus-devnet image in devnet checks

---

CHANGELOG.md
src/cli_shared/cli/mod.rs

As part of https://github.com/ChainSafe/forest/issues/3990
This PR allows overriding p2p listening addresses via CLI options, which is easier than using a config file. The next step is updating `forest-iac` to publicly expose the p2p addresses of forest nodes to allow accepting connections from new peers, to improve discoverability and connectivity.
- Add `--p2p-listen-address` CLI option to `forest` daemon
- (To specify multiple addresses, `--p2p-listen-address A --p2p-listen-address B`)
Closes

feat(daemon): add `--p2p-listen-address` arg to `forest`

---

scripts/tests/calibnet_db_migration.sh
src/db/migration/migration_map.rs

This PR tries to omit void migrations in the migration map definition by automatically generating void migrations when necessary. 
- omit void (db) migrations
CI log https://github.com/ChainSafe/forest/actions/runs/8111423534/job/22170964108?pr=4017#step:6:126
```
2024-03-01T12:45:09.467017Z  INFO forest_filecoin::db::migration::db_migration: Migrating database from version 0.12.0 to 0.16.8
2024-03-01T12:45:09.467063Z  INFO forest_filecoin::db::migration::migration_map: Migrating database from version 0.12.0 to 0.12.1
2024-03-01T12:45:09.467104Z  INFO forest_filecoin::db::migration::void_migration: copying old database from /tmp/tmp.NlKDjKNEXj/data_dir/calibnet/0.12.0 to /tmp/tmp.NlKDjKNEXj/data_dir/calibnet/migration_0_12_0_0_12_1 …
```

feat: omit void (db) migrations

---

CHANGELOG.md
src/rpc/channel.rs

After canceling a subscription, a WebSocket client would still get stale responses.
- Fix Forest sending stale notifications after channel cancelation
- Add debug traces
If you enable debug traces you shoud now see something like:
```
...
2024-03-01T15:47:19.338708Z  INFO filecoin_proofs::api::winning_post: verify_winning_post:finish    
2024-03-01T15:47:19.363249Z DEBUG forest_filecoin::rpc::channel: sending notification {"jsonrpc":"2.0","method":"xrpc.ch.val","params":[0,{"Type":"apply","Val":[{"Miner":"t017387","Ticket":{"VRFProof":"llZkMUVsIkbv8BJdM5jeE4qqA+3oR6K+QMHqnpikTLCNo7UZ2bJpoCdhYJm/TxWzFbEhahaNXukBbVz1O4keo7YRteUMbn6i34wZ3I1OWrSz/G1klGnE9Ium7oMxrz3A"},...}
2024-03-01T15:47:19.364928Z  INFO forest_filecoin::chain_sync::tipset_syncer: …
```

Fix notification task not properly ended

---

src/libp2p/behaviour.rs
src/libp2p/discovery.rs
src/libp2p/service.rs
src/rpc/mod.rs
src/rpc/net_api.rs
src/rpc_api/mod.rs
src/rpc_client/net_ops.rs
src/tool/subcommands/api_cmd.rs

- implement `Filecoin.NetAutoNatStatus`
```console
Running `target/debug/forest-tool api compare --filter NetAuto`
| RPC Method                | Forest | Lotus |
|---------------------------|--------|-------|
| Filecoin.NetAutoNatStatus | Valid  | Valid |
```
Closes

feat(rpc): implement Filecoin.NetAutoNatStatus

---

src/blocks/tipset.rs
src/cid_collections/small_cid_vec.rs
src/ipld/util.rs

- Implement `fn TipsetKey::iter`
Closes https://github.com/ChainSafe/forest/issues/4024

feat: make TipsetKey iterable

---

Cargo.toml

nit: `libp2p` could be cleaned up from dev-deps
_Originally posted by @hanabi1224 in https://github.com/ChainSafe/forest/pull/4033#discussion_r1521518536_
- cleanup libp2p from dev-dependencies
Closes

fix(deps): cleanup libp2p from dev-dependencies

---

CHANGELOG.md
src/cli/subcommands/net_cmd.rs
src/rpc_api/mod.rs
src/rpc_client/net_ops.rs

Follow up of https://github.com/ChainSafe/forest/pull/4039
- Add  `forest-cli net reachability` command (compatible with `lotus net reachability`) that prints information about reachability from the internet.
```console
➜  lotus git:(master) FULLNODE_API_INFO="/ip4/64.226.122.57/tcp/2345/http" lotus net reachability
2024-03-13T14:15:03.689+0800    WARN    cliutil util/apiinfo.go:94      API Token not set and requested, capabilities might be limited.
AutoNAT status:  Public
Public address: [/ip4/64.226.122.57/tcp/12345]
➜  forest git:(main) ✗  FULLNODE_API_INFO="/ip4/64.226.122.57/tcp/2345/http" cargo run --bin forest-cli -- net reachability
Compiling forest-filecoin v0.17.0 (/home/me/git/forest)
Finished dev [unoptimized] target(s) in 38.39s …
```

feat(cli): forest-cli net reachability

---

src/ipld/util.rs
src/tool/subcommands/benchmark_cmd.rs

- implemented `PinnedDrop` for `UnorderedChainStream` to make sure we cleanup automatically. 
- avoid worker panics when `UnorderedChainStream` is dropped, there is no need to panic when the receiver channel is closed.
- removed redundant `join_workers` method as we are cleaning up in `Drop`. 
- improved `into_seen` implementation to work properly with `Drop` and avoiding `Arc` nuances. 
Closes #3991 

[Fix] Implement Drop for UnorderedChainStream and handle send errors.

---

scripts/tests/calibnet_offline_rpc_check.sh
scripts/tests/test_data/calibnet_block_3000.json
src/cli/subcommands/chain_cmd.rs

- fixes the output of the `forest-cli chain block` command, and ensures such regressions are caught in the future.
Previous output:
```
forest-cli chain block -c bafy2bzacedj4d4ceekbwcvyfokf5u5o6utbf7s4ovoltocdzdbrcdcfkll3q6                                                                                                                                                                                     14:05:00 [892/992]
[
[
0,
234,
7                                                                                                                                                                                                                                                                                                                             ],
[ …
```

fix `forest-cli chain block` output

---

CHANGELOG.md
src/rpc/chain_api.rs

- Send head changes as an array.
Unfortunately, we don't have a way of testing the `chain_notify` channel yet. That will be part of a later PR.
Closes #4069

fix: head changes should always be sent as an array

---

CHANGELOG.md
src/cli_shared/logger/mod.rs
src/libp2p/mod.rs
src/libp2p/ping.rs
src/tool/main.rs
src/tool/subcommands/mod.rs
src/tool/subcommands/net_cmd.rs

- implement `forest-tool net ping` command that is similar to `lotus net ping` but does not require a running forest/lotus daemon
Local run:
```
➜  forest git:(main) ✗ cargo run --bin forest-tool -- net ping /ip4/108.62.52.130/udp/50374/quic-v1/p2p/12D3KooWHevRB9VCfQYSm12ZFExsrSpKmQKYegJ4WiPPmLNUmW6j
Compiling forest-filecoin v0.17.0 (/home/me/git/forest)
Finished dev [unoptimized] target(s) in 37.29s
Running `target/debug/forest-tool net ping /ip4/108.62.52.130/udp/50374/quic-v1/p2p/12D3KooWHevRB9VCfQYSm12ZFExsrSpKmQKYegJ4WiPPmLNUmW6j`
PING /ip4/108.62.52.130/udp/50374/quic-v1/p2p/12D3KooWHevRB9VCfQYSm12ZFExsrSpKmQKYegJ4WiPPmLNUmW6j
Pong received: time=278ms
Pong received: time=243ms
Pong received: time=280ms
Pong received: time=248ms
Pong …
```

feat(tool): forest-tool net ping

---

.config/forest.dic
src/rpc/chain_api.rs
src/rpc/mod.rs
src/rpc/reflect/mod.rs
src/rpc/snapshots/forest_filecoin__rpc__tests__openrpc.snap

Iteration on #4033.
This approach obviates the need to define client operations separately:
https://github.com/ChainSafe/forest/blob/d0b490e7889157c668c1e3f4f96416fb093cf1c9/src/rpc_client/chain_ops.rs
In the limit, `src/rpc_client` can be deleted.
- #4054, better to get this in first and _then_ start rewriting handlers.
- #4038 
- #4032
- #4066 

feat: trait RpcMethod for server, client, and schema

---

src/rpc_client/net_ops.rs

`StateMinerAvailableBalance` is a v0 method. (When methods are available in both V0 and V1, we should use V0.)
_Originally posted by @lemmih in https://github.com/ChainSafe/forest/pull/4061#discussion_r1526028915_
- call `/rpc/v0` endpoint for `Filecoin.NetAutoNatStatus`
Closes
https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v0-methods.md#netautonatstatus

fix(rpc): Filecoin.NetAutoNatStatus should be v0 API

---

Cargo.lock
Cargo.toml
src/rpc/mod.rs
src/rpc/state_api.rs
src/rpc_api/data_types.rs
src/rpc_api/mod.rs
src/rpc_client/state_ops.rs
src/tool/subcommands/api_cmd.rs

~Blocked on https://github.com/ChainSafe/fil-actor-states/pull/267~
- Implement V0 RPC method `Filecoin.StateMarketStorageDeal`
- Api compare tests
Test output (with `fil-actor-states` on https://github.com/ChainSafe/fil-actor-states/pull/267 branch)
```
➜  forest git:(hm/rpc-state-market-storage-deal) ✗ cargo run --bin forest-tool -- api compare --filter StateMarket ~/fr/
snapshots/calibnet/forest_snapshot_calibnet_2024-03-19_height_1450304.forest.car.zst
Finished dev [unoptimized] target(s) in 0.39s
Running `target/debug/forest-tool api compare --filter StateMarket /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-03-19_height_1450304.forest.car.zst`
| RPC Method                            | Forest | Lotus | …
```

feat(rpc): implement Filecoin.StateMarketStorageDeal

---

CHANGELOG.md
src/networks/calibnet/mod.rs

Our `get_fil_vested` function returned an incorrect amount compared to Lotus, leading to the failure of this RPC method on calibnet.
The `get_fil_vested` uses the `Liftoff` upgrade height in its computation, but height 0 was taken instead of -5.
This is likely a regression coming from PR (https://github.com/ChainSafe/forest/pull/3950).
- Add back `Liftoff` entry in calibnet schedule
```console
$ RUST_LOG=forest_filecoin::rpc_client=debug ./target/debug/forest-tool api compare --lotus /ip4/127.0.0.1/tcp/1234/http --forest /ip4/127.0.0.1/tcp/2345/http forest_snapshot_calibnet_2024-03-18_height_1448006.forest.car.zst --filter StateVMCirculatingSupplyInternal -n 1
2024-03-19T12:18:47.742155Z DEBUG forest_filecoin::rpc_client: Using JSON-RPC v2 HTTP …
```

Fix `Filecoin.StateVMCirculatingSupplyInternal`

---

CHANGELOG.md
scripts/tests/api_compare/filter-list

- `Filecoin.StateCall` is still flaky. Don't test it until fixed.
Closes

ci: mark `StateCall` as flaky

---

Cargo.lock
Cargo.toml
rust-toolchain.toml
src/beacon/signatures/tests.rs
src/cli/subcommands/attach_cmd.rs
src/ipld/util.rs
src/message_pool/msg_chain.rs

- bump rust toolchain to 1.77.0
- retire `async-recursion` crate
Closes
https://releases.rs/docs/1.77.0/

chore(toolchain): bump rust toolchain to 1.77.0

---

scripts/tests/api_compare/filter-list

- `Filecoin.StateSectorGetInfo` is failing. Disable testing until it has been fixed.
Closes

ci: mark `StateSectorGetInfo` as flaky

---

scripts/tests/calibnet_offline_rpc_check.sh
src/cli/subcommands/auth_cmd.rs
src/daemon/mod.rs
src/rpc/error.rs
src/rpc/mod.rs
src/rpc_client/mod.rs
src/tool/subcommands/api_cmd.rs
src/tool/subcommands/shed_cmd.rs

- make `crate::rpc::error::JsonRpcError` public
- remove `crate::rpc_client::JsonRpcError` in favour of the above
- remove `crate::rpc_client::JsonRpcResponse` in favour of `jsonrpsee::types::Response`
Risks:
- Changes to output of API check commands.
- I've tried to emulate the old behaviour where possible.
Closes

refactor: remove duplicate JsonRpcError and Request objects

---

src/rpc/mod.rs
src/rpc/reflect/mod.rs
src/rpc/sync_api.rs

- Move to `RpcModule::from_arc` constructor to avoid double indirection
Closes #4007

Remove one level of Arc in Ctx

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/networks/actors_bundle.rs
src/networks/calibnet/mod.rs
src/networks/mod.rs
src/state_migration/mod.rs
src/state_migration/nv22fix/migration.rs
src/state_migration/nv22fix/mod.rs

- add NV22 fix upgrade,
- manually tested post-migration conformance with Lotus.
Forest:
```
2024-03-27T14:45:19.127400Z  INFO compute_tipset_state_blocking: forest_filecoin::state_migration: State migration at height DragonFix(epoch 1473980) was successful, Previous state: bafy2bzacea4gv5rrhavhsxfwvtd6xdbktcc34h75s4puu3bdjyzmn36gqt4w4, new state: bafy2bzaceby523wwqi5pdel7waavlkre55fb2ibvzelpkrx2igujcpdj2kq6g, new state actors: bafy2bzacebmbknorvnryliwnjeclqgukabceqccwxjkpsfdn66wzu2vqbkauy. Took: 0.5127817s.
```
Lotus:
```
2024-03-27T15:16:03.112+0100    WARN    statemgr        stmgr/forks.go:206      COMPLETED migration     {"height": "1473980", "from": "bafy2bzacea4gv5rrhavhsxfwvtd6xdbktcc34h75s4puu3bdjyzmn36gqt4w4", "to": …
```

calibnet dragon fix

---

scripts/tests/api_compare/docker-compose.yml

There's some race condition in the current setup where `lotus chain sethead` does not work properly. 
- run `lotus chain sethead` right after `lotus sync wait` to make sure it's not in middle of a sync so that it re-validates tipsets since the new head (to generate the missing message receipts for RPC tests)
Closes

fix(test): improve rpc test stability

---

Cargo.toml

Currently, editing files under those irrelevant folders results in rebuilding (or at least re-linking) the forest binaries.  This PR excludes them in `Cargo.toml` config
The `cargo-publish-dry-run` CI job should prove the correctness of the change
-
Closes

fix: cargo exclude irrelevant folders

---

Cargo.lock

Addresses
```
Crate:     h2
Version:   0.3.25
Title:     Degradation of service in h2 servers with CONTINUATION Flood
Date:      2024-04-03
ID:        RUSTSEC-2024-0332
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0332
Solution:  Upgrade to ^0.3.26 OR >=0.4.4
```
Closes

cargo update h2

---

Cargo.lock
src/rpc/auth_layer.rs
src/rpc/chain_api.rs
src/rpc/mod.rs
src/rpc/mpool_api.rs
src/rpc/snapshots/forest_filecoin__rpc__tests__openrpc.snap
src/rpc/types.rs
src/rpc_client/mpool_ops.rs

I need a full API example to continue prototyping the client.
The mpool API is ideal for this:
- relatively small
- used in `forest-tool api compare`
- used in `forest-cli` subcommands
- See title
#4032 

refactor: migrate mpool_api to use trait RpcMethod

---

CHANGELOG.md
src/cli/subcommands/net_cmd.rs
src/rpc_client/mod.rs

- Fixes `forest-cli net agent --version`
Before:
```
❯ forest-cli net peers --agent
2024-04-04T13:23:22.785489Z ERROR forest_filecoin::rpc_client: Failure: ErrorObject { code: InternalError, message: "item not found", data: None }
JSON-RPC request URL: http://127.0.0.1:2345/rpc/v0, payload: {"jsonrpc":"2.0","id":0,"method":"Filecoin.NetAgentVersion","params":["12D3KooWJfKFjE7ZEEx9DQRETWnMe9iiDMYavWMgfbBe6456Cw2x"]}
2024-04-04T13:23:22.785552Z ERROR forest_filecoin::rpc_client: Failure: ErrorObject { code: InternalError, message: "item not found", data: None }
JSON-RPC request URL: http://127.0.0.1:2345/rpc/v0, payload: {"jsonrpc":"2.0","id":0,"method":"Filecoin.NetAgentVersion","params":["12D3KooWE46Q9NivpjELBV42VYNt7xS41vce9PNte2vEMbBg2LmA"]} …
```

fix agent version cli

---

src/chain_sync/chain_muxer.rs

This PR tries to address an issue that `forest-cli sync wait` sometimes takes very long to exit by letting the node enter FOLLOW mode sooner when it's appropriate.  CI jobs that run `forest-cli sync wait` should also benefit from this change.
- 
Closes https://github.com/ChainSafe/forest/issues/4136

fix: ChainMuxer sometimes does not enter FOLLOW mode when it should

---

src/networks/mainnet/mod.rs

To align with https://github.com/filecoin-project/lotus/pull/11849/files#diff-66472237d88b30902ef59e70f35d1314a9f11e04e093a927dec9cf04f8d2bf75L103
See https://filecoinproject.slack.com/archives/C05P37R9KQD/p1712548103521969
- Update dragon upgrade epoch on mainnet to 3855360
Closes

fix: delay dragon upgrade on mainnet

---

Cargo.lock
Cargo.toml
src/networks/actors_bundle.rs
src/rpc_client/mod.rs
src/utils/reqwest_resume/mod.rs
src/utils/reqwest_resume/tests.rs

- bump reqwest to 0.12
- retire http 0.2
Closes

chore(deps): bump reqwest to 0.12 and retire http 0.2

---

scripts/devnet/.env
scripts/devnet/lotus.dockerfile

- bump lotus-devnet image from `1.26.0` to `1.26.1`
Closes

fix(ci): bump lotus-devnet image to 1.26.1

---

scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline

- no mercy for flaky methods
- it failed in https://github.com/ChainSafe/forest/actions/runs/8619017774/job/23623141130?pr=4170 (and I recall some other PR).
```
| Filecoin.EthSyncing                             | Valid  | Valid               |
| Filecoin.MpoolGetNonce (12)                     | Valid  | InternalServerError |
| Filecoin.MpoolGetNonce (8)                      | Valid  | Valid               |
| Filecoin.MpoolPending                           | Valid  | Valid               |
```
Closes

disable flaky MpoolGetNonce

---

.config/forest.dic
CHANGELOG.md
documentation/src/environment_variables.md
src/utils/proofs_api/paramfetch.rs

- by default, use self-hosted proof parameters. In case of errors (or if forced by an environmental variable), fall back to the IPFS gateway. This should resolve numerous issues with the slow download and knocking out our GH jobs.
Even in good conditions, it's faster:
```
❯ export FOREST_PROOFS_ONLY_IPFS_GATEWAY=1
❯ time forest-tool fetch-params --keys
________________________________________________________
Executed in   11.83 secs      fish           external
usr time  620.09 millis    0.00 micros  620.09 millis
sys time  338.11 millis  276.00 micros  337.83 millis
```
```
❯ export FOREST_PROOFS_ONLY_IPFS_GATEWAY=0
❯ time forest-tool fetch-params --keys
________________________________________________________
Executed in    4.59 secs      fish …
```

self-host proof parameters

---

src/beacon/drand.rs
src/beacon/tests/drand.rs
src/chain/store/index.rs
src/fil_cns/mod.rs
src/fil_cns/validation.rs
src/state_manager/chain_rand.rs
src/state_manager/mod.rs

This PR tries to fix a bug in chained drand verification caught by https://github.com/ChainSafe/forest/pull/4146
[Full CI log](https://productionresultssa10.blob.core.windows.net/actions-results/684fb0a5-cd58-48e6-ad8f-8591e1ea7687/workflow-job-run-db13e6aa-cabf-50ef-864b-9f917373f735/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-09T09%3A35%3A13Z&sig=dsRUhA9Vm7Ai09vBJg8G9%2FlTgLArJfRZAXAK9IJrwao%3D&sp=r&spr=https&sr=b&st=2024-04-09T09%3A25%3A08Z&sv=2021-12-02)
Basically, when blocks of a certain height are not mined (in this case, height 18 is missing)
In lotus miner log, we see
```
mined new block	{"cid": "bafy2bzaced3zy2fcdpyfqha4zaqrv5s5bjgjpvdwhmg3ltnp2ha5etkvl222s", "height": 17
...
mined new block	{"cid": "bafy2bzacedicxuinvpb4yihvxgc73bfnyttvkzopp4x3nji3pxbu5x4pbrkp4", …
```

fix: drand verification logic and block validation logic

---

scripts/devnet/docker-compose.yml
scripts/tests/api_compare/docker-compose.yml

- fixes a warning in logs
```
WARN[0000] /home/rumcajs/prj/forest/scripts/devnet/docker-compose.yml: `version` is obsolete
```
Closes

remove deprecated compose version

---

CHANGELOG.md
src/cli_shared/cli/client.rs
src/cli_shared/cli/mod.rs
src/daemon/mod.rs
tests/common/mod.rs
tests/import_snapshot_tests.rs

- re-enabled `importing_bad_snapshot_should_fail` - I was not able to reproduce the failure, if it happens again let's investigate it.
- simplified common conditions for tests, so that no servers are started by default (might help with some flakiness)
- added a flag to disable healthcheck
- :warning: Breaking change. Removed shorthand flags from `forest`. They were not helpful; someone seeing `forest -n` might have been surprised it runs Forest with disabled metrics.
Closes https://github.com/ChainSafe/forest/issues/3449

`--no-healthcheck`, no shorthands and test necromancy

---

src/rpc/client.rs
src/rpc/mod.rs

- Some tests were failing on client-side; payload size was too large for the default 10 MiB. Likely, in the future, this should be configurable, though a sane default is more important.
- merge before https://github.com/ChainSafe/forest/pull/4199
```
2024-04-15T15:30:45.109455Z DEBUG forest_filecoin::tool::subcommands::api_cmd: err=ServerError { inner: ErrorObject { code: InternalError, message: "The HTTP message was too big", data: None } }
```
Closes

increase RPC max req/resp size

---

scripts/tests/api_compare/docker-compose.yml
src/tool/subcommands/api_cmd.rs

- add basic debugging capabilities to `api compare`, so that we're not completely blind when encountering an error in, e.g., CI.
- I expect one RPC endpoint to fail here, so https://github.com/ChainSafe/forest/pull/4201 is a blocker.
```
api-compare-1          | Request: RpcRequest { method_name: "Filecoin.BeaconGetEntry", params: Array [Number(10101)], result_type: PhantomData<serde_json::value::Value>, api_version: V0, timeout: 60s }
api-compare-1          | Forest response: {
api-compare-1          |   "Data": "jrcsjrAwyZTEj+SJbhlQgB/o3dcqWY30AMCHiQ1KyQLfFqs2AQPLroE4WJl4Y05eDZSn6t5dGidL09Lz1FS8xL6yhhaMygPKnRhSaC0QISbi57+gtmf4OVWarqvyhJ20",
api-compare-1          |   "Round": 2406587
api-compare-1          | }
api-compare-1          | Lotus …
```

add debugging tooling for api-compare

---

src/message_pool/config.rs
src/message_pool/mod.rs
src/message_pool/msg_chain.rs
src/message_pool/msgpool/mod.rs
src/message_pool/msgpool/selection.rs
src/rpc/auth_layer.rs
src/rpc/methods/mpool.rs
src/rpc/snapshots/forest_filecoin__rpc__tests__openrpc.snap
src/tool/subcommands/api_cmd.rs

- Expose `select_messages`, which was hidden behind `#[cfg(test)]`.
- Test schema of `MpoolSelect` against Lotus.
Closes #4196 

feat(rpc): implement `MpoolSelect`

---

src/rpc/methods/gas.rs

- Multiply by gas estimates by 1.25 (`GAS_LIMIT_OVERESTIMATION`).
This fixes a bug introduced in #4187, which prevented us from sending funds.
Closes

fix: add 25% to gas estimations

---

src/db/car/forest.rs

- Resolve a comment `// This unnecessarily copies the zstd frame. :(` in `fn decode_zstd_single_frame`
Closes

fix: avoid unnecessarily copies in decode_zstd_single_frame

---

src/cli/subcommands/chain_cmd.rs
src/cli/subcommands/mod.rs

- constrain `print_pretty_json` with `T: HasLotusJson` to avoid breakage of the output format
- rename `print_pretty_json` to `print_pretty_lotus_json` to avoid confusion
Closes

fix: constrain print_pretty_json with T: HasLotusJson to avoid breakage

---

.github/workflows/rpc_test_repeat.yml

- introduces a cron/on-demand workflow to spawn 100 parallel RPC tests in order to flush out  flakiness from the Forest's RPC world.
Closes

rpc tests on demand

---

CHANGELOG.md
src/rpc/auth_layer.rs
src/rpc/client.rs

- align JWT usage with Lotus (and in general JSON Web Token specification) - header values shall include the `Bearer` prefix. This is necessary, e.g., for the `api compare` to support sending `write` tokens to Lotus, see [Go JSON-RPC authorization handling](https://github.com/filecoin-project/go-jsonrpc/blob/17a35772b24f59ceee25cc8d8177a2b255a659ac/auth/handler.go#L29-L33).
- Added some tests to untested code.
Closes

handle bearer token

---

CHANGELOG.md
src/rpc/client.rs

- Decrease `request_timeout` value in `WsClientBuilder` and `HttpClientBuilder` to avoid panics (see logs below)
Rational:
We don't need to handle timeouts at the `jsonrpsee` client level since we shim our own timeouts during the call, but setting it to some max value seems unsafe.
Setting a 10s timeout and simulating a slow endpoint in forest daemon:
```console
$ FOREST_RPC_DEFAULT_TIMEOUT=10 ./forest-tool api compare --lotus /ip4/127.0.0.1/tcp/1234/ws --forest /ip4/127.0.0.1/tcp/2345/ws forest_snapshot_calibnet_2024-04-19_height_1539740.forest.car.zst --filter EthChainId
Request dump: RpcRequest { method_name: "Filecoin.EthChainId", params: Null, result_type: PhantomData<serde_json::value::Value>, api_version: V1, timeout: 10s }
Request params …
```

Decrease `request_timeout` in builders to avoid panics

---

src/rpc/methods/chain.rs
src/rpc/methods/eth.rs
src/rpc/methods/state.rs
src/shim/machine/manifest.rs
src/state_manager/circulating_supply.rs
src/state_manager/mod.rs
src/state_migration/common/macros/verifier.rs
src/state_migration/nv17/migration.rs
src/state_migration/nv17/miner.rs
src/state_migration/nv18/eam.rs
src/state_migration/nv18/eth_account.rs
src/state_migration/nv18/init.rs
src/state_migration/nv19/miner.rs
src/state_migration/nv19/power.rs
src/state_migration/nv21/migration.rs
src/state_migration/nv21/miner.rs
src/state_migration/nv21fix/migration.rs
src/state_migration/nv21fix2/migration.rs
src/state_migration/nv22/market.rs
src/state_migration/nv22/migration.rs
src/state_migration/nv22/miner.rs
src/state_migration/nv22fix/migration.rs
src/state_migration/type_migrations/miner/state_v10_to_v11.rs
src/state_migration/type_migrations/miner/state_v8_to_v9.rs
src/statediff/resolve.rs
src/utils/db/mod.rs

- simplify `CborStore::get_cbor(params)?.context(params)?` with `CborStore::get_cbor_required(params)?`
- simplify `StateManager::get_actor(params)?.context(params)?` with `StateManager::get_required_actor(params)?`
Closes

chore: use `fn get_required_*` to avoid uninformative `<Option as anyhow::Context>::context` calls

---

src/rpc/methods/miner.rs
src/rpc/methods/state.rs
src/rpc/methods/state/types.rs
src/rpc/types/mod.rs
src/state_manager/mod.rs

- `MinerGetBaseInfo` was incorrectly in the `state` module, though it should be in the `miner` https://github.com/filecoin-project/lotus/blob/082a9159ced1f6bd7e8fa77064a51d209324b693/documentation/en/api-v0-methods.md#miner
Closes

move `MinerGetBaseInfo` to miner module

---

CHANGELOG.md
scripts/tests/api_compare/.env
scripts/tests/api_compare/docker-compose.yml
src/rpc/methods/wallet.rs
src/tool/subcommands/api_cmd.rs

- exposed worker address as part of the `api-compare`,
- fixed `Filecoin.WalletSign` endpoint and introduce a conformance test
Closes

fix: double base64 decoding in `Filecoin.WalletSign`

---

src/rpc/methods/state.rs

- the `Filecoin` prefix got introduced again, probably caused by a conflict. Using `Forest` again.
Closes

fix: rename `Filecoin.StateFetchRoot` to `Forest.StateFetchRoot` again

---

src/cid_collections/hash_set.rs
src/rpc/methods/eth.rs
src/tool/subcommands/api_cmd.rs

- Implement RPC method `Filecoin.EthGetBlockTransactionCountByNumber`
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-05-09_height_1597054.forest.car.zst --filter EthGetBlockTransactionCountByNumber`
| RPC Method                                        | Forest | Lotus |
|---------------------------------------------------|--------|-------|
| Filecoin.EthGetBlockTransactionCountByNumber (10) | Valid  | Valid |
```
Closes https://github.com/ChainSafe/forest/issues/4307

feat(rpc): implement Filecoin.EthGetBlockTransactionCountByNumber

---

src/rpc/auth_layer.rs
src/rpc/methods/msig.rs
src/rpc/methods/state.rs
src/rpc/mod.rs
src/rpc/types/mod.rs
src/shim/actors/mod.rs
src/shim/actors/multisig.rs
src/shim/actors/multisig/state.rs
src/tool/subcommands/api_cmd.rs

- Implemented `Filecoin.MsigGetVested` and `Filecoin.MsigGetVestingSchedule` RPC method 
- Moved `Filecoin.MsigGetAvailableBalance` and `Filecoin.MsigGetPending` (10) from `state.rs` to `msig.rs`
```
forest-tool api compare forest_snapshot_calibnet_2024-05-09_height_1597332.forest.car.zst --filter Msig
| RPC Method                            | Forest | Lotus |
|---------------------------------------|--------|-------|
| Filecoin.MsigGetAvailableBalance (10) | Valid  | Valid |
| Filecoin.MsigGetPending (10)          | Valid  | Valid |
| Filecoin.MsigGetVested (10)           | Valid  | Valid |
| Filecoin.MsigGetVestingSchedule (10)  | Valid  | Valid |
```
contributes to https://github.com/ChainSafe/forest/issues/4164
[1]: …

feat(rpc): implement Filecoin.MsigGetVested and Filecoin.MsigGetVestingSchedule

---

.github/workflows/forest.yml
scripts/tests/api_compare/aria2-Dockerfile
scripts/tests/api_compare/docker-compose.yml
scripts/tests/snapshot_parity/docker-compose.yml

The cache step does not work properly on buildjet build agents and is causing timeout in lotus
https://github.com/ChainSafe/forest/actions/runs/9029022947/job/24810699319#step:2:42
```
/usr/bin/tar: ../../../../../var: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../../var/tmp/filecoin-proof-parameters: Cannot mkdir: No such file or directory
```
- drop CI cache
- run `forest-tool fetch-params --keys` in `docker-compose` `init` service
Closes

fix(ci): snapshot parity test: fetch param files on init and drop CI cache

---

CHANGELOG.md
src/chain_sync/chain_muxer.rs

- Forest would sample tipset HEADs from 5 peers before fully joining a network. This obviously doesn't work if there are fewer than 5 peers available. This PR temporarily sets the sample size to 1. The chain muxer is scheduled to be completely re-written soon.
Closes

fix: set tipset sample size to 1

---

CHANGELOG.md
src/chain_sync/chain_muxer.rs
src/chain_sync/validation.rs
src/daemon/mod.rs
src/health/endpoints.rs
src/networks/metrics.rs
src/networks/mod.rs
src/rpc/methods/sync.rs

- added `expected_network_height` metric
Closes https://github.com/ChainSafe/forest/issues/4322

feat: add `expected_network_height` metric

---

scripts/devnet/lotus.dockerfile

When we build a custom lotus branch that references an unpublished version of `filecoin-ffi`(like in #4321), a prebuilt `libfilcrypto` cannot be downloaded and `filecoin-ffi` needs to be rebuilt from source code.
- Install rust toolchain (for building `filecoin-ffi`)
- Set `FFI_USE_BLST_PORTABLE="1"`
- Set `FFI_USE_GPU="0"`
- (See https://github.com/Filecoin-project/filecoin-ffi?tab=readme-ov-file#building-from-source)
Closes

fix(ci): rust build issues in lotus devnet dockerfile

---

src/lotus_json/mod.rs

`LotusJson<Option<T>>` is handled as an optional argument

fix: handle optional parameters

---

.github/workflows/release.yml

- fix MacOS release via aliasing, so no additional dependency is required.
Closes

fix: missing dep macos release

---

src/rpc/methods/state.rs
src/state_manager/circulating_supply.rs
src/state_manager/mod.rs

- implemented FIP-0065 Ignore built-in market locked balance in circulating supply calculation.
Closes
Looking more closely into the networks, I assessed that it needs some rework to facilitate further changes, see more in https://github.com/ChainSafe/forest/issues/4347

feat: FIP-0065 Ignore built-in market locked balance

---

CHANGELOG.md
src/rpc/methods/eth.rs
src/rpc/mod.rs
src/tool/subcommands/api_cmd.rs

- Add `Filecoin.EthGetBlockTransactionCountByHash` RPC method
```console
| RPC Method                                        | Forest | Lotus |
|---------------------------------------------------|--------|-------|
| Filecoin.EthGetBlockTransactionCountByHash (10)   | Valid  | Valid |
```
Closes #4360
Depends on PR https://github.com/ChainSafe/forest/pull/4285

feat(rpc): implement Filecoin.EthGetBlockTransactionCountByHash

---

src/chain_sync/network_context.rs
src/libp2p/peer_manager.rs
src/libp2p/service.rs

(Part of https://github.com/ChainSafe/forest/issues/4346 investigation)
In the previous logic, we mark peers bad when they don't support `Hello` and `ChainExchange` protocols, but it does not make sense to hold connections to those peers and broadcast their addresses via `Kademlia` in the network.
- Ban peers that don't support `Hello` and `ChainExchange` protocols
Closes

fix(p2p): ban peers that don't support hello and chain exchange

---

scripts/devnet/docker-compose.yml
src/blocks/header.rs
src/chain/store/chain_store.rs
src/chain_sync/network_context.rs
src/chain_sync/tipset_syncer.rs
src/libp2p/peer_manager.rs
src/libp2p/ping.rs
src/libp2p/service.rs
src/state_manager/mod.rs

As [discussed on slack](https://chainsafeio.slack.com/archives/C0144LHN732/p1717501294343469)
- demote log levels on peer banning from `warn` to `debug`
- demote verbose debug logs to trace to make output more readable when `RUST_LOG=forest_filecoin=debug`
Closes

fix(log): demote log levels on peer banning

---

scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline
src/lotus_json/actor_state.rs
src/rpc/methods/state/types.rs
src/state_manager/utils.rs

- Fix `Filecoin.StateCall` RPC and re-enable in rpc check
```
forest-tool api compare forest_snapshot_calibnet_2024-05-09_height_1597332.forest.car.zst --filter StateCall
| RPC Method              | Forest | Lotus |
|-------------------------|--------|-------|
| Filecoin.StateCall (27) | Valid  | Valid |
```
Contributes to #4164 

Fix Filecoin.StateCall RPC

---

scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline
src/rpc/methods/chain.rs

- Fix `Filecoin.ChainGetPath` RPC and re-enable in rpc check
```
forest-tool api compare forest_snapshot_calibnet_2024-05-09_height_1597332.forest.car.zst --filter ChainGetPath
| Filecoin.ChainGetPath (10) | Valid  | Valid |
```
Contributes to https://github.com/ChainSafe/forest/issues/4164

Fix Filecoin.ChainGetPath RPC

---

src/health/endpoints.rs
src/libp2p/service.rs
src/message_pool/msgpool/mod.rs
src/rpc/methods/eth.rs
src/rpc/methods/state.rs
src/state_manager/mod.rs
src/state_migration/mod.rs

This PR demotes some `&Arc<T>` parameter types to `&T` when possible
-
Closes

fix: use &T instead of &Arc<T> in parameter types when possible

---

Cargo.lock
Cargo.toml
src/rpc/auth_layer.rs
src/rpc/channel.rs
src/rpc/client.rs
src/rpc/mod.rs
src/rpc/reflect/mod.rs
src/tool/subcommands/api_cmd.rs

- bump `jsonrpsee` version
- refine RPC authorization error message 
Closes #3961 
https://github.com/paritytech/jsonrpsee/releases/tag/v0.23.0

chore(deps): bump jsonrpsee

---

src/libp2p/discovery.rs
src/libp2p/hello/codec.rs
src/libp2p/hello/mod.rs
src/libp2p/service.rs

(Part of https://github.com/ChainSafe/forest/issues/4391 investigation)
In `go-libp2p` and `js-libp2p`, `identify` is a core protocol that other protocols depend on, e.g. [<sup>1</sup>](https://github.com/filecoin-project/lotus/blob/v1.27.0/node/modules/services.go#L73)
```go
pic := evt.(event.EvtPeerIdentificationCompleted)
// We just finished identifying the peer, that means we should know what
// protocols it speaks. Check if it speeks the Filecoin hello protocol
// before continuing.
if p, _ := h.Peerstore().FirstSupportedProtocol(pic.Peer, hello.ProtocolID); p != hello.ProtocolID {
continue
}
```
It turns out in `rust-libp2p`, `identify` is not a core protocol [<sup>2</sup>](https://docs.rs/libp2p/0.53.2/libp2p/identify/index.html) so the `protocol unsupported failure` is not due to …

fix(p2p): handle identify event and check required protocols

---

rust-toolchain.toml
src/chain_sync/chain_muxer.rs
src/libp2p/discovery.rs
src/libp2p/rpc/mod.rs
src/libp2p/service.rs
src/message_pool/msg_chain.rs
src/message_pool/msgpool/msg_pool.rs

- upgrade rust toolchain to [1.79.0](https://releases.rs/docs/1.79.0/)
```
warning: field `0` is never read
--> src/libp2p/rpc/mod.rs:56:8
|
56 |     Io(io::Error),
|     -- ^^^^^^^^^
|     |
|     field in this variant
|
= note: `#[warn(dead_code)]` on by default
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
|
56 |     Io(()),
|        ~~
warning: fields `source` and `request` are never read
--> src/libp2p/service.rs:94:9
|
93 |     HelloRequestInbound {
|     ------------------- fields in this variant
94 |         source: PeerId,
|         ^^^^^^
95 |         request: HelloRequest,
|         ^^^^^^^
warning: field `request_id` is never …
```

chore: bump rust toolchain

---

src/rpc/methods/state.rs
src/rpc/mod.rs
src/state_manager/mod.rs
src/tool/subcommands/api_cmd.rs

- implement RPC method `Filecoin.StateListActors`
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-12_height_1694998.forest.car.zst --filter StateListActors`
| RPC Method                    | Forest | Lotus |
|-------------------------------|--------|-------|
| Filecoin.StateListActors (10) | Valid  | Valid |
```
Closes

feat(rpc): implement Filecoin.StateListActors

---

src/lotus_json/vec.rs

Who the fuck wrote this code?
This fixes, in our openrpc:
- ugly names
- immediate recursion
#4032 

fix: schema name collisions in VecLotusJson

---

Cargo.lock
Cargo.toml
src/chain/mod.rs
src/chain/store/chain_store.rs
src/daemon/db_util.rs
src/daemon/mod.rs
src/db/car/many.rs
src/db/gc/mod.rs
src/db/memory.rs
src/db/migration/db_migration.rs
src/db/migration/migration_map.rs
src/db/migration/mod.rs
src/db/migration/v0_12_1.rs
src/db/migration/v0_16_0.rs
src/db/migration/v0_19_0.rs
src/db/migration/void_migration.rs
src/db/mod.rs
src/db/parity_db.rs
src/libp2p/chain_exchange/provider.rs
src/rpc/methods/chain.rs
src/rpc/methods/eth.rs
src/rpc/methods/sync.rs
src/tool/subcommands/api_cmd.rs

- Introduce a new ParityDB namespace for storing Ethereum mappings such as `Hash` to `TipsetKey` and `Hash` to message `Cid`.
This is required by methods like:
- EthGetBlockByHash
- EthGetBlockTransactionCountByHash
- EthGetMessageCidByTransactionHash
- Increment Forest version to `0.19.0`
Closes

Add support for Eth mappings

---

Cargo.lock
src/interpreter/vm.rs
src/state_manager/mod.rs
src/tool/subcommands/snapshot_cmd.rs

To address the below comment,  the rust compiler has now become smart enough to compile the desired code with no additional tricks
```
// note: we take &MessageCallbackCtx rather than MessageCallbackCtx<'_>
//       because I'm not smart enough to make the second one work
```
-
Closes

fix: change FnMut(&MessageCallbackCtx) to FnMut(MessageCallbackCtx<'_>)

---

scripts/tests/api_compare/filter-list

- `Filecoin.NetAgentVersion` fails the RPC test https://github.com/ChainSafe/forest/actions/runs/9581179496/job/26417600610
- the problem is that the node may have disconnected from the peer at hand (here - the last bootstrap node on the list), which in turn clears the entry in the peers collection. Perhaps we could not clear it on disconnects or keep another collection for historical info? @hanabi1224 what do you think? Anyhow, we can address it in a follow-up.
Closes

fix: disable NetAgentVersion RPC test

---

Cargo.lock
src/rpc/methods/state.rs
src/shim/executor.rs
src/state_manager/mod.rs
src/tool/subcommands/snapshot_cmd.rs

To address the original comment
> // This isn't ideal to have, since the execution is synchronous, but this needs
// to be the case because the state transition has to be in blocking
// thread to avoid starving executor
let (tx, rx) = flume::bounded(1);
- refactor `replay` into `replay_blocking` and `replay` to avoid using channels
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-18_height_1711826.forest.car.zst --filter StateReplay`
| RPC Method                | Forest | Lotus |
|---------------------------|--------|-------|
| Filecoin.StateReplay (24) | Valid  | Valid |
```
Closes

fix: refactor StateManager::replay to get rid of channels

---

src/lotus_json/cid.rs
src/lotus_json/mod.rs
src/lotus_json/signature_type.rs
src/lotus_json/vec.rs
src/lotus_json/vec_u8.rs
src/rpc/methods/eth.rs
src/rpc/mod.rs
src/rpc/reflect/mod.rs
src/tool/subcommands/shed_cmd.rs
tests/tool_tests.rs

Fixes this in our generated OpenRPC
```jsonc
{ "components": { "schemas": { "Cid": ..., "Cid2": ... } } }
```
- add an `include` argument to `forest-tool shed openrpc`
- rename `eth::BigInt` to `eth::EthBigInt`, but see #4436 
- make LotusJson for Vec less special
- make LotusJson for Cid less special
- `<LotusJson as JsonSchema>::schema_id` (this fixes most of the bugs)
- tweak schemas for SignatureType,  Vec<u8>, 

fix: duplicate schema names

---

build/bootstrap/calibnet
build/bootstrap/mainnet

The list of bootstrap nodes was provided using the `/dns4` multiaddr prefix, which limits libp2p connections to IPV4 only. Since the ChainSafe Infrastructure team has added IPV6 support to their bootstrap nodes, this change introduces a node's ability to join using either IPV4 or IPV6 through the DNS path. This change supports nodes that are IPV4 only, as well as those that support IPV4 and IPV6 (ChainSafe & glif.io nodes).
- Multiaddr prefix changed from `/dns4` to `/dns`
Closes https://github.com/ChainSafe/infrastructure-general/issues/264
This is to support the changes made during conversations with FilOz and to match changes made to Lotus here:
https://github.com/filecoin-project/lotus/pull/12103
[1]: …

chore: update multiaddr dns prefix for bootstrap nodes

---

CHANGELOG.md
src/rpc/methods/state.rs
src/rpc/mod.rs
src/state_manager/mod.rs
src/tool/subcommands/api_cmd.rs

(Part of https://github.com/ChainSafe/forest/issues/4424)
This PR fixes the `StateWaitMsg` RPC method against the [v1 spec](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md#StateWaitMsg) and uses it for both v0 and v1 endpoints until https://github.com/ChainSafe/forest/issues/3960 is resolved. (Keeping the v0 implementation with a different name for now)
- update `StateWaitMsg` against v1 spec
Closes

fix(rpc): update StateWaitMsg against v1 spec

---

src/blocks/header.rs
src/blocks/tipset.rs
src/chain/mod.rs
src/db/gc/mod.rs
src/interpreter/vm.rs
src/shim/machine/manifest.rs
src/tool/subcommands/archive_cmd.rs
src/tool/subcommands/benchmark_cmd.rs
src/tool/subcommands/snapshot_cmd.rs

This PR tries to avoid some `Arc::clone`s and recursive `Arc`s around `Blockstore`
- use borrowed impl Blockstore in parameter types when possible
Closes

fix: use borrowed impl Blockstore in parameter types when possible

---

src/rpc/reflect/mod.rs
src/rpc/reflect/parser.rs

Follow-up of #4452
- explicitly define the number of required RPC params to disambiguate the meaning of `Option` between `nullable` and `optional`
- update parser and tests accordingly
Closes

feat(rpc): explicitly define the number of required RPC params

---

src/chain_sync/tipset_syncer.rs

To address
Could we avoid the inner/outer loop complexity by refactoring this to smaller functions that could potentially be unit tested? At least the block `for tipset in network_tipsets {`
_Originally posted by @LesnyRumcajs in https://github.com/ChainSafe/forest/pull/4459#discussion_r1660713502_
- use a standalone function `for_each_tipset_until_epoch_overreached` for handling network tipsets
- more comments explaining the loop breaking logic
Closes

fix: refactor `sync_headers_in_reverse` to use a standalone function for handling network tipsets

---

src/cli/subcommands/mpool_cmd.rs
src/lotus_json/mod.rs
src/lotus_json/vec.rs
src/rpc/methods/mpool.rs

This PR tries to fix the below bug (https://github.com/ChainSafe/forest/issues/4424#issuecomment-2205601945)
> MpoolPending
expected response: empty json array result: [] if no messages found
actual response: result: null
-
Closes

fix(rpc): MpoolPending empty result should serialize into `[]` instead of `null`

---

src/rpc/methods/state.rs
src/tool/subcommands/api_cmd.rs

This PR tries to fix the below bug (https://github.com/ChainSafe/forest/issues/4424#issuecomment-2205601945)
> StateSectorGetInfo
expected response: result: null if sector commit info not found
actual response:
"error": {
"code": -32603,
"message": "Info for sector number 2 not found"
},
- add parity tests for StateSectorGetInfo to cover bad address and bad sector cases
- fix StateSectorGetInfo implementation
Closes

fix(rpc): parity tests for StateSectorGetInfo to cover bad address and bad sector cases

---

.github/workflows/release.yml
.github/workflows/release_dispatch.yml

- the script works on my MacOS machine on both `fish`, `bash`, `zsh` and `sh`. Likely we could contrive another workaround, but to avoid complexity let's just install `coreutils`.
Closes
https://github.com/ChainSafe/forest/actions/runs/9805478327/job/27075215364#step:5:20

fix: install macos sha256sum

---

Cargo.lock
Cargo.toml
src/lib.rs

To mitigate https://github.com/libp2p/rust-libp2p/issues/5487
- pin rustls@0.23.10
- bump jsonrpsee version
- `cargo update`
Closes

fix(deps): pin rustls@0.23.10 to mitigate panic in libp2p

---

CHANGELOG.md
src/rpc/methods/state.rs
src/rpc/mod.rs
src/tool/subcommands/api_cmd.rs

- implement RPC method `Filecoin.StateMinerAllocated`
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-07-10_height_1775204.forest.car.zst --filter StateMinerAllocated`
| RPC Method                        | Forest | Lotus |
|-----------------------------------|--------|-------|
| Filecoin.StateMinerAllocated (32) | Valid  | Valid |
```
Closes #4502

feat(rpc): implement Filecoin.StateMinerAllocated

---

.github/workflows/forest.yml

- The eth-mapping tests are failing for reasons I do not understand. It looks like there is a problem with the tests themselves, though.
Closes

ci: disable the eth-mapping checks

---

src/blocks/tests/serialization_vectors.rs
src/chain/store/base_fee.rs
src/chain/store/chain_store.rs
src/chain_sync/tipset_syncer.rs
src/cli/subcommands/chain_cmd.rs
src/cli/subcommands/mpool_cmd.rs
src/cli/subcommands/send_cmd.rs
src/db/ttl/mod.rs
src/interpreter/vm.rs
src/lotus_json/signed_message.rs
src/message/chain_message.rs
src/message/signed_message.rs
src/message_pool/msgpool/mod.rs
src/message_pool/msgpool/msg_pool.rs
src/message_pool/msgpool/utils.rs
src/rpc/methods/chain.rs
src/rpc/methods/eth.rs
src/rpc/methods/mpool.rs
src/rpc/methods/state.rs
src/rpc/methods/state/types.rs
src/shim/message.rs
src/state_manager/mod.rs
src/tool/subcommands/api_cmd.rs
src/tool/subcommands/snapshot_cmd.rs
src/wallet/subcommands/wallet_cmd.rs

- All messages have a CID; message serialization cannot fail.
Closes

chore: `Message::cid` is infallible

---

CHANGELOG.md
src/rpc/methods/wallet.rs
src/rpc/mod.rs
src/tool/subcommands/api_cmd.rs

- Implement `WalletSignMessage` - this signs the CID of a message and returns a `SignedMessage`.
Closes #4510

feat(rpc) Implement WalletSignMessage

---

CHANGELOG.md
scripts/tests/calibnet_other_check.sh
src/cli/subcommands/state_cmd.rs
src/rpc/methods/state.rs
src/rpc/mod.rs

- added support for runtime state computation, as opposed to exporting the snapshots and then checking it. This is useful for verifying network upgrades.
Closes

feat: compute-state via cli

---

src/metrics/mod.rs
src/utils/version/mod.rs

- add forest version to prometheus
```
forest_version_info{version="0.19.0+git.ffa93120d61"} 1
```
Closes #4533

feat(metric): add forest version to prometheus

---

.github/workflows/lotus-api-bump.yml

- use latest Lotus major/minor in the updates so that the automated workflow doesn't update `1.28.0` to `1.27.42` if the latter happens to be the latest release.
Closes

chore: use latest Lotus minor in updates

---

src/state_migration/mod.rs

There seems to be some off-by-1 error in the current logic that in CI devnet test it reveals the wrong logo on the waffle upgrade, see https://github.com/ChainSafe/forest/actions/runs/9958493368/job/27513328498#step:8:427
After the fix, see https://github.com/ChainSafe/forest/actions/runs/9965722823/job/27536633471?pr=4541#step:8:438
-
Closes

fix: reveal the proper logo for the waffle upgrade

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/rpc/methods/state.rs
src/rpc/mod.rs
src/shim/actors/verifreg.rs
src/shim/actors/verifreg/state.rs
src/state_manager/mod.rs
src/tool/subcommands/api_cmd.rs

- Introduces `Filecoin.StateGetAllClaims` RPC endpoint.
- Introduces `Filecoin.StateGetAllAllocations` RPC endpoint.
Closes #4500 
Closes #4501 

[Feature] Filecoin.StateGetAllClaims and Filecoin.StateGetAllAllocations RPC.

---

src/chain_sync/tipset_syncer.rs
src/daemon/mod.rs
src/rpc/methods/beacon.rs
src/rpc/methods/chain.rs
src/rpc/methods/common.rs
src/rpc/methods/eth.rs
src/rpc/methods/gas.rs
src/rpc/methods/miner.rs
src/rpc/methods/mpool.rs
src/rpc/methods/msig.rs
src/rpc/methods/net.rs
src/rpc/methods/node.rs
src/rpc/methods/state.rs
src/rpc/methods/sync.rs
src/rpc/methods/wallet.rs
src/rpc/mod.rs
src/state_manager/mod.rs
src/tool/subcommands/api_cmd.rs

This PR removes `chain_store` and `beacon` fields from `RPCState` that are accessible from `state_manager`.
- removes `chain_store` and `beacon` fields from `RPCState`
- add methods to `RPCState` for accessing `beacon`, `chain_store`, `chain_config` and `chain_index`
- publicly expose `StateManager::chain_rand` to avoid manually call `ChainRand::new` in RPC implementations
- cleanup and simplify RPC implementations code
Closes

fix(rpc): remove duplicate fields from rpc state

---

src/shim/actors/verifreg/state.rs

- Macros for `VerifiedRegistryStateExt`
Work on #4550 

[Enhancement] Macros for State.GetAll*

---

CHANGELOG.md
src/rpc/methods/state.rs
src/rpc/mod.rs
src/shim/actors/verifreg.rs
src/shim/actors/verifreg/state.rs
src/tool/subcommands/api_cmd.rs

- implement RPC method `Filecoin.StateVerifiedRegistryRootKey`
```
Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-07-18_height_1798730.forest.car.zst --filter StateVerifiedRegistryRootKey`
| RPC Method                                 | Forest | Lotus |
|--------------------------------------------|--------|-------|
| Filecoin.StateVerifiedRegistryRootKey (10) | Valid  | Valid |
```
Closes #4557

feat(rpc): implement Filecoin.StateVerifiedRegistryRootKey

---

src/rpc/methods/state.rs
src/shim/actors/common.rs
src/shim/actors/mod.rs
src/state_manager/mod.rs

There is a lot of repetitive code to load actor states in the RPC code. This PR introduces a new StateManager API to simplify that.
```rust
// before
let actor = ctx
.state_manager
.get_required_actor(&Address::VERIFIED_REGISTRY_ACTOR, *ts.parent_state())?;
let state = verifreg::State::load(ctx.store(), actor.code, actor.state)?;
// after 
let state: verifreg::State = ctx.state_manager.get_actor_state(&ts)?;
```
-
Closes

chore(rpc): new state manager api to simplify actor state loading logic

---

Cargo.lock
Cargo.toml
src/lib.rs

Undo the workaround in forest since `libp2p-tls@0.4.1` has fixed the bug https://github.com/libp2p/rust-libp2p/issues/5487 
- upgrade `libp2p-tls` and `rustls` to latest
Closes

fix(dep): upgrade libp2p-tls and unpin rustls

---

Cargo.lock
Cargo.toml
build/manifest.json
src/fil_cns/validation.rs
src/fil_cns/weight.rs
src/interpreter/fvm2.rs
src/interpreter/fvm3.rs
src/interpreter/fvm4.rs
src/interpreter/mod.rs
src/networks/actors_bundle.rs
src/networks/calibnet/mod.rs
src/networks/mod.rs
src/rpc/methods/eth.rs
src/rpc/methods/msig.rs
src/rpc/methods/state.rs
src/shim/actors/common.rs
src/shim/actors/mod.rs
src/shim/actors/state_load.rs
src/shim/actors/version.rs
src/shim/machine/manifest.rs
src/shim/state_tree.rs
src/state_manager/circulating_supply.rs
src/state_manager/mod.rs
src/state_manager/utils.rs
src/statediff/mod.rs
src/tool/subcommands/api_cmd.rs

- use CIDs from our self-generated manifest and not from Go-parsed code.
Closes https://github.com/ChainSafe/forest/issues/4347
~~Can be reviewed now, but blocked on https://github.com/ChainSafe/fil-actor-states/pull/320 to adjust the `fil-actor-states` version.~~
~~Also, tests blocked by https://github.com/ChainSafe/forest-iac/pull/460~~

chore: use actor cids from the manifest

---

src/libp2p/discovery.rs

Part of #4576
`go-libp2p-kad-dht` sends the remote peer id as query key during bootstrap, however, `rust-libp2p` returns empty peer list when the key it receives matches the local one. This PR configures Kademlia with a random peer ID as a workaround
- 
Closes 

fix(p2p): make kademlia in forest work for lotus

---

scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline

- The methods turned out to be flaky, see the linked issues https://github.com/ChainSafe/forest/issues/4584 and https://github.com/ChainSafe/forest/issues/4585
Closes

workaround: filter out flaky Eth methods

---

build/manifest.json
src/networks/actors_bundle.rs
src/networks/mainnet/mod.rs
src/state_migration/mod.rs

- tested on Lotus `v1.28.0` and latest `main` (8a31449b525c093cffb4af44563e31a277a6c622) of Forest for a fixed epoch.
```
2024-07-24T16:08:28.134515Z  INFO compute_tipset_state_blocking: forest_filecoin::state_migration: State migration at height Waffle(epoch 4117585) was successful, Previous state: bafy2bzacect6qqmzw6wspfibnr7p2jus5yhrrpoq2mpmckgekxdwvbvk2w2nw, new state: bafy2bzacec4awws4mrc5yrfzrq5qu7mlts7jgjpfiscv5mlgwvkdrkn7abaxu, new state actors: bafy2bzaceaekyd6f3u7eulusshrwhqkri3f5wbepyk4cuc6mvjwbqquf546jg. Took: 20.796257s.
```
```
2024-07-24T18:24:04.091+0200    WARN    statemgr        stmgr/forks.go:211      COMPLETED migration     {"height": "4117585", "from": "bafy2bzacect6qqmzw6wspfibnr7p2jus5yhrrpoq2mpmckgekxdwvbvk2w2nw", "to": …
```

feat: nv23 migration for mainnet

---

src/metrics/mod.rs
src/utils/version/mod.rs

This reverts commit 1103ac70fa749ec304751fa9a9be403bb1153a1b.
- the `Info` metric is not compliant with the default Prometheus/Grafana stack and so we should not use it (unless proven it works fine). See https://github.com/ChainSafe/forest/issues/4533#issuecomment-2250242854
Closes

Revert "feat(metric): add forest version to prometheus (#4535)"

---

CHANGELOG.md
scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline
src/rpc/methods/eth.rs

- Ran the fixed methods with the offending snapshot, now it works fine:
```
❯ forest-tool api compare --filter-file scripts/tests/api_compare/filter-list ~/prj/snapshots/forest_snapshot_calibnet_2024-07-24_height_1816297.forest.car.zst -n 10
| RPC Method                        | Forest | Lotus |
|-----------------------------------|--------|-------|
| Filecoin.EthGetBlockByHash (20)   | Valid  | Valid |
| Filecoin.EthGetBlockByNumber (20) | Valid  | Valid |
```
Closes https://github.com/ChainSafe/forest/issues/4584
Closes https://github.com/ChainSafe/forest/issues/4585

fix: fix invalid deserialization in `EthGetBlock`s

---

CHANGELOG.md
src/cli_shared/cli/client.rs
src/daemon/mod.rs

- The root token in Lotus does not expire. We _require_ expiration dates, though. This PR sets the expiration date of the root token to 100 years in the future. This aligns our behavior with that of Lotus.
Closes #4582

fix: align root JWT token expiration behavior with Lotus

---

CHANGELOG.md
src/metrics/mod.rs
src/rpc/metrics_layer.rs
src/rpc/mod.rs

- Expose how many times each RPC method has been called, how long the execution took, and how many failed.
The new metrics look like this:
```
rpc_processing_time_sum{method="Filecoin.NodeStatus"} 0.006975156
rpc_processing_time_count{method="Filecoin.NodeStatus"} 9
rpc_processing_time_bucket{le="0.01",method="Filecoin.NodeStatus"} 9
rpc_processing_time_bucket{le="0.02",method="Filecoin.NodeStatus"} 9
rpc_processing_time_bucket{le="0.04",method="Filecoin.NodeStatus"} 9
rpc_processing_time_bucket{le="0.08",method="Filecoin.NodeStatus"} 9
rpc_processing_time_bucket{le="0.16",method="Filecoin.NodeStatus"} 9
rpc_processing_time_bucket{le="0.32",method="Filecoin.NodeStatus"} 9
rpc_processing_time_bucket{le="0.64",method="Filecoin.NodeStatus"} 9 …
```

feat: prometheus metrics for RPC methods

---

CHANGELOG.md
documentation/src/environment_variables.md
src/networks/mod.rs
src/utils/misc/env.rs
src/utils/misc/mod.rs
src/utils/proofs_api/mod.rs
src/utils/proofs_api/parameters.rs
src/utils/proofs_api/paramfetch.rs

- configurable block delay and propagation delay,
- minor refactoring on env handling utilities.
Closes https://github.com/ChainSafe/forest/issues/4599

feat: configurable block delay and propagation delay

---

Dockerfile

- fixes `docker build` warning:
```
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 63)                                                                                                           0.0s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 96)                                                                                                           0.0s
```
Closes

fix: dockerfile FromAs casing

---

.github/workflows/forest.yml

- this reduces the disk space usage in the RPC test job that is failing due to heavy disk usage (GH workers out of the box guarantee only ~14-16 GB).
- added some visibility to disk space usage to facilitate future investigations.
Closes

fix(ci): remove unnecessary software in RPC build to reduce disk usage

---

CHANGELOG.md
scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline
src/fil_cns/validation.rs
src/lotus_json/extended_sector_info.rs
src/lotus_json/mod.rs
src/lotus_json/po_st_proof.rs
src/lotus_json/registered_po_st_proof.rs
src/lotus_json/registered_seal_proof.rs
src/lotus_json/sector_info.rs
src/rpc/methods/state.rs
src/rpc/types/mod.rs
src/shim/sector.rs
src/state_manager/utils.rs

- fixed consensus issues caused by using obsolete proof enums,
- I had to revive a function deleted in https://github.com/filecoin-project/ref-fvm/pull/1903 with some modifications `registered_winning_post_proof`
- re-applied the fix for `MinerGetBaseInfo` where the issue surfaced. 
Closes https://github.com/ChainSafe/forest/issues/4626
Closes https://github.com/ChainSafe/forest/issues/4610

fix: fix winning proofs

---

src/db/gc/mod.rs

- ignore the repeatedly failing GC unit tests, as outlined in https://github.com/ChainSafe/forest/issues/4404 so that they don't fail other unrelated PRs. They should still be fixed.
- `#[ignore]` doesn't work, see https://github.com/nytopop/quickcheck_async/issues/2
Closes

fix: ignore flaky GC tests

---

CHANGELOG.md
scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline
src/rpc/methods/state.rs
src/shim/actors/miner.rs
src/shim/actors/miner/state.rs

- In Lotus, calling `DeadlineInfo` redirects to `RecordedDeadlineInfo`. For reasons I don't understand, there exists `deadline_info()` and `recorded_deadline_info()`. There may be more places where we call the wrong function.
- This PR only fixes `StateMinerProvingDeadline`.
Closes #4630

fix: align `StateMinerProvingDeadline` with Lotus

---

src/metrics/mod.rs
src/rpc/metrics_layer.rs

Based on the feedback from Glif:
- changed the unit of RPC metrics to milliseconds, same as is reported in Lotus. This will facilitate cross-implementation performance testing,
- added unit of measure to the metric description.
Based on my subjective opinion (and so I'm open to reverting that):
- changed the histogram characteristics a bit, otherwise the majority of the methods would fall into all buckets. Should we change the bucket count to 5 and increase the factor to 10 @lemmih ?
Closes
```
rpc_processing_time_sum{method="Filecoin.ChainGetTipSetByHeight"} 0.039538
rpc_processing_time_count{method="Filecoin.ChainGetTipSetByHeight"} 1
rpc_processing_time_bucket{le="0.1",method="Filecoin.ChainGetTipSetByHeight"} 1 …
```

feat: use millis in RPC metrics

---

scripts/tests/api_compare/filter-list

- the test seems flaky, I added a corresponding issue with a snapshot that should reproduce the fiasco https://github.com/ChainSafe/forest/issues/4661
Closes

fix: move `Filecoin.EthGetBlockByNumber` to ignore

---

Cargo.lock
Cargo.toml
src/key_management/keystore.rs
src/libp2p/keypair.rs
src/utils/io/mod.rs
src/utils/tests/files.rs

- this mitigates a potential vulnerability where a malicious actor could intercept the private key before proper permissions were assigned to the file,
- Removed the needless compilation conditionals - Forest doesn't work outside of Unix and it won't happen anytime soon. If we want to support other platforms, there are way more things to do (and test).
After the change, the permissions are still `0600`
```
drwxr-xr-x. 1 rumcajs rumcajs  70 Aug 22 11:40 ./
drwx------. 1 rumcajs rumcajs 538 Aug 22 11:40 ../
drwxr-xr-x. 1 rumcajs rumcajs  12 Aug 22 11:40 calibnet/
-rw-------. 1 rumcajs rumcajs 161 Aug 22 11:40 keystore
-rw-------. 1 rumcajs rumcajs 116 Aug 22 11:40 keystore.json
drwxr-xr-x. 1 rumcajs rumcajs  14 Aug 22 11:40 libp2p/
```
Closes
[1]: …

fix: race condition in private key creation

---

CHANGELOG.md
Cargo.lock
Cargo.toml
scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline

- Bump actors to v16.0.1. This fixes a corner case in the `StateCirculatingSupply` RPC method.
- No testing yet. Testing will be part of #4657.
Closes #4446

Use actors v16.0.1 to fix the StateCirculatingSupply RPC method

---

CHANGELOG.md
src/rpc/methods/eth.rs
src/rpc/methods/eth/types.rs
src/rpc/mod.rs
src/tool/subcommands/api_cmd.rs

- implement RPC method `Filecoin.EthCall`
- API compare test
```console
$ ./forest-tool api compare --lotus /ip4/127.0.0.1/tcp/1234/http --forest /ip4/127.0.0.1/tcp/2345/http --filter EthCall
| RPC Method       | Forest | Lotus |
|------------------|--------|-------|
| Filecoin.EthCall | Valid  | Valid |
```
Closes #4613

feat(rpc) Implement `Filecoin.EthCall`

---

CHANGELOG.md
src/rpc/methods/common.rs
src/tool/subcommands/api_cmd.rs

- fixes the `APIVersion` returned by Forest. We only do it for `V1`, as `V0` is not going to be supported https://github.com/ChainSafe/forest/issues/3960#issuecomment-2276286349
Closes https://github.com/ChainSafe/forest/issues/4498

fix: `APIVersion` in `Filecoin.Version`

---

src/rpc/mod.rs

We've added some methods that we neglect to actually emit the OpenRPC spec for.
I've added that, and sorted the lists of methods for good measure

fix: sort and fill methods

---

scripts/tests/api_compare/.env
scripts/tests/snapshot_parity/.env
src/tool/subcommands/api_cmd.rs

- Updates Lotus version in the JSON-RPC API tests to the latest release.
- Ignore tests requesting old beacons, see https://github.com/ChainSafe/forest/issues/4718

[automated] Update Lotus version in API tests

---

CHANGELOG.md
src/rpc/error.rs
src/rpc/methods/eth.rs
src/rpc/mod.rs
src/tool/subcommands/api_cmd.rs

- added `unimplemented` stubs for `Filecoin.EthGetTransactionByBlockNumberAndIndex` and `Filecoin.EthGetTransactionByBlockHashAndIndex`. This behaviour matches Lotus's 1.29.0 behavior, and so we are on par with its support. Given the current Lotus-centric testing infrastructure, I believe that's the optimal way to move forward. When Lotus will decide to implement these methods, we'll get a notification.
Closes https://github.com/ChainSafe/forest/issues/4701
Closes https://github.com/ChainSafe/forest/issues/4702
```
❯ docker compose logs api-compare | rg EthGetTransactionByBlock
api-compare-1  | | Filecoin.EthGetTransactionByBlockHashAndIndex (10)   | Rejected("unsupported method")                                                                | …
```

feat: add unsupported `EthGetTransactionByBlock*`

---

.cargo/audit.toml

https://rustsec.org/advisories/RUSTSEC-2024-0370
-
Closes

fix(ci): ignore RUSTSEC-2024-0370 to unblock CI

---

Makefile

automatically upgrade prettier in `make fmt` to avoid potential CI lint errors when local prettier is out-of-date
- 
Closes

fix: automatically upgrade prettier in `make fmt`

---

.config/forest.dic
src/cli_shared/logger/mod.rs
src/rpc/log_layer.rs
src/rpc/metrics_layer.rs
src/rpc/mod.rs

- added server-side logs for RPC calls.
Closes
Default:
```
2024-09-06T11:29:27.964357Z  INFO forest_filecoin::chain_sync::chain_muxer: Bootstrap successfully completed, now evaluating the network head to ensure the node is in sync
2024-09-06T11:29:27.964369Z  INFO forest_filecoin::chain_sync::chain_muxer: Evaluating network head...
2024-09-06T11:29:27.964380Z  INFO forest_filecoin::chain_sync::chain_muxer: Local node is in sync with the network
2024-09-06T11:29:28.209002Z  INFO forest_filecoin::rpc::log_layer: RPC#7e600a OK: Filecoin.StateNetworkName. Took 92.986µs
2024-09-06T11:29:28.209320Z  INFO forest_filecoin::rpc::log_layer: RPC#d6ce46 OK: Filecoin.NetPeers. Took 107.429µs
2024-09-06T11:29:28.209522Z  INFO forest_filecoin::rpc::log_layer: …
```

feat: log RPC calls

---

rust-toolchain.toml
src/key_management/keystore.rs
src/libp2p/peer_manager.rs

- upgrade rust toolchain to 1.81.0
```
warning: method `unprotect_peer` is never used
--> src/libp2p/peer_manager.rs:352:12
|
107 | impl PeerManager {
| ---------------- method in this implementation
...
352 |     pub fn unprotect_peer(&self, peer_id: &PeerId) {
|            ^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: using `map_err` over `inspect_err`
--> src/key_management/keystore.rs:132:34
|
132 | ...                   .map_err(|e| {
|                        ^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_inspect
= note: `#[warn(clippy::manual_inspect)]` on by default
help: try
|
132 ~                                 .inspect_err(|e| …
```

chore: upgrade rust toolchain

---

CHANGELOG.md
documentation/src/configuration.md
scripts/tests/bootstrapper/docker-compose-forest.yml
src/cli_shared/cli/mod.rs
src/daemon/db_util.rs

As follow up of #4620
- add `--import-mode=hardlink` to hard link snapshots instead of copying them to save time and disk space
- add `--import-mode=auto` as default to hard link snapshots and fallback to copying them.
- add some info logs that print modes during snapshot import
Closes

feat: support hardlink in --import-mode

---

CHANGELOG.md
src/rpc/methods/auth.rs
src/rpc/methods/beacon.rs
src/rpc/methods/chain.rs
src/rpc/methods/common.rs
src/rpc/methods/gas.rs
src/rpc/methods/miner.rs
src/rpc/methods/mpool.rs
src/rpc/methods/msig.rs
src/rpc/methods/net.rs
src/rpc/methods/node.rs
src/rpc/methods/state.rs
src/rpc/methods/sync.rs
src/rpc/methods/wallet.rs

- move all RPC methods to V1 if applicable
- add comments to methods that are no longer supported in V1
- TODO: https://github.com/ChainSafe/forest/issues/4767
Closes https://github.com/ChainSafe/forest/issues/4678

chore: move all RPC methods to V1

---

scripts/tests/api_compare/filter-list
src/tool/subcommands/api_cmd.rs

- we have no means of ensuring two nodes are completely in sync with regards to the chain head. As such, we can't, with the current setup, check for parity of methods relying on that.
Closes https://github.com/ChainSafe/forest/issues/4661

fix: demote `safe` eth methods to basic tests

---

scripts/devnet-curio/docker-compose.yml

- The variables from `.env` are required but were lost in the script refactoring. This PR makes them available to the curio script.
Closes

fix: expand environment variables available for curio script

---

.github/DOCKER_ISSUE_TEMPLATE.md
.github/workflows/dockerfile-check.yml

- adds a workflow that will periodically check that the Dockerfile works fine. This is to limit builds in the CI and save some :moneybag: 
- Sample output: https://github.com/ChainSafe/forest/issues/4785 (right now the Dockerfile is broken). A link will be added in a follow-up.
Closes

feat(ci): check Dockerfile

---

f3-sidecar/ffi_gen.go
f3-sidecar/ffi_impl.go
f3-sidecar/go.mod
f3-sidecar/main.go
f3-sidecar/run.go
src/daemon/mod.rs
src/f3/go_ffi.rs
src/f3/mod.rs

This PR ports https://github.com/filecoin-project/lotus/pull/12502 to Forest F3 sidecar integration
-
CI log: https://github.com/ChainSafe/forest/actions/runs/11029965114/job/30633871974?pr=4795#step:8:265
```
2024-09-25T09:22:14.821Z	INFO	f3	go-f3@v0.3.0/host.go:662	reached a decision	{"instance": 14, "ecHeadEpoch": 19}
2024-09-25T09:22:14.832Z	INFO	f3	go-f3@v0.3.0/host.go:284	backing off for: 1m10s
2024-09-25T09:22:20.867Z	INFO	f3	go-f3@v0.3.0/host.go:662	reached a decision	{"instance": 15, "ecHeadEpoch": 19}
2024-09-25T09:22:20.875Z	INFO	f3	go-f3@v0.3.0/host.go:284	backing off for: 1m39.68s
2024-09-25T09:22:20.912Z	INFO	f3	go-f3@v0.3.0/host.go:662	reached a decision	{"instance": 16, "ecHeadEpoch": 22}
```
Closes
[1]: …

feat(f3): add initial power table support to F3 sidecar

---

scripts/devnet-curio/docker-compose.yml

- f3 is no longer a separate container.
Closes

fix: align f3 configuration with the regular devnet

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/docs.yml
.github/workflows/scripts-lint.yml
.lycheeignore
CHANGELOG.md
Makefile
README.md
monitoring/README.md

- Removed documentation workflow
- Removed make the now-obsolete documentation make targets
Closes
Follow-up: https://github.com/ChainSafe/forest/issues/4793
Do we still need `make docs`?
We also copy `documentation` folder as part of `release` and `release-dispatch` workflows, but that can be removed as part of `documentation` folder cleanup later on.

chore: remove doc workflows and targets

---

.github/workflows/docker.yml
.github/workflows/forest.yml

This PR separates sccache directory of macos/amd64 and linux/amd64 by setting `SCCACHE_S3_KEY_PREFIX=[maxos|aarch64]`, and increase RAM on the runner to address build failures in https://github.com/ChainSafe/forest/actions/runs/11034989905/job/30675114594
Note: https://github.com/ChainSafe/forest/actions/runs/11034989905/job/30675114594 passed after retry so the root cause should be OOM.  upgrading buildjet runner model should be the actual fix
- set SCCACHE_S3_KEY_PREFIX for macos and arm64 build to avoid potential hash confilicts(in file names)
- upgrade `buildjet-4vcpu-ubuntu-2204-arm` to `buildjet-8vcpu-ubuntu-2204-arm` to get rid of OOM
CI log with the change: https://github.com/ChainSafe/forest/actions/runs/11046284131/job/30685340347?pr=4807 …

fix(ci): add s3 key prefix for macos and arm64

---

CHANGELOG.md
build.rs

- Fixes the Go compilation on a mac for aarch64 target.
Closes https://github.com/ChainSafe/forest/issues/4777
Has been tested running on calibnet. Works.

fix: mac os x aarch64 sidecar compilation

---

.github/workflows/scripts-lint.yml

To fix the below error in https://github.com/ChainSafe/forest/actions/runs/11053255845/job/30707195919#step:5:87
```
Error: lint-action does not support "merge_group" GitHub events
```
-
Closes

fix(ci): disable python-lint for merge queue

---

build/bootstrap/calibnet

- add calibnet archival bootnode endpoint
Closes

chore: add calibnet archival bootnode endpoint

---

src/rpc/log_layer.rs

- demoted `info` to `debug` and `debug` to `trace` in the log layer of RPC. This avoids spamming logs when the RPC endpoint is repeatedly called, e.g., by F3. See https://github.com/ChainSafe/forest/issues/4790
Closes

chore: demote RPC logs by one level

---

README.md
documentation/src/configuration.md

I was trying to setup Forest on a Devnet and noticed that some of the docs are out of date
This PR has corrected a spelling error on the `README` and updated the `configuration.md` file to represent a working configuration

Documentation change

---

scripts/devnet-curio/run_curio.sh

- Forest requires access to the miner key pair. This is solved by exporting the wallet from Lotus and importing it into Forest.
- Errors are ignored since this code is run multiple times and has to be idempotent. I'll fix it soon. Later. Eventually. I promise.
Closes

curio devnet: move miner wallet to forest

---

Cargo.lock

- this fixes:
```
Crate:     tonic
Version:   0.12.2
Title:     Remotely exploitable Denial of Service in Tonic
Date:      2024-10-01
ID:        RUSTSEC-2024-0376
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0376
Solution:  Upgrade to >=0.12.3
Dependency tree:
tonic 0.12.2
├── console-subscriber 0.4.0
│   └── forest-filecoin 0.20.0
│       └── forest-interop-tests 0.1.0
└── console-api 0.8.0
└── console-subscriber 0.4.0
error: 1 vulnerability found!
```
https://github.com/ChainSafe/forest/actions/runs/11140650758/job/30959881615
Closes

fix: update tonic dependency

---

CHANGELOG.md
src/state_manager/mod.rs

- If a miner isn't found in the look-back state, we must return `null` to match Lotus' behavior.
Closes

fix: return null in `MinerGetBaseInfo` if miner hasn't been around for 900 epochs

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/task.md

- this should fix the broken Slack description and the lack of a `task` in the list of available templates.
Closes

fix: fixed GH templates

---

scripts/devnet/lotus.dockerfile

- `lotus-shed` is required in the curio-backed devnet.
Closes

chore: make lotus-shed available from our lotus-devnet image

---

scripts/devnet-curio/.env
scripts/devnet-curio/lotus.dockerfile
scripts/devnet/.env
scripts/devnet/lotus.dockerfile

Lotus has upgraded Go to 1.22 in its v1.29.2 release, this PR updates the Dockerfiles accordingly.
https://github.com/filecoin-project/lotus/blob/v1.29.2/go.mod#L3
CI to build new image from this branch: https://github.com/ChainSafe/forest/actions/runs/11224471498/job/31201254574#step:8:30
- update lotus.dockerfile(s)
- update lotus-devnet image tags
Closes

chore(dockerfile): bump golang version in lotus.dockerfile

---

CHANGELOG.md
src/networks/mod.rs
src/rpc/methods/state.rs
src/shim/actors/mod.rs
src/shim/actors/power.rs
src/state_migration/nv24/migration.rs
src/state_migration/nv24/mod.rs
src/state_migration/nv24/power.rs

- Migrate power actor for nv24.
- Ramp durations are: 1 year for mainnet, 3 days for calibnet, and 200 epochs for devnet.
- No tests other than those included in the builtin actors.
Closes #4798

feat: power migration for nv24

---

.github/workflows/forest.yml
Cargo.lock
Cargo.toml
scripts/devnet-curio/check.sh
scripts/devnet/check.sh
src/cli/subcommands/send_cmd.rs
src/shim/address.rs
src/wallet/subcommands/wallet_cmd.rs

- updated FVM to the latest version as required by the NV24 upgrade,
- updated `fil-actor-states` deps to unblock the bump,
- removed the `testing` feature for FVM builds outside of tests.
Closes https://github.com/ChainSafe/forest/issues/4806

chore: update FVM

---

CHANGELOG.md
f3-sidecar/api.go
src/rpc/methods/f3.rs
src/rpc/mod.rs

- implement RPC method `Filecoin.F3GetProgress` https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md#F3GetProgress
- manual testing (API compare tests will come later once F3 is enabled by default in Lotus)
Closes https://github.com/ChainSafe/forest/issues/4862

feat(rpc): Filecoin.F3GetProgress

---

src/networks/calibnet/mod.rs
src/networks/mod.rs
src/state_migration/mod.rs

- tested on the latest Lotus `v1.30.0-rc.1`
```
2024-10-14T15:12:14.017+0200    WARN    statemgr        stmgr/forks.go:211      COMPLETED migration     {"height": "2052698", "from": "bafy2bzacecsa5a2s6qb734yp6jq2mzprtgtiu45ytwzumlof6yjuvdzzyveus", "to": "bafy2bzacec4jgncvjs7yngjn5kmwxsmpzhnyzi7tlbykzmfwahpp2avquhc2w", "duration": 3.369077624}
```
```
2024-10-14T13:12:43.792872Z  INFO compute_tipset_state_blocking: forest_filecoin::state_migration: State migration at height TukTuk(epoch 2052698) was successful, Previous state: bafy2bzacecsa5a2s6qb734yp6jq2mzprtgtiu45ytwzumlof6yjuvdzzyveus, new state: bafy2bzacec4jgncvjs7yngjn5kmwxsmpzhnyzi7tlbykzmfwahpp2avquhc2w, new state actors: bafy2bzaceabi4nlwixwupjdaqr66dtq3marmj4h4iownwcxvlaudzw3s5iiaw. Took: …
```

feat: add calibnet tuk tuk epoch

---

src/rpc/methods/f3.rs
src/tool/subcommands/api_cmd.rs

- API compare tests for `Filecoin.F3GetECPowerTable`(which does not require F3 to be running)
- (Parity tests for other F3 methods will come later when F3 is enabled by default)
```
| RPC Method                      | Forest | Lotus |
|---------------------------------|--------|-------|
| Filecoin.F3GetECPowerTable (11) | Valid  | Valid |
```
Closes

test(rpc): pairty test for Filecoin.F3GetECPowerTable

---

.config/forest.dic
f3-sidecar/ffi_impl.go
f3-sidecar/main.go
f3-sidecar/run.go
src/blocks/header.rs
src/chain_sync/chain_muxer.rs
src/chain_sync/mod.rs
src/chain_sync/network_context.rs
src/daemon/mod.rs
src/f3/mod.rs
src/networks/mod.rs
src/rpc/error.rs
src/rpc/methods/f3.rs
src/rpc/methods/net.rs
src/rpc/methods/state.rs
src/rpc/methods/sync.rs
src/rpc/mod.rs
src/tool/offline_server/server.rs
src/utils/misc/env.rs

See #4876 for details
- implement Finalize for EC(expected consensus) backend
- add `f3_enabled` and `f3_consensus` to `ChainConfig`
- adjust F3 sidecar log levels
- fix `CommitteeLookback` setting in F3 sidecar manifest to align with Lotus
- env var docs updated in https://github.com/ChainSafe/forest-docs-v2/pull/92
Closes #4876

feat(f3): implement Finalize for EC backend

---

Cargo.lock
Cargo.toml
src/metrics/mod.rs
src/rpc/mod.rs

Part of #4903
- add compression support to metrics server
- add compression support to RPC server (~blocked on https://github.com/paritytech/jsonrpsee/pull/1475~)
- mark the `Authorization` request header as sensitive so it doesn't show in logs
- upgrade `jsonrpsee`
Closes #4903

feat: add compression support to metrics and RPC servers

---

CHANGELOG.md
src/rpc/methods/f3.rs
src/rpc/mod.rs

- implement Filecoin.F3ListParticipants
- API parity tests will come later
Closes #4909

feat(rpc): implement Filecoin.F3ListParticipants

---

f3-sidecar/run.go

This PR ports https://github.com/filecoin-project/lotus/pull/12597 to avoid a deadlock situation where everyone is waiting for the next round to participate, but we'll never get there because not enough participants acted in the current round.
-
Closes #4911

fix(f3): send the last gpbft message for each new participant

---

f3-sidecar/run.go

This PR ports the cert exchange poll interval settings from https://github.com/filecoin-project/lotus/pull/12552/files#diff-7c1c1d6fc05d13d1b9fdb96e27a9dfb356073fb6afb16d2654392d9dee4070d5R66
It makes no difference for chains whose epoch delay is 30s, but should reduce poll interval on devnet.
-
Closes

fix(f3): port CertificateExchange.*PollInterval config from lotus

---

.github/workflows/release.yml
.github/workflows/release_dispatch.yml

- fixes failing build for MacOS (missing Go setup),
- fixes wrong architecture for the build (`macos-latest` moved to arm-based workers)
- fixes missing wallet binary.
- removes legacy `documentation`
Closes

fix: failing macos build, wrong arch, missing wallet

---

CHANGELOG.md
Cargo.lock
Cargo.toml
build/bootstrap/butterflynet
src/libp2p/behaviour.rs
src/libp2p/discovery.rs
src/libp2p/service.rs
src/networks/butterflynet/mod.rs

- reset butterflynet using build params in https://github.com/filecoin-project/lotus/tree/butterfly/v24
- support `/dnsaddr/name` addresses for bootstrapping libp2p network
(Manually tested locally)
```
2024-10-18T16:18:30.188574Z  INFO forest_filecoin::chain_sync::tipset_syncer: Fork detected, searching for a common ancestor between the local chain and the network chain
2024-10-19T00:18:30.336+0800    INFO    f3      go-f3@v0.7.0/host.go:880        reached a decision      {"instance": 611, "ecHeadEpoch": 814}
2024-10-19T00:18:30.359+0800    INFO    f3      go-f3@v0.7.0/host.go:256        not finalizing a new head because Finalize the manifest specifies that tipsets should not be finalized  {"tsk": …
```

chore: butterflynet reset

---

Cargo.lock
Cargo.toml

- given https://github.com/filecoin-project/ref-fvm/issues/2058 is resolved, we should be safely able to bump the FVM2 and FVM3. Leaving out FVM4 for now to keep it the same as in Lotus RC for NV24.
Closes

chore: bump older FVM versions

---

.github/workflows/curio-devnet-publish.yml
scripts/devnet-curio/.env
scripts/devnet-curio/docker-compose.yml

- fixes the curio devnet build/publish workflow,
- uses the cached image in the CI so that Curio is not rebuilt on every commit in a PR
Closes

fix: curio docker build/publish

---

CHANGELOG.md
Cargo.lock
Cargo.toml
f3-sidecar/.gitignore
f3-sidecar/run.go
src/daemon/mod.rs
src/networks/mod.rs

chore(f3): set f3_init_power_table_cid for calibnet

---

scripts/tests/api_compare/filter-list
src/chain/store/chain_store.rs
src/chain_sync/chain_muxer.rs
src/chain_sync/mod.rs
src/chain_sync/validation.rs
src/rpc/error.rs
src/rpc/methods/f3.rs
src/rpc/methods/sync.rs

This PR fixes a bug that Forest crashes when F3 resets the chain head. (We should merge this before releasing v0.21.1)
error:
```
2024-10-26T03:37:05.829Z        ERROR   f3      go-f3@v0.7.0/host.go:352        could not get timestamp of just finalized tipset: RPC error (-32603): Key for header not found
2024-10-26T03:37:06.382087Z  INFO forest_filecoin::chain::store::chain_store: New heaviest tipset! [bafy2bzacec4ebks2o4mt4itaq3ipf2zka23ctsz4j5dn4akw2mup2kz3ncrxm, bafy2bzacecdnlleq6q3vqn2rek5eqldercx2qe5min3arh2gn6mwuxfxgv4wi] (EPOCH = 2086246)
2024-10-26T03:37:06.382140Z  INFO forest_filecoin::rpc::methods::f3: F3 finalized tsk [bafy2bzacec4ebks2o4mt4itaq3ipf2zka23ctsz4j5dn4akw2mup2kz3ncrxm, bafy2bzaceczae4ft7az3boquqprikoegyhpqy44jxvnq456nljlbcoicigugu, …
```

fix(f3): validate tipset before resetting the chain head

---

CHANGELOG.md
Cargo.lock
Cargo.toml
scripts/tests/api_compare/filter-list
src/cli/main.rs
src/cli/subcommands/f3_cmd.rs
src/cli/subcommands/mod.rs
src/lotus_json/duration.rs
src/lotus_json/mod.rs
src/rpc/methods/f3.rs
src/rpc/methods/f3/types.rs
templates/cli/f3/manifest.stpl

This PR ports `lotus f3 manifest` CLI command.
- implement `forest-cli f3 manifest` command 
Output:
```
➜  forest git:(hm/forest-cli-f3-manifest) cargo run --bin forest-cli -- f3 manifest --output text
Compiling forest-filecoin v0.21.1 (/home/me/git/forest)
Finished `dev` profile [unoptimized] target(s) in 22.60s
Running `target/debug/forest-cli f3 manifest --output text`
Manifest:
Protocol Version:     4
Paused:               false
Initial Instance:     0
Initial Power Table:  bafy2bzaceab236vmmb3n4q4tkvua2n4dphcbzzxerxuey3mot4g3cov5j3r2c
Bootstrap Epoch:      2081674
Network Name:         calibrationnet
Ignore EC Power:      false
Committee Lookback:   10
Catch Up Alignment:   15s
GPBFT Delta:                        6s
GPBFT Delta BackOff …
```

feat(cli): implement forest-cli f3 manifest

---

CHANGELOG.md
src/cli/subcommands/f3_cmd.rs
src/rpc/methods/f3.rs
src/rpc/methods/f3/types.rs
templates/cli/f3/progress.stpl

This PR ports `lotus f3 status` to Forest
-
Output
```
Running: true
Progress:
Instance: 11271
Round:    0
Phase:    INITIAL
Manifest:
Protocol Version:     4
Paused:               false
Initial Instance:     0
Initial Power Table:  bafy2bzaceab236vmmb3n4q4tkvua2n4dphcbzzxerxuey3mot4g3cov5j3r2c
Bootstrap Epoch:      2081674
Network Name:         calibrationnet
Ignore EC Power:      false
Committee Lookback:   10
Catch Up Alignment:   15s
GPBFT Delta:                        6s
GPBFT Delta BackOff Exponent:       2.0
GPBFT Max Lookahead Rounds:         5
GPBFT Rebroadcast Backoff Base:     6s
GPBFT Rebroadcast Backoff Exponent: 1.3
GPBFT Rebroadcast Backoff Spread:   0.1
GPBFT Rebroadcast Backoff Max:      1m
EC Period:            30s
EC Finality: …
```

feat(cli): forest-cli f3 status

---

CHANGELOG.md
scripts/tests/calibnet_other_check.sh
scripts/tests/calibnet_stateless_mode_check.sh
src/cli/subcommands/chain_cmd.rs

- adds `forest-cli chain head --tipsets [and -n]` option, which allows for printing multiple last tipsets
- breaking change as I added epoch label
```
❯ forest-cli chain head
[2097089]
bafy2bzaceajfbzlhuwudsdu3swuhgys2govtyel46akjdbarq2752w7cz7gde
bafy2bzaceapu74bbaxoftc76qbez7vr5a3hmkjcxjfk5pofufwv3wnlk36b3w
bafy2bzaceb2372awzqenvkdgpnkt34ssz64redtf4qb2ewugzbbpekl4kfftq
bafy2bzacebzh3llwhllzxsremaop4u37kbm4quu5bpjiwuoagzgmudmmwsywo
```
```
❯ forest-cli chain head -n 5
[2097089]
bafy2bzaceajfbzlhuwudsdu3swuhgys2govtyel46akjdbarq2752w7cz7gde
bafy2bzaceapu74bbaxoftc76qbez7vr5a3hmkjcxjfk5pofufwv3wnlk36b3w
bafy2bzaceb2372awzqenvkdgpnkt34ssz64redtf4qb2ewugzbbpekl4kfftq
bafy2bzacebzh3llwhllzxsremaop4u37kbm4quu5bpjiwuoagzgmudmmwsywo
[2097088] …
```

feat: extend `forest-cli chain head`

---

f3-sidecar/ffi_impl.go

This PR prints the error message when F3 service fails unexpectedly and tries to reboot the service, to mitigate the CI failure in https://github.com/ChainSafe/forest/actions/runs/11592356963/job/32274345532
-
Closes

fix(f3): auto-restart F3 service on errors

---

scripts/tests/api_compare/.env
scripts/tests/bootstrapper/.env
scripts/tests/snapshot_parity/.env

- use v1.30.0 stable Lotus in CI tests, @LeshyBot can't deal with this at its current capacities.
Closes

chore: use v1.30.0 stable Lotus in CI tests

---

CHANGELOG.md
src/rpc/methods/eth.rs
src/rpc/mod.rs
src/tool/subcommands/api_cmd.rs

Implemented `eth_getBlockReceipts` RPC method
Closes #4839 

feat: Add EthGetBlockReceipts RPC method

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli/subcommands/f3_cmd.rs
src/cli/subcommands/f3_cmd/tests.rs

Closes #5000
- implement `forest-cli f3 certs list`
lotus ouput:
```
➜  lotus git:(master) lotus f3 c list --output text 5000..5002
Instance:     5002
Power Table:
Next:       bafy2bzaceaiaeoyryp6ojvoqxvr6yarzqhat2zq3aaszhz3jol2u46v2gu4ry
Delta:      None
Finalized Chain:
Length:     2
Epochs:     2087720-2087721
Chain:
├──2087720 (length: 4): [bafy2bzaceagtkrcgrdaeqjyq2xra4jrqni53m5tlw3dcx3wtbqpidhj65uemg, bafy2bzacedtxz7jfcxeishfjiba33e6oq2jsx6pwt4gnnrcitf4ruyfva7mzg, ...]
└──2087721 (length: 3): [bafy2bzacedioj63g772b4zss4vtt5w7u7yklaajablkpuq73yp5np4x7fplj4, bafy2bzaceckybf34ub7ob5rhhe4cb7mtpsqvqyd54432q57qfkkonctqusmqk, ...]
Signed by 3 miner(s).
Instance:     5001
Power Table:
Next: …
```

feat(f3): forest-cli f3 certs list

---

CHANGELOG.md
src/rpc/methods/eth.rs
src/rpc/mod.rs
src/tool/subcommands/api_cmd.rs

implemented EthGetBlockReceiptsLimited RPC method
-
Closes #5017

feat: implement EthGetBlockReceiptsLimited RPC method

---

CHANGELOG.md
src/rpc/methods/state.rs

- added missing TukTuk entry in the network params info
Closes

fix: include TukTuk in the network params

---

.github/workflows/forest.yml

To make CI workflow config more intuitive.
`merge_group: null` -> `merge_group`
`workflow_dispatch: null` -> `workflow_dispatch`
-
Closes

fix(ci): omit null in workflow triggering conditions in forest.yml

---

Cargo.lock
deny.toml

- ignore RUSTSEC-2024-0421 for now and track the fix in https://github.com/ChainSafe/forest/issues/5058
Closes
https://rustsec.org/advisories/RUSTSEC-2024-0421.html

fix(ci): ignore RUSTSEC-2024-0421 to unblock CI

---

src/chain_sync/network_context.rs
src/libp2p/discovery.rs
src/libp2p/peer_manager.rs
src/libp2p/service.rs

We occasionally see a lot of expected `banning peer PEER for REASON` logs, it'd help troubleshooting the issue to add user agent to the log
-
Sample logs:
```
2024-12-10T00:41:20.357572Z  DEBUG forest_filecoin::libp2p::service: Banning peer peer=12D3KooWJe3QWBUFPa7DBaYLq1BXWcK2LVM39VBawuVz3ePHT45K user_agent= reason=Hello protocol unsupported
2024-12-10T00:41:20.357801Z  DEBUG forest_filecoin::libp2p::service: Banning peer peer=12D3KooWJe3QWBUFPa7DBaYLq1BXWcK2LVM39VBawuVz3ePHT45K user_agent=sophon-messager reason=hello protocol unsupported
2024-12-10T00:41:20.435089Z  DEBUG forest_filecoin::libp2p::service: Banning peer peer=12D3KooWQtcfpAhnu89D3YkyA1ZVXmDBmCLwA62LEfHinfLcHzoL user_agent= reason=Hello protocol unsupported
```
Closes
[1]: …

fix(p2p): log user agent on banning a peer

---

.github/workflows/docs-check.yml

- Copy over GHA from [forest-docs-v2](https://github.com/ChainSafe/forest-docs-v2/blob/main/.github/workflows/check.yaml)
- Add concurrency conditions and update triggers
- Disable caching due to known issue in `setup-node`, exact cause unknown
Part of #5045 

Add spellcheck gha for docs

---

CHANGELOG.md
src/chain_sync/chain_muxer.rs
src/health/mod.rs
src/libp2p/metrics.rs
src/libp2p/peer_manager.rs
src/libp2p/service.rs
src/rpc/methods/state.rs

- Do not keep track of which epoch peers are at. There are no good ways of doing it and we don't need it.
- Remove dead code.
Closes

chore: do not keep track of which tipsets peers have seen

---

scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline
src/rpc/methods/state.rs

fix(rpc): StateCirculatingSupply

---

src/rpc/methods/eth.rs
src/shim/gas.rs

- Remove duplicated `GasOutputs` code
Closes https://github.com/ChainSafe/forest/issues/4759

fix(shim): remove duplicated GasOutputs code

---

.config/lychee.toml
.github/workflows/forest.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
src/interpreter/fvm2.rs
src/interpreter/fvm3.rs
src/interpreter/fvm4.rs

- fix logic to match Lotus
- bump Forest version
https://github.com/filecoin-project/lotus/blob/v1.32.0-rc2/chain/vm/fvm.go#L169
```go
// (4) expensive final checks
// check blocks are properly signed by their respective miner
// note we do not need to check extra's: it is a parent to block b
// which itself is signed, so it was willingly included by the miner
gasA, sigErr := x.verifyBlockSig(ctx, &blockA)
totalGas += gasA
if sigErr != nil {
log.Info("invalid consensus fault: cannot verify first block sig: %w", sigErr)
return ret, totalGas
}
gas2, sigErr := x.verifyBlockSig(ctx, &blockB)
totalGas += gas2
if sigErr != nil {
log.Info("invalid consensus fault: cannot verify second block sig: %w", sigErr)
return ret, totalGas
}
```
Closes …

fix: block validation error at epoch 2281645

---

.github/workflows/forest.yml

- we're back on track with snapshots; let's use again a more strict timeout to catch potential performance regressions.
Reverts https://github.com/ChainSafe/forest/pull/5109/commits/634cde9a8aa8c9231bfce8803476af1fbe7a5af2

chore: revert timeout increase for RPC tests

---

CHANGELOG.md
f3-sidecar/p2p.go
scripts/tests/calibnet_no_discovery_check.sh
scripts/tests/calibnet_other_check.sh
src/f3/mod.rs
src/libp2p/discovery.rs

This PR introduces a second internal Kademlia for bootstrapping F3 when the node Kademlia is disabled.
- add a second internal Kademlia
- update test scripts accordingly
Closes #5065

fix(f3): F3 sidecar should work with Kademlia disabled

---

.github/workflows/docker.yml
.github/workflows/docs-required-override.yml
.github/workflows/forest.yml
.github/workflows/unit-tests.yml

- workaround for required checks for docs as documented in the workflow file,
- don't trigger expensive jobs on doc workflow changes
Closes

fix: docs don't trigger required checks

---

CHANGELOG.md
src/db/gc/mod.rs
src/ipld/util.rs

This PR fixes a potential bug in GC flow that after sleeping(10h), only `current_epoch` is refreshed but the 10h old `tipset` is used for the filtering step. 
It also refactors a few chain traversal APIs to be more generic in preparation for lite GC implementation that is tracked by https://github.com/ChainSafe/forest/issues/5121
-
Closes

fix(gc): refresh `current_tipset` together with `current_epoch` after sleeping

---

Cargo.toml
benches/car-index.rs
docs/docs/users/guides/monitoring/logs.md
docs/docs/users/knowledge_base/jwt_handling.md
documentation/src/developer_documentation/state_migration_guide.md
documentation/src/offline-forest.md
interop-tests/Cargo.toml
interop-tests/src/tests/bitswap_go_compat.rs
interop-tests/src/tests/kad_go_compat.rs
scripts/devnet-curio/docker-compose.yml
scripts/devnet/docker-compose.yml
scripts/tests/api_compare/docker-compose.yml
src/bin/forest-cli.rs
src/bin/forest-tool.rs
src/bin/forest-wallet.rs
src/bin/forest.rs
src/cli/humantoken.rs
src/rpc/methods/state.rs
src/shim/error.rs
src/shim/randomness.rs
src/shim/sector.rs
src/shim/state_tree.rs
src/shim/version.rs
src/state_migration/tests/mod.rs
src/utils/encoding/mod.rs
src/utils/io/mod.rs
src/utils/io/progress_log.rs
tests/config.rs
tests/keystore_tests.rs

- shorten `forest_filecoin` to `forest` in log
Closes #4649

fix(tracing): rename lib name from forest_filecoin to forest

---

CHANGELOG.md
src/rpc/methods/eth.rs
src/shim/actors/builtin/eam.rs

- fixes deserialization issue in `EthGetBlockReceipts`. The main fix comes from using `Deserialize_tuple` internally, but it's more maintainable to simply import the correct data structure.
-
```
api-compare-1  | | RPC Method                               | Forest                                                                | Lotus      |
api-compare-1  | |------------------------------------------|-----------------------------------------------------------------------|------------|
api-compare-1  | | Filecoin.EthGetBlockReceipts (3)         | Rejected("Fallback deserialization failed: Eof. Original error: Eof") | Valid      |
api-compare-1  | | Filecoin.EthGetBlockReceipts (9)         | CustomCheckFailed …
```

fix: incorrect params serialisation for EthGetBlockReceipts

---

Cargo.lock
Cargo.toml
deny.toml
interop-tests/src/tests/bitswap_go_compat.rs
src/libp2p/gossip_params.rs
src/libp2p/hello/behaviour.rs
src/libp2p/service.rs
src/libp2p_bitswap/internals/event_handlers.rs
src/libp2p_bitswap/tests/request_manager.rs

- upgrade `libp2p`
- resolve `RUSTSEC-2024-0384`
Closes #5069

chore(deps): upgrade libp2p and resolve RUSTSEC-2024-0384

---

.github/workflows/forest.yml

- disabling Curio Devnet check given it's silently failing anyway. There's no point in spending CPU cycles and GHA minutes until https://github.com/ChainSafe/forest/issues/5171 is resolved
Closes

chore: (temporarily?) disable curio devnet job

---

src/cli/subcommands/f3_cmd.rs

- Port https://github.com/filecoin-project/lotus/pull/12840 to Forest
```
➜  lotus git:(master) ✗ lotus f3 pt gp 1179 1167 8888
{
"Instance": 126141,
"FromEC": false,
"PowerTable": {
"CID": "bafy2bzaced7pp3jghq3hdgaayl3uxcofhuedq6wwqm3pyer3oiywvqofobfto",
"ScaledTotal": 65524
},
"ScaledSum": 12,
"Proportion": 0.0001831390025028997,
"NotFound": [
8888
]
}
```
```
➜  forest git:(hm/f3-power-proportion-non-existing-actors) forest-cli f3 pt gp 1179 1167 8888
{
"Instance": 126141,
"FromEC": false,
"PowerTable": {
"CID": "bafy2bzaced7pp3jghq3hdgaayl3uxcofhuedq6wwqm3pyer3oiywvqofobfto",
"ScaledTotal": 65524
},
"ScaledSum": 12,
"Proportion": 0.0001831390025028997,
"NotFound": [
8888
]
}
```
Closes #5174
[1]: …

fix(cli): handle non-existing actors gracefully in F3 power proportion CLI

---

src/daemon/mod.rs
src/f3/mod.rs
src/health/endpoints.rs
src/rpc/methods/f3.rs

- check f3 running status on healthz and readyz endpoints
```
➜  forest git:(hm/f3-health-check) forest-cli healthcheck ready
[+] sync complete
[+] epoch up to date
[+] rpc server running
[+] eth mapping up to date
[+] f3 running
```
Closes #4955

fix: check f3 running status on healthz and readyz endpoints

---

scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline

- can't reproduce the issue with recent snapshot, so let's assume it works now (might have been fixed via other fixes). If it happens again, we can revert and re-open with reproducible input.
Closes https://github.com/ChainSafe/forest/issues/4432

chore: remove `Filecoin.StateReply` from filter lists

---

.github/workflows/docker.yml
.github/workflows/forest.yml
.github/workflows/unit-tests.yml

- use the new, publicly available GH ARM runner instead of buildjet (should save some costs)
- use GH runner in snapshot parity checks - it's run only on main, so we don't need it to run fast.
Closes

chore: less buildjet

---

CHANGELOG.md
scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline
src/rpc/methods/eth.rs

- Fix flakyness in `Filecoin.EthGetTransactionReceipt` and `Filecoin.EthGetTransactionReceiptLimited` methods, because wrong tipset was sometimes passed to `new_eth_tx_receipt`.
Closes #4996

Fix incorrect Tipset passed to `new_eth_tx_receipt`

---

CHANGELOG.md
scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline
src/rpc/methods/eth/filter/mod.rs
src/tool/subcommands/api_cmd.rs

- Fix range tipset lookups that were not taking null rounds into account.
```bash
forest-tool api compare --lotus /ip4/127.0.0.1/tcp/1234/http --forest /ip4/127.0.0.1/tcp/2345/http forest_snapshot_calibnet_2025-01-30_height_2364216.forest.car.zst --filter EthGetLogs -n 900
| Filecoin.EthGetLogs (1800) | Valid  | Valid |
```
Closes https://github.com/ChainSafe/forest/issues/5213

Fix loading tipsets past the range

---

CHANGELOG.md
src/cli/humantoken.rs

205.4 FIL over 205400 milliFIL.
- This PR changes the behaviour of the FIL pretty-printer. It's a change in behaviour rather than a bug fix.
- Previously, the pretty-printer tried to find the biggest prefix that yielded a non-fractional number. Eg. `1001 milliFIL` over `1.001 FIL`. This PR changes the behaviour to find the biggest prefix that yields a number greater than 1.
Closes #4951

fix: favor fractional FIL amounts over a larger number of a smaller unit

---

CHANGELOG.md
documentation/src/offline-forest.md
src/cli/subcommands/healthcheck_cmd.rs
src/health/endpoints.rs
src/health/mod.rs

Currently, we have 3 health check endpoints, namely, `readyz`, `livez` and `healthz` but only 1 CLI command `forest-cli healthcheck ready`. This PR extends the CLI subcommand to support all 3 endpoints
- impl `forest-cli healthcheck live`
- impl `forest-cli healthcheck healthy`
Closes #5246

feat(cli): more healthcheck subcommands

---

docs/docs/users/reference/cli.md
src/cli/subcommands/healthcheck_cmd.rs

- Updates Forest CLI docs to the latest commit in the `main` branch.

[automated] Update Forest CLI docs

---

CHANGELOG.md
src/key_management/wallet.rs
src/key_management/wallet_helpers.rs
src/lib.rs
src/shim/crypto.rs
src/utils/encoding/mod.rs
src/wallet/subcommands/wallet_cmd.rs

-Adds `Delegated` signature and address type in `forest-wallet` 
Closes #4769 

feat: add delegated address in forest-wallet

---

src/blocks/tipset.rs
src/chain/store/chain_store.rs
src/daemon/db_util.rs
src/daemon/mod.rs
src/db/car/any.rs
src/db/car/forest.rs
src/db/car/many.rs
src/db/car/plain.rs
src/db/memory.rs
src/db/mod.rs
src/tool/offline_server/server.rs
src/tool/subcommands/api_cmd/generate_test_snapshot.rs
src/tool/subcommands/api_cmd/test_snapshot.rs

This reverts commit d9e76f613470ef50e1fd32e28f289e99719161e9.
- The HEAD changes (d9e76f613470ef50e1fd32e28f289e99719161e9) are causing Forest to always require a snapshot. For example, running `❯ forest --chain calibnet --encrypt-keystore false --import-snapshot ../snapshots/calibnet` , exiting and then `❯ forest --chain calibnet --encrypt-keystore false` will result in download snapshot prompt.
Closes

Revert "fix(db): fallback to CAR DB head when HEAD_KEY not set (#5223)"

---

.github/workflows/forest.yml
.github/workflows/rust-lint.yml
.github/workflows/unit-tests.yml

- removed scheduled Forest builds. Nobody checks them anyway and we do plenty of builds, outside of weekends.
Closes

chore: remove scheduled Forest builds

---

src/rpc/methods/state.rs

chore: correct CNA method names 4/4 

---

src/daemon/bundle.rs
src/utils/net.rs

The `state_migration_generate_actors_metadata` test has been flaky. Revert the manifest json generation logic for now.
-
Closes

fix(ci): no cache for generating manifest json

---

.github/workflows/docs-required-override.yml

- add an override to required jobs for lints. Right now, lints are not required, but they should be. Without this, docs changes that don't trigger lints wouldn't be mergeable.
Closes

chore: add override to require lint checks

---

CHANGELOG.md
src/tool/subcommands/shed_cmd.rs

- Added `--omit` to filter certain fields from generation, such as `summary` or `description`.
```
forest-tool shed openrpc --help
Dump the OpenRPC definition for the node
Usage: forest-tool shed openrpc [OPTIONS] --path <PATH> [INCLUDE]...
Arguments:
[INCLUDE]...  
Options:
--path <PATH>  Which API path to dump [possible values: v0, v1]
--omit <OMIT>  A comma-separated list of fields to omit from the output (e.g., "summary,description") [possible values: summary, description]
-h, --help         Print help
```
Closes #5243 

Add omit fields option for OpenRPC spec generation

---

CHANGELOG.md
Cargo.lock
Cargo.toml
scripts/tests/calibnet_no_discovery_check.sh
src/cli/subcommands/f3_cmd.rs
src/daemon/mod.rs
src/rpc/methods/eth/types.rs
src/rpc/methods/f3/types.rs
src/tool/subcommands/shed_cmd.rs
src/tool/subcommands/shed_cmd/f3.rs

Part of https://github.com/ChainSafe/forest/issues/5307
-
Lotus code:
```go
var f3CheckActivationRaw = &cli.Command{
Name:  "check-activation-raw",
Usage: "queries f3 parameters contract using raw logic",
Flags: []cli.Flag{
&cli.StringFlag{
Name:  "contract",
Usage: "address contract to query",
},
},
Action: func(cctx *cli.Context) error {
// this code is raw logic for cross-checking
// the cleaner code is in chain/lf3/manifest.go
address, err := ethtypes.ParseEthAddress(cctx.String("contract"))
return fmt.Errorf("trying to parse contract address: %s: %w", cctx.String("contract"), err)
}
ethCall := ethtypes.EthCall{
To:   &address,
Data: must.One(ethtypes.DecodeHexString("0x2587660d")), // method ID of activationInformation()
} …
```

feat(shed): add forest-tool shed f3 check-activation-raw

---

Cargo.lock
rust-toolchain.toml
src/cli/subcommands/mpool_cmd.rs
src/db/mod.rs
src/message_pool/msgpool/provider.rs
src/rpc/methods/common.rs
src/shim/actors/builtin/miner/mod.rs

- upgrade rust toolchain to 1.85.0
- fix new `cargo clippy` warnings
- Rust 2024 upgrade is tracked in https://github.com/ChainSafe/forest/issues/5327
- Cargo resolver version 3 upgrade cannot be made yet until all CI lint tools support it. 
Closes

chore: upgrade rust toolchain to 1.85.0

---

CHANGELOG.md
src/rpc/methods/eth.rs
src/rpc/methods/net.rs

- use Lotus's aliases as outlined in https://github.com/filecoin-project/lotus/blob/a9718c841e1fced8afc6e9fee2db2a2b565acc42/api/eth_aliases.go (discrepancy reported by @AlexeyKrasnoperov)
- added agent type to `Filecoin.Web3ClientVersion`
Closes

fix: map RPC aliases to what Lotus uses + agent name in client version

---

CHANGELOG.md
src/cli/main.rs
src/cli/subcommands/mod.rs

- remove the last remnant of the JavaScript console. It shall forever live in our `git` history. :candle: 
Closes

chore: remove deprecated JS attach

---

CHANGELOG.md
src/rpc/methods/eth/filter/mod.rs
src/rpc/methods/eth/types.rs
src/tool/subcommands/api_cmd/api_compare_tests.rs

- allows addresses in the `EthFilterSpec` accept non-lists as well, thus conforming to Lotus and Eth API,
- tests for the above,
- simplified some calls of the `EthFilterSpec`,
- this fixes the usage of `EthGetLogs` and `EthNewFilter`.
Closes
```
❯ curl --silent -X POST -H "Content-Type: application/json" \
--data '{"jsonrpc":"2.0","id":2,"method":"Filecoin.EthNewFilter","params": [{ "fromBlock": "latest", "toBlock": "latest", "address": ["0x0000000000000000000000000000000000000000"] }] }' \
"http://127.0.0.1:2345/rpc/v1"
{"jsonrpc":"2.0","id":2,"result":"0x9c8f633445fa4c3ea11d2667bf5e821700000000000000000000000000000000"}⏎
❯ curl --silent -X POST -H "Content-Type: application/json" \
--data …
```

feat: allow non-lists for address lists

---

CHANGELOG.md
src/lotus_json/mod.rs

- fixed handling of odd-length inputs for methods such as `Filecoin.EthGetStorageAt` (anything that uses `EthBytes` as a parameter). This should now adhere to Lotus and Eth clients' handling of this (which is somewhat disputable).
Closes

fix: handling of odd-length hex inputs

---

CHANGELOG.md
src/rpc/methods/eth.rs
src/tool/subcommands/api_cmd/api_compare_tests.rs

- `Filecoin.EthGetBlockReceipts` and `Filecoin.EthGetBlockReceiptsLimited` now accepts predefined block parameters on top of the block hash, e.g., `latest`, `earliest`, `pending`.
```
❯ curl --silent -X POST -H "Content-Type: application/json" \
--data '{"jsonrpc":"2.0","id":2,"method":"Filecoin.EthGetBlockReceipts","params": ["latest"]}' \
"http://127.0.0.1:2345/rpc/v1"
{"jsonrpc":"2.0","id":2,"result":[{"transactionHash":"0xac21fb8074a7d39008538ae066aa3d54aa036f7eaf61877cceb51af153f7601a","transactionIndex":"0x0","blockHash":"0x665d2d7d35038cdde374fd4694e62822aa1c1ed6061e6a3261e9de8264a85b53","blockNumber":"0x25424a","from":"0x908fdd9ef6db0b4f8c3a60640f2d6b3c2a7a4f3b","to":"0x58b1b601ee88044f5a7f56b3abec45faa7e7681b","root":"0x00000000000000000000 …
```

feat: accept block params instead of block hash

---

src/networks/drand.rs

Update failing drand unit test to unblock CI. The failing test ensures all the servers on the list serve the correct network with known network parameters. The beacon fetching logic with fallback is tested elsewhere and passing. 
https://filecoinproject.slack.com/archives/C05P37R9KQD/p1740782510773029
> FYI, the League of Entropy quicknet network used by Filecoin is currently in a somewhat degraded state because the Cloudflare HTTP relays are unable to server the quicknet beacons since Tuesday and they most likely won't be able to until next Tuesday. This should not affect Filecoin SPs since Filecoin relies on the drand OptimizingClient and on all 4 HTTP relays (the other 3 are still up) as well as on the Gossipsub relays (which are also still up) …

fix(test): update drand test on quicknet to unblock CI

---

.github/DOCKER_ISSUE_TEMPLATE.md
.github/SNAPSHOT_PARITY_ISSUE_TEMPLATE.md
.github/workflows/forest.yml
.github/workflows/snapshot-parity.yml
scripts/tests/snapshot_parity/docker-compose.yml

The snapshot parity test start failing since we move back to GH hosted runners due to insufficient RAM and disk space.
This PR moves it back to buildjet runners and schedule it weekly to reduce cost.
Successful test run: https://github.com/ChainSafe/forest/actions/runs/13650828365/job/38158739597?pr=5373
Issue on failure: https://github.com/ChainSafe/forest/issues/5374
-
Closes

fix(ci): fix snapshot parity test and schedule it to be weekly

---

Cargo.lock
deny.toml

- ignore RUSTSEC warnings to unblock CI
Closes

fix(ci): ignore RUSTSEC warnings

---

Cargo.lock
deny.toml

Fix `ring` related RUSTSEC issues by bumping `libp2p-tls` since [upstream PR](https://github.com/libp2p/rust-libp2p/pull/5917) has been merged and released.
-
Closes

fix: RUSTSEC issues

---

Cargo.lock
deny.toml

`humantime` is maintained again and `RUSTSEC-2025-0014` has been withdrawn
https://rustsec.org/advisories/RUSTSEC-2025-0014
-
Closes https://github.com/ChainSafe/forest/issues/5405

fix: RUSTSEC-2025-0014

---

src/daemon/db_util.rs

- https://github.com/ChainSafe/forest/pull/5368 introduced an `AppContext` which does a bit too much in certain scenarios, especially in tests. This makes snapshot tests timeout due to actor bundles being downloaded multiple times. This change skips it.
Closes

fix: don't load bundles in snapshot tests

---

scripts/tests/api_compare/docker-compose.yml

- the forest variable was incorrectly placed in the lotus service, causing failures:
```
| Filecoin.EthGetMessageCidByTransactionHash (8)      | Rejected("indexer disabled, enable with chain_indexer.enable_indexer / FOREST_CHAIN_INDEXER_ENABLED") | Valid                                                                                                                                                                                                                                                                |
```
Closes https://github.com/ChainSafe/forest/issues/5426

fix: incorrect placement of forest var in lotus

---

src/chain_sync/chain_follower.rs

- Previously, the chain follower would inform about in-progress downloads of forks. This is rather verbose since there are always a few forks.
- This change hides download notifications for forks. Forks are still fetched, but it happens silently in the background.
Closes

ui: suppress output when downloading forks

---

CHANGELOG.md
src/chain_sync/chain_follower.rs

- Fix stack overflow occurring when running Forest in debug mode
Closes

Fix stack overflow in debug mode

---

CHANGELOG.md
src/tool/subcommands/api_cmd.rs

- Changed the `allow_response_mismatch` flag to `use_response_from` in the `forest-tool api generate-test-snapshot` subcommand. This allows specifying the source of the response to use when generating test snapshots and creating failing tests.
Closes

feat: allow rpcsnaps with failing cases

---

CHANGELOG.md
docs/docs/developers/guides/network_upgrades.md
src/blocks/tipset.rs
src/shim/version.rs
src/state_migration/mod.rs
src/state_migration/nv25/migration.rs
src/tool/subcommands/shed_cmd.rs
src/tool/subcommands/shed_cmd/migration.rs

This PR ports `lotus shed migrate-state` tool into Forest
-
```
➜  forest git:(main) ✗ forest-tool shed migrate-state --chain calibnet 25 bafy2bzaceb2pqqnclk6hptttsuxtcfhzzfewfizk4c6lonrvq7vesddasxkbo
Migrating... state_root: bafy2bzaceaftms6pagbrvjqmhmehjuxuvicbmyjaz4rfe2rke5xnloc4x3v6e, epoch: 2519400
2025-03-26T09:01:57.696451Z  INFO forest::state_migration::common::state_migration: Processed 100000 actors
2025-03-26T09:02:01.296881Z  INFO forest::state_migration::common::state_migration: Processing deferred migrations
2025-03-26T09:02:01.322608Z  INFO forest::state_migration::common::state_migration: Processed 158974 deferred migrations
Done. old_state: bafy2bzaceaftms6pagbrvjqmhmehjuxuvicbmyjaz4rfe2rke5xnloc4x3v6e, new_state: …
```

feat(tool): add forest-tool shed migrate state command

---

src/chain/store/chain_store.rs
src/shim/machine/mod.rs
src/state_manager/mod.rs
src/tool/subcommands/archive_cmd.rs
src/tool/subcommands/snapshot_cmd.rs

Currently, RPC snapshot tests create a new `MultiEngine` for each test case. This PR tries to use a shared MultiEngine for all tests to reduce engine initialization time.
```
PASS [  29.958s] forest-filecoin tool::subcommands::api_cmd::test_snapshot::tests::rpc_regression_tests
PASS [ 145.529s] forest-filecoin tool::subcommands::api_cmd::test_snapshot::tests::rpc_regression_tests
```
-
Closes

fix: speed up rpc snapshot tests by using shared MultiEngine

---

src/blocks/chain4u.rs
src/chain_sync/bad_block_cache.rs
src/chain_sync/chain_follower.rs

- Fix the calculation of available chain fragments. This avoids a situation where Forest repeatedly and unnecessarily loads the same tipset from the DB.
- Remove an invalid short-cut when querying known-bad tipsets. The short-cut would prevent the tipset from being marked as bad and removed from the set of known tipsets.
Closes

fix: improve fork enumeration, delete invalid short-cut

---

Cargo.lock
Cargo.toml

-------
Update the FVM from v4.6.0 to v4.6.1.
This is an opportunistic pricing fix in NI-PoRep and includes https://github.com/filecoin-project/ref-fvm/pull/2119 only. It should be included in the nv25 upgrade.

chore: update fvm to v4.6.1

---

scripts/tests/api_compare/docker-compose.yml
scripts/tests/calibnet_eth_mapping_check.sh
scripts/tests/calibnet_other_check.sh
scripts/tests/harness.sh
src/cli/subcommands/healthcheck_cmd.rs
src/daemon/mod.rs
src/health/endpoints.rs

`forest-cli healthcheck ready --wait` throws an error on CI because the endpoint is not available when `forest` container becomes healthy, which might be caused by the recent `sync wait` logic change. 
This PR mitigates the issue while the actual bug is tracked in https://github.com/ChainSafe/forest/issues/5517
-
Closes https://github.com/ChainSafe/forest/issues/5513

fix: readyz returns 503

---

Cargo.lock

- fixes https://github.com/ChainSafe/forest/actions/runs/14303759563/job/40082951418
```
error[unsound]: Broadcast channel calls clone in parallel, but does not require `Sync`
┌─ /home/runner/work/forest/forest/Cargo.lock:769:1
│
769 │ tokio 1.44.1 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unsound advisory detected
│
├ ID: RUSTSEC-2025-0023
├ Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0023
├ The broadcast channel internally calls `clone` on the stored value when
receiving it, and only requires `T:Send`. This means that using the broadcast
channel with values that are `Send` but not `Sync` can trigger unsoundness if
the `clone` implementation makes use of the …
```

fix: cargo deny on RUSTSEC-2025-0023

---

.github/workflows/docs-auto-update.yml
.github/workflows/lotus-api-bump.yml

- fixes an issue where we have two automated bumps simultaneously, e.g., CLI docs and Lotus version. They would use the default `create-pull-request/patch`, causing a race which in turn might result in, e.g., empty PRs https://github.com/ChainSafe/forest/pull/5525 (re-run was successful https://github.com/ChainSafe/forest/pull/5526). Consecutive commits for the same category will still update the same branch.
Closes

fix: auto update branch name conflict

---

.github/workflows/rust-lint.yml
Makefile

- this makes the installation procedure smarter by figuring out the CPU architecture of the host and downloading the correct binary. Additional translation layers might be introduced in the future for more exotic architectures.
- fixes CPU architecture mismatch https://github.com/ChainSafe/forest/actions/runs/14345905509/job/40215502924 where we downloaded `x86_64` binary for an ARM runner.
Closes https://github.com/ChainSafe/forest/issues/5542

fix: cpu architecture mismatch in CI

---

CHANGELOG.md
src/chain_sync/chain_follower.rs
src/daemon/mod.rs
src/state_manager/mod.rs

- Reject tipsets if they're older than `chain_finality`. We used to reject tipsets if they were older than 1 day but that made little sense.
- Populate the state-root cache on start-up. This improves validation time for the first tipset and it prevents duplicate migrations, effectively acting as a migration cache.
Closes

fix: populate state cache on start-up

---

.github/workflows/docs-required-override.yml
.github/workflows/forest.yml

- run RPC checks on CI only when PR is tagged with `RPC`
Closes

fix(ci): run RPC checks on CI only when PR is tagged with `RPC`

---

Cargo.lock

```
error[vulnerability]: crossbeam-channel: double free on Drop
┌─ /home/runner/work/forest/forest/Cargo.lock:153:1
│
153 │ crossbeam-channel 0.5.14 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ security vulnerability detected
│
├ ID: RUSTSEC-2025-0024
├ Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0024
├ The internal `Channel` type's `Drop` method has a race
which could, in some circumstances, lead to a double-free.
This could result in memory corruption.
Quoting from the
[upstream description in merge request \#1187](https://github.com/crossbeam-rs/crossbeam/pull/1187#issue-2980761131):
> The problem lies in the fact that `dicard_all_messages` …
```

chore: update crossbeam-channel

---

Cargo.lock
src/blocks/tipset.rs
src/rpc/methods/eth.rs
src/state_manager/mod.rs

This PR fixes `EthFeeHistory` failure on CI, by re-computing tipset state when the output is cached but underlying state tree and message receipts are missing (likely introduced by https://github.com/ChainSafe/forest/pull/5540)
RPC tests passed on CI: https://github.com/ChainSafe/forest/actions/runs/14378406720/job/40316604127?pr=5553
It also fixed a few warnings:
```
warning: package `crossbeam-channel v0.5.14` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
--> src/blocks/tipset.rs:67:5
|
67 |     pub fn len(&self) -> usize {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#len_without_is_empty
= note: `#[warn(clippy::len_without_is_empty)]` on by default
```
Changes …

fix(rpc): EthFeeHistory failure on CI

---

CHANGELOG.md
src/rpc/methods/chain.rs
src/tool/subcommands/api_cmd/test_snapshots_ignored.txt

This PR changes:
- `Filecoin.ChainGetMinBaseFee` -> `Forest.ChainGetMinBaseFee`
- Change `Admin` to `Read` permission
Closes: #5558 

fix: change Filecoin.ChainGetMinBaseFee to internal API with read access

---

scripts/tests/api_compare/docker-compose.yml
src/tool/subcommands/api_cmd/api_compare_tests.rs

Lotus node should only be considered ready when F3 certificates are available. This becomes an issue since Forest eth mapping generation logic has been made much faster in https://github.com/ChainSafe/forest/pull/5360
-
Closes https://github.com/ChainSafe/forest/issues/5576
Closes https://github.com/ChainSafe/forest/issues/5577
Closes https://github.com/ChainSafe/forest/issues/5578

fix(ci): transient error in F3GetCertificate

---

.github/workflows/forest.yml
.github/workflows/rpc-parity.yml

The only RPC failure is fixed by https://github.com/ChainSafe/forest/pull/5553
- move docker volumes folder to under `/mnt` which has 60GB+ free space
- remove `Remove unnecessary software` step as it's no longer necessary but takes 1min - [5min](https://github.com/ChainSafe/forest/actions/runs/14403141690/job/40393612129?pr=5530)
```
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          9         9         2.313GB   667.6MB (28%)
Containers      10        3         588.8MB   0B (0%)
Local Volumes   9         9         16.21GB   0B (0%)
Build Cache     11        0         586.5MB   586.5MB
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        72G   37G   35G  52% /
tmpfs           7.9G   84K  7.9G   1% /dev/shm
tmpfs …
```

fix(ci): speed up RPC parity tests by symbol-linking docker volumes instead of removing unnecessary software

---

Cargo.lock
Cargo.toml
src/eth/transaction.rs
src/shim/actors/builtin/power/mod.rs
src/shim/actors/builtin/reward/mod.rs
src/shim/actors/convert.rs
src/shim/clock.rs
src/shim/crypto.rs
src/shim/trace.rs
src/state_manager/utils.rs

-
Closes https://github.com/ChainSafe/forest/issues/5572

chore(deps): bump fvm and fvm_shared

---

docs/docs/users/reference/env_variables.md
src/db/blockstore_with_write_buffer.rs
src/db/mod.rs
src/state_migration/mod.rs
src/tool/subcommands/shed_cmd/migration.rs

As discussed on [slack](https://filecoinproject.slack.com/archives/C029LPZ5N73/p1744674781996969?thread_ts=1744670553.976459&cid=C029LPZ5N73), this PR implements write buffer to speed up state migrations
On my laptop, nv25 mainnet upgrade takes 5m with 10k buffer, and 22m without buffer.
```
➜  forest git:(main) ✗ forest-tool shed migrate-state --chain mainnet 25 bafy2bzacebb44z6iy77lzpkdxosxk5c2rxtyststp6ukvbknfokswi4czrr3i
Migrating... state_root: bafy2bzaced5lda3j6wpzmgglta47xcxdmnxhanxyiugdme4bl3fdieiaot6go, epoch: 4878799
2025-04-21T11:47:32.422007Z  INFO forest::state_migration::common::state_migration: Processed 100000 actors
...
2025-04-21T11:51:27.950242Z  INFO forest::state_migration::common::state_migration: Processed 3500000 actors
2025-04-21T11:51:31.553214Z  INFO …
```

feat(db): use write buffer to speed up state migrations

---

scripts/tests/api_compare/filter-list
scripts/tests/api_compare/filter-list-offline
src/daemon/db_util.rs
src/interpreter/vm.rs
src/rpc/methods/eth/filter/mod.rs
src/state_manager/mod.rs
src/tool/subcommands/index_cmd.rs

- Fix `apply_block_messages` function
- Remove RPC method from filter lists
```bash
forest-tool api compare --lotus /ip4/127.0.0.1/tcp/1234/http --forest /ip4/127.0.0.1/tcp/2345/http forest_snapshot_calibnet_2025-04-22_height_2599416.forest.car.zst --filter ChainGetEvents -n 200
| RPC Method                    | Forest | Lotus |
|-------------------------------|--------|-------|
| Filecoin.ChainGetEvents (254) | Valid  | Valid |
```
Closes #5579

Fix `Filecoin.ChainGetEvents` method

---

scripts/tests/api_compare/docker-compose.yml
src/daemon/mod.rs
src/tool/offline_server/server.rs
src/tool/subcommands/api_cmd/api_compare_tests.rs
src/tool/subcommands/api_cmd/test_snapshot.rs
src/tool/subcommands/snapshot_cmd.rs
src/utils/proofs_api/mod.rs
src/utils/proofs_api/parameters.rs

- this PR fixes inconsistent proof params cache overriding. There isn't a super clean way to do it, given https://crates.io/crates/filecoin-proofs is a pretty invasive library, creating directories on its own and expecting certain environment variables to be available for the process.
Closes

fix: fix parameters cache handling

---

f3-sidecar/api.go
f3-sidecar/run.go
src/networks/mod.rs
src/rpc/methods/f3.rs
src/rpc/methods/state.rs
src/rpc/mod.rs
src/tool/subcommands/api_cmd/test_snapshots_ignored.txt

- use `testnetnet` for joining mainnet Kademlia
- use `filecoin` as mainnet F3 network name in static manifest (Not yet effective until we set F3 activation epoch in code or env var to bypass contract manifest)
- fix mainnet network name in `Filecoin.StateGetNetworkParams` RPC method
- set F3 initial power table on mainnet 
Closes

fix(f3): wrong mainnet network name for joining KAD network

---

CHANGELOG.md
Cargo.lock
Cargo.toml

- prepare release v0.26.1 [Ijon Tichy](https://en.wikipedia.org/wiki/Ijon_Tichy)
Closes

chore(release): prepare release v0.26.1

---

CHANGELOG.md
README.md
docs/docs/users/knowledge_base/jwt_handling.md
scripts/tests/calibnet_no_discovery_check.sh
scripts/tests/calibnet_other_check.sh
scripts/tests/calibnet_stateless_rpc_check.sh
scripts/tests/harness.sh
src/cli_shared/cli/client.rs
src/daemon/context.rs
src/rpc/client.rs

- update daemon to save RPC token to {data_dir}/token by default, to align with Lotus
- update CLI to consume the default token
Closes https://github.com/ChainSafe/forest/issues/4745

feat: (daemon) saves default RPC token and (CLI) consumes it automatically

---

src/tool/subcommands/api_cmd/api_compare_tests.rs

Both implementations return the same result on a certain condition. It's the same error so it should not fail the workflow.
```
| Filecoin.EthTraceFilter (4)                         | Rejected("too many results, maximum supported is 500, try paginating requests with After and Count")                                                                                                                                                        | Rejected("too many results, maximum supported is 500, try paginating requests with After and Count")                                                                                                                                                          |
```
- allow same the tests to pass on same errors in …

fix: allow same errors on `EthTraceFilter`

---

CHANGELOG.md

I'd add it to the section of breaking changes for visibility.
_Originally posted by @LesnyRumcajs in https://github.com/ChainSafe/forest/pull/5652#discussion_r2111337265_
-
Closes

fix: highlight #5652 in changelog breaking section

---

src/chain_sync/chain_follower.rs

I happened to run into https://github.com/ChainSafe/forest/issues/5679 on mainnet after rebooting the node during chain catchup validation. After setting chain head to a few epochs back, the node was still stuck (No tipset download jobs are scheduled), 
With changes in this PR, my node was able to resume following the chain, however, I cannot reproduce the issue, but found another bug https://github.com/ChainSafe/forest/issues/5677
This PR should fix https://github.com/ChainSafe/forest/issues/5677 and might fix https://github.com/ChainSafe/forest/issues/5679
-
Closes https://github.com/ChainSafe/forest/issues/5677
Closes https://github.com/ChainSafe/forest/issues/5679

fix: chain follower gets stuck in some cases

---

src/daemon/mod.rs

- fixes an issue that GC is triggered right after snapshot is imported
Closes

fix(gc): run GC scheduler after snapshot being imported

---

src/rpc/client.rs

- it doesn't seem to be a very useful information outside of debugging and it might fail unit tests locally.
```
thread 'export_empty_archive' panicked at /home/rumcajs/.rustup/toolchains/1.87.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5:
Unexpected stderr, failed var == "Error: input not recognized as any kind of CAR data (.car, .car.zst, .forest.car)"
├── var: "2025-06-06T12:57:50.028448Z  INFO forest::rpc::client: Loaded the default RPC token\nError: input not recognized as any kind of CAR data (.car, .car.zst, .forest.car)\n\nStack backtrace:\n   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from\n   1: <core::result::Result<T,F> as …
```

chore: demote token loading log to debug

---

src/daemon/context.rs

- This fixes a potential issue where non-owners of the JWT token could read it up. Likely not a huge deal unless someone customized their `data_dir` to be outside their home directory (which should have proper checks anyway).
Closes

fix(security): owner-only access admin token

---

src/db/car/forest.rs

Came across a hard-code value and use a constant instead
-
Closes

fix: use constant for forest CAR header compression level

---

.config/nextest.toml
CHANGELOG.md
src/message/signed_message.rs
src/message_pool/msg_chain.rs
src/message_pool/msgpool/mod.rs
src/message_pool/msgpool/msg_pool.rs
src/message_pool/msgpool/selection.rs
src/networks/mod.rs

Follow up of https://github.com/ChainSafe/forest/pull/5729.
- added block message limits (same as in Lotus - 8192 per message type and 10000 globally),
- migrated some refactoring that was made in the Lotus around adding different message chains,
- fixed a few random bugs that I uncovered while implementing the above,
- optimal selection now doesn't fail to pack a block.
Closes https://github.com/ChainSafe/forest/issues/5730

feat: mpool msg limits
